### ISSUE TITLE
你好！我想把这个主题编译到固件里去，但是出现错误。因为我也是小白不太懂

### ISSUE THREAD

**Issue by hexianfu** [jerrykuku/luci-theme-argon#1]
![QQ图片20190419103212](https://user-images.githubusercontent.com/17141299/56402295-42149000-628f-11e9-973a-50408f804fe1.png)

别的另外一个主题https://github.com/apollo-ng/luci-theme-darkmatter 按照他下面的安装方法我能正确安装。但同样方法安装你的却出现了图片中的错误。麻烦帮忙解惑，不胜感激！

**Comment by jerrykuku** [comment]
我不确定是我theme 的问题 你不导入theme 会有问题吗？


 
---原始邮件---
发件人: "hexianfu"<notifications@github.com>
发送时间: 2019年4月19日(星期五) 上午10:36
收件人: "jerrykuku/luci-theme-argon"<luci-theme-argon@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [jerrykuku/luci-theme-argon] 你好！我想把这个主题编译到固件里去，但是出现错误。因为我也是小白不太懂 (#1)




 别的另外一个主题https://github.com/apollo-ng/luci-theme-darkmatter 按照他下面的安装方法我能正确安装。但同样方法安装你的却出现了图片中的错误。麻烦帮忙解惑，不胜感激！

**Comment by hexianfu** [comment]
你是说下载包拖进目录直接安装？

**Comment by jerrykuku** [comment]
这样应该可以的 


------------------
Jerry Liu
Tel:33521646
Mobile:18964723467
	   18621965106
---------------------------------------------
Web Design-Graphics Design-Quality Service


 




------------------ 原始邮件 ------------------
发件人: "hexianfu"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 上午10:42
收件人: "jerrykuku/luci-theme-argon"<luci-theme-argon@noreply.github.com>;
抄送: "老竭力"<jerrykuku@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jerrykuku/luci-theme-argon] 你好！我想把这个主题编译到固件里去，但是出现错误。因为我也是小白不太懂 (#1)




你是说下载包拖进目录直接安装？

**Comment by hexianfu** [comment]
你这个主题，我是在油管一个老友的视频里看到的，感觉很漂亮，然后一搜在豆瓣有个IPK安装包，然后直接安装到路由上了，由于是K2容量太小 想单独只做你这个主题的。结果编译不进去

**Comment by jerrykuku** [comment]
应该可以的 我试过新三 16M 没问题的
不过这个主题停更了 还是有些bug 暂时也不会修复。如果有能力自己修复一下吧。
------------------
Jerry Liu
Tel:33521646
Mobile:18964723467
	   18621965106
---------------------------------------------
Web Design-Graphics Design-Quality Service


 




------------------ 原始邮件 ------------------
发件人: "hexianfu"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 上午10:45
收件人: "jerrykuku/luci-theme-argon"<luci-theme-argon@noreply.github.com>;
抄送: "老竭力"<jerrykuku@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jerrykuku/luci-theme-argon] 你好！我想把这个主题编译到固件里去，但是出现错误。因为我也是小白不太懂 (#1)




你这个主题，我是在油管一个老友的视频里看到的，感觉很漂亮，然后一搜在豆瓣有个IPK安装包，然后直接安装到路由上了，由于是K2容量太小 想单独只做你这个主题的。结果编译不进去

**Comment by hexianfu** [comment]
刚刚我试过直接安装，不知道对不对。我是放在FEEDS/LUCI/THEMES目录下使用  scripts/feeds install luci-theme-argon 安装的
好像不行

**Comment by hexianfu** [comment]
ga520@ga520:~/lede$ scripts/feeds install luci-theme-argon
Ignoring feed 'argon' - index missing
WARNING: No feed for package 'luci-theme-argon' found
ga520@ga520:~/lede$

**Comment by jerrykuku** [comment]
你是官方的openwrt还是lean的？


------------------
Jerry Liu
Tel:33521646
Mobile:18964723467
	   18621965106
---------------------------------------------
Web Design-Graphics Design-Quality Service


 




------------------ 原始邮件 ------------------
发件人: "hexianfu"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 上午10:49
收件人: "jerrykuku/luci-theme-argon"<luci-theme-argon@noreply.github.com>;
抄送: "老竭力"<jerrykuku@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jerrykuku/luci-theme-argon] 你好！我想把这个主题编译到固件里去，但是出现错误。因为我也是小白不太懂 (#1)




ga520@ga520:/lede$ scripts/feeds install luci-theme-argon
 Ignoring feed 'argon' - index missing
 WARNING: No feed for package 'luci-theme-argon' found
 ga520@ga520:/lede$

**Comment by hexianfu** [comment]
lean的

**Comment by hexianfu** [comment]
我感觉你这个界面没什么BUG啊，美观漂亮 好用

**Comment by jerrykuku** [comment]
多少有一点点，
我这边好多人都编译了 没出现过你这个问题啊


------------------
Jerry Liu
Tel:33521646
Mobile:18964723467
	   18621965106
---------------------------------------------
Web Design-Graphics Design-Quality Service


 




------------------ 原始邮件 ------------------
发件人: "hexianfu"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 上午10:52
收件人: "jerrykuku/luci-theme-argon"<luci-theme-argon@noreply.github.com>;
抄送: "老竭力"<jerrykuku@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jerrykuku/luci-theme-argon] 你好！我想把这个主题编译到固件里去，但是出现错误。因为我也是小白不太懂 (#1)




我感觉你这个界面没什么BUG啊，美观漂亮 好用

**Comment by hexianfu** [comment]
你是怎么编译的呢

**Comment by jerrykuku** [comment]
其实我不太编译，很久没编译了 都是别人在编译


------------------
Jerry Liu
Tel:33521646
Mobile:18964723467
	   18621965106
---------------------------------------------
Web Design-Graphics Design-Quality Service


 




------------------ 原始邮件 ------------------
发件人: "hexianfu"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 上午10:55
收件人: "jerrykuku/luci-theme-argon"<luci-theme-argon@noreply.github.com>;
抄送: "老竭力"<jerrykuku@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jerrykuku/luci-theme-argon] 你好！我想把这个主题编译到固件里去，但是出现错误。因为我也是小白不太懂 (#1)




你是怎么编译的呢

**Comment by hexianfu** [comment]
哦 我试试删掉FEEDS 重新下载看看

**Comment by jerrykuku** [comment]
嗯 你多尝试下  我这边可以确认 很多人都成功的编译了。只是我自己不太编译 所以你的问题我也不确定


------------------
Jerry Liu
Tel:33521646
Mobile:18964723467
	   18621965106
---------------------------------------------
Web Design-Graphics Design-Quality Service


 




------------------ 原始邮件 ------------------
发件人: "hexianfu"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 上午10:57
收件人: "jerrykuku/luci-theme-argon"<luci-theme-argon@noreply.github.com>;
抄送: "老竭力"<jerrykuku@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jerrykuku/luci-theme-argon] 你好！我想把这个主题编译到固件里去，但是出现错误。因为我也是小白不太懂 (#1)




哦 我试试删掉FEEDS 重新下载看看

**Comment by hexianfu** [comment]
哎！还是不行 跟1楼的图一样 找不到目录

**Comment by hexianfu** [comment]
![QQ图片20190419110533331157](https://user-images.githubusercontent.com/17141299/56403279-227f6680-6293-11e9-9f5b-54a36a46d8dc.png)  又安装一遍，dark那个主题没问题

**Comment by jerrykuku** [comment]
你是使用lean的源码编译的嘛？


------------------
Jerry Liu
Tel:33521646
Mobile:18964723467
	   18621965106
---------------------------------------------
Web Design-Graphics Design-Quality Service


 




------------------ 原始邮件 ------------------
发件人: "hexianfu"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 中午11:06
收件人: "jerrykuku/luci-theme-argon"<luci-theme-argon@noreply.github.com>;
抄送: "老竭力"<jerrykuku@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jerrykuku/luci-theme-argon] 你好！我想把这个主题编译到固件里去，但是出现错误。因为我也是小白不太懂 (#1)




  又安装一遍，dark那个主题没问题

**Comment by hexianfu** [comment]
是啊

**Comment by hexianfu** [comment]
你问两次这个问题了，难道LEAN跟官方的目录有区别？才导致没有那个目录。-

**Comment by jerrykuku** [comment]
不是 我这个只适配lean的luci。


------------------
Jerry Liu
Tel:33521646
Mobile:18964723467
	   18621965106
---------------------------------------------
Web Design-Graphics Design-Quality Service


 




------------------ 原始邮件 ------------------
发件人: "hexianfu"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 中午11:12
收件人: "jerrykuku/luci-theme-argon"<luci-theme-argon@noreply.github.com>;
抄送: "老竭力"<jerrykuku@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jerrykuku/luci-theme-argon] 你好！我想把这个主题编译到固件里去，但是出现错误。因为我也是小白不太懂 (#1)




你问两次这个问题了，难道LEAN跟官方的目录有区别？才导致没有那个目录。-

**Comment by hexianfu** [comment]
。。。如1楼图里说的那几个目录 还真没搜索到-   -

**Comment by jerrykuku** [comment]
你用TG吗？或者微信 如果用TG 加我的TG群吧
https://t.me/PIN1Group


------------------
Jerry Liu
Tel:33521646
Mobile:18964723467
	   18621965106
---------------------------------------------
Web Design-Graphics Design-Quality Service


 




------------------ 原始邮件 ------------------
发件人: "hexianfu"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 中午11:13
收件人: "jerrykuku/luci-theme-argon"<luci-theme-argon@noreply.github.com>;
抄送: "老竭力"<jerrykuku@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jerrykuku/luci-theme-argon] 你好！我想把这个主题编译到固件里去，但是出现错误。因为我也是小白不太懂 (#1)




。。。如1楼图里说的那几个目录 还真没搜索到-   -

**Comment by hexianfu** [comment]
百度这个主题 只搜到一篇豆瓣分享这个主题IPK的文章，想多找点文章来看看斗不行哎！

**Comment by jerrykuku** [comment]
这个主题本来我就是用来适配单个设备的。
没想适配所有 但一般都能用


------------------
Jerry Liu
Tel:33521646
Mobile:18964723467
	   18621965106
---------------------------------------------
Web Design-Graphics Design-Quality Service


 




------------------ 原始邮件 ------------------
发件人: "hexianfu"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 中午11:15
收件人: "jerrykuku/luci-theme-argon"<luci-theme-argon@noreply.github.com>;
抄送: "老竭力"<jerrykuku@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jerrykuku/luci-theme-argon] 你好！我想把这个主题编译到固件里去，但是出现错误。因为我也是小白不太懂 (#1)




百度这个主题 只搜到一篇豆瓣分享这个主题IPK的文章，想多找点文章来看看斗不行哎！
