### ISSUE TITLE
登录页面背景图是否可以改为自己固定的

### ISSUE THREAD

**Issue by ifeng361** [jerrykuku/luci-theme-argon#102]
登录时每天都从Bing背景图库加载了一张背景图，我想改为自己喜欢的固定图片，不再希望调用bing图片的AIP。一直都没有找到更改的代码文件，有哪位知道请帮忙告知，谢谢。

**Comment by jerrykuku** [comment]
增加可自定义登录背景功能，请自行将文件上传到/www/luci-static/argon/background 目录下，支持jpg png gif格式图片，主题将会优先显示自定义背景，多个背景为随机显示，系统默认依然为从bing获取【v1.6.4】
