### ISSUE TITLE
是否可以增加对OpenWrt SNAPSHOT / LuCI 17.01 Lienol 的支持？

### ISSUE THREAD

**Issue by geekbb** [jerrykuku/luci-theme-argon#105]
如题

**Comment by jerrykuku** [comment]
17.01 是什么版本？

**Comment by eggydutch** [comment]
> 17.01 是什么版本？

![photo_2021-01-14_01-34-38](https://user-images.githubusercontent.com/59375032/104488033-cb91f700-5608-11eb-9fe9-efc7cd3fb5c3.jpg)
大佬可以支持么？

**Comment by jerrykuku** [comment]
试试 v1.70

**Comment by lon91ong** [comment]
> 试试 v1.70

怎样在编译时选择版本? 改Makefile中的`PKG_VERSION:=2.2.7`为`PKG_VERSION:=1.7.2` ???

**Comment by chinasoul** [comment]
> 

试了1.70，安装上没啥问题
[Powered by LuCI Master (git-20.191.36863-eee6bae)](https://github.com/openwrt/luci) / [ArgonTheme v1.7.0](https://github.com/jerrykuku/luci-theme-argon) / LEDE Reboot 17.01-SNAPSHOT r4046-beaa2ecc10
