### ISSUE TITLE
在readme文档里面写18.06的1.64登录界面添加了毛玻璃特效,release里面没有提到...希望可以添加

### ISSUE THREAD

**Issue by pikachullk** [jerrykuku/luci-theme-argon#107]
如题~
现在编译使用了1.6.6貌似登录界面貌似依然没有毛玻璃特效啊~
希望可以添加~
真的非常好看~

**Comment by jerrykuku** [comment]
麻烦告知下浏览器版本，这个需要比较高版本的chrome内核

**Comment by pikachullk** [comment]
> 
> 
> 麻烦告知下浏览器版本，这个需要比较高版本的chrome内核

firefox 79.0.....

**Comment by jerrykuku** [comment]
firefox 就不能确定了

**Comment by pikachullk** [comment]
> 
> 
> firefox 就不能确定了

是的...我用edge测试有的.....原来是浏览器问题

**Comment by pikachullk** [comment]
> 
> 
> firefox 就不能确定了

大佬再请教一下~能不能有声音按钮默认开启的设置?

**Comment by jerrykuku** [comment]
不行的，最新的chrome 要求 如果要能自动播放 必须要静音。我们不是专业视频网站 他们有白名单。

**Comment by pikachullk** [comment]
> 
> 
> 不行的，最新的chrome 要求 如果要能自动播放 必须要静音。我们不是专业视频网站 他们有白名单。

了解了~谢谢大佬~您的主题很漂亮~很好用~
