### ISSUE TITLE
最新版主题暗黑模式在官方master下升级固件，无法勾选或去除“保留当前配置”前的对勾！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [jerrykuku/luci-theme-argon#108]
**暗黑模式下：**
![image](https://user-images.githubusercontent.com/45259624/90675503-25c2a200-e28d-11ea-9e81-229a0e791a60.png)

**正常情况下可以选择，见图：**
![image](https://user-images.githubusercontent.com/45259624/90675710-70441e80-e28d-11ea-83dc-9f760c11834c.png)

**Comment by jerrykuku** [comment]
![image](https://user-images.githubusercontent.com/9485680/90720270-d6aa5a80-e2e8-11ea-950f-7cbf8cdcf248.png)
已经更新
