### ISSUE TITLE
[request support OpenWrt 19.07] There some bug occur in it.

### ISSUE THREAD

**Issue by Mosney** [jerrykuku/luci-theme-argon#11]
OpenWrt official branch already release two rc versions for 19.07, looks luci has an upgrade and I noticed many luci-app needs to adapt, Include [luci-app-adguardhome](https://github.com/rufengsuixing/luci-app-adguardhome/issues/8), [luci-theme-rosy](https://github.com/rosywrt/luci-theme-rosy/issues/65), and also, luci-theme-argon also face some problem, until now I found these following:
- Localization in most page does not work only show English.  (as same as luci-theme-rosy)
- After click save&apply button, notice message will hide behind the main page. <details><summary>Screenshot:</summary>
![image](https://user-images.githubusercontent.com/22477230/70424055-afd52c80-1aa9-11ea-8067-cb015356a529.png)</details>
- Software section, remove button work but msg box shown in the page bottom.<details><summary>Screenshot:</summary>![image](https://user-images.githubusercontent.com/22477230/70424219-faef3f80-1aa9-11ea-925d-03a9a88b742a.png)</details>

**Comment by jerrykuku** [comment]
Current version does not fit for 19.07,  i will try to fix these in next few days.

**Comment by gorquan** [comment]
Support 19.07？

**Comment by subtilt** [comment]
Any news on the current state of the Argon theme in 19.07? Is it still buggy? I was getting the same result as Mosney. I also couldn't hit apply on certain buttons in the GUI. Are you working on a fix for Argon in 19.07? Would be appreciated!

**Comment by jerrykuku** [comment]
I’m working on it ，please wait a few days。

**Comment by subtilt** [comment]
Great news! Thank you for letting me know

**Comment by jerrykuku** [comment]
it is working with 19.07 now @subtilt  @Mosney

**Comment by Mosney** [comment]
Thx for your contribution!

**Comment by subtilt** [comment]
Excellent! Thank you very much
