### ISSUE TITLE
Login page not working

### ISSUE THREAD

**Issue by Arxk** [jerrykuku/luci-theme-argon#114]
Hello, I love this theme, amazing work.

Do you know what can cause the login page to not work? I uploaded an image to **/www/luci-static/argon/background/image.jpg** but doesn't show. I installed the latest release.

![image](https://user-images.githubusercontent.com/8551650/91241463-8e38d580-e70a-11ea-8381-02210d08caf8.png)

```
Model: TP-Link Archer C7 v2
Firmware Version: OpenWrt 19.07.3 r11063-85e04e9f46 / LuCI openwrt-19.07 branch git-20.136.49537-fb2f363
Kernel Version: 4.14.180
```

**Comment by jerrykuku** [comment]
Can you try to update luci through the package? Maybe the luci version is not the latest.

**Comment by morozdan2003** [comment]
I have the problem such as in this issue. Updating LuCI does not solve the trouble. Changing of picture does not work too.

**Comment by Arxk** [comment]
I upgraded OpenWrt from 19.07.3 to 19.07.7 and the problem was fixed. I'm not sure what package needed to be updated, but updating was the solution.
