### ISSUE TITLE
升级到最新的1.6.9版本页面报500 内部服务器错误

### ISSUE THREAD

**Issue by dolphinpaopao** [jerrykuku/luci-theme-argon#115]
作者你好，我今天升级到最新的主题版本遇到了和上次类似的错误。lean源码，主题为最新。
1、刷好固件后，进入系统→语言和界面→主题，选择Argon，点击保存和应用。刷新页面后主题不会生效，上传1.6.8版本，切换主题生效，但以下两个错误依旧存在；
2、点击服务→SSR，报500内部服务器错误，此时，方框1里面的按钮均失效，可以点击退出或者方框2里面的任一菜单切换一下，方框1的菜单又重新生效。
![图示2](https://user-images.githubusercontent.com/20945941/91426630-59a25680-e88f-11ea-8ee8-24bab8bfa5c5.png)
2、ssr的服务器节点和状态两个页面有500内部服务器错误出现，但这两个页面的报错不会引起（状态、系统、服务、网络存储等）这些菜单按钮失效。
![图示3](https://user-images.githubusercontent.com/20945941/91427011-ddf4d980-e88f-11ea-8cfe-28278d6e8d0f.png)
![图示4](https://user-images.githubusercontent.com/20945941/91427245-2f04cd80-e890-11ea-943b-33cc02e5dea4.png)

**Comment by dolphinpaopao** [comment]
回退到1.6.8的源码，今天重新编译了一次固件，问题解决，1.6.9的某些改动和ssrp存在不兼容。我先用着1.6.8了，感谢作者。

**Comment by abc2251259** [comment]
作者你好，我用L大最新源码编译的OpenWrt R20.8.27，用了您的这个插件发现访问LEDE的时候打开网页会比较慢，然后点击左侧防火墙的时候整个列表会自动收缩到一起，换其他主题没有这个问题，请问是不是兼容性的问题...

**Comment by jerrykuku** [comment]
防火墙这里 因为 dom 数据比较多 js会在dom完成后才会起作用 所以才会 搜索在一起。正常现象

**Comment by abc2251259** [comment]
哦哦哦，感谢，就是换了这个主题打开WEB管理页面会比较慢，不知道能不能设置一下~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jerrykuku/luci-theme-argon"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月5日(星期六) 凌晨1:21
收件人:&nbsp;"jerrykuku/luci-theme-argon"<luci-theme-argon@noreply.github.com&gt;;
抄送:&nbsp;"Mydsh"<287682291@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jerrykuku/luci-theme-argon] 升级到最新的1.6.9版本页面报500 内部服务器错误 (#115)





 
防火墙这里 因为 dom 数据比较多 js会在dom完成后才会起作用 所以才会 搜索在一起。正常现象
