### ISSUE TITLE
lean大神做的OpenWrt SSRP版本无法使用主题，日志如下

### ISSUE THREAD

**Issue by justin0705** [jerrykuku/luci-theme-argon#116]
固件版本：OpenWrt R20.7.20 built by Lean & KFERM / LuCI Master (git-20.223.26773-d18ef13)
内核版本：5.4.51
Sun Aug 30 23:11:53 2020 daemon.err uhttpd[2341]: uci: Entry not found
Sun Aug 30 23:11:53 2020 daemon.err uhttpd[2341]: uci: Entry not found
Sun Aug 30 23:12:01 2020 daemon.err uhttpd[2341]: /usr/lib/lua/luci/dispatcher.lua:469: Failed to execute template dispatcher target for entry '/admin/status/overview'.
Sun Aug 30 23:12:01 2020 daemon.err uhttpd[2341]: The called action terminated with an exception:
Sun Aug 30 23:12:01 2020 daemon.err uhttpd[2341]: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'admin_status/index'.
Sun Aug 30 23:12:01 2020 daemon.err uhttpd[2341]: A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
Sun Aug 30 23:12:01 2020 daemon.err uhttpd[2341]: A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/argon/header'.
Sun Aug 30 23:12:01 2020 daemon.err uhttpd[2341]: A runtime error occured: [string "/usr/lib/lua/luci/view/themes/argon/header...."]:17: attempt to call field 'menu_json' (a nil value)
Sun Aug 30 23:12:01 2020 daemon.err uhttpd[2341]: stack traceback:
Sun Aug 30 23:12:01 2020 daemon.err uhttpd[2341]: 	[C]: in function 'assert'
Sun Aug 30 23:12:01 2020 daemon.err uhttpd[2341]: 	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
Sun Aug 30 23:12:01 2020 daemon.err uhttpd[2341]: 	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: /usr/lib/lua/luci/dispatcher.lua:469: Failed to execute template dispatcher target for entry '/admin/status/overview'.
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: The called action terminated with an exception:
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'admin_status/index'.
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/argon/header'.
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: A runtime error occured: [string "/usr/lib/lua/luci/view/themes/argon/header...."]:17: attempt to call field 'menu_json' (a nil value)
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: stack traceback:
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: 	[C]: in function 'assert'
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: 	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: 	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: /usr/lib/lua/luci/dispatcher.lua:469: Failed to execute template dispatcher target for entry '/admin/status/overview'.
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: The called action terminated with an exception:
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'admin_status/index'.
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/argon/header'.
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: A runtime error occured: [string "/usr/lib/lua/luci/view/themes/argon/header...."]:17: attempt to call field 'menu_json' (a nil value)
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: stack traceback:
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: 	[C]: in function 'assert'
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: 	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
Sun Aug 30 23:12:06 2020 daemon.err uhttpd[2341]: 	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by jerrykuku** [comment]
你装的哪个版本？ 大家都是lean 源码 就你的不能用

**Comment by justin0705** [comment]
> 你装的哪个版本？ 大家都是lean 源码 就你的不能用

![S00903-20443301](https://user-images.githubusercontent.com/38656632/92116381-60fac000-edb9-11ea-92ad-42b52642ab26.png)
从这个频道下载的

**Comment by justin0705** [comment]
抱歉，是我的问题，才发现需要下载lean版的
