### ISSUE TITLE
4英寸屏幕上登陆键被遮挡

### ISSUE THREAD

**Issue by Paris0-0** [jerrykuku/luci-theme-argon#117]
4英寸屏幕登陆界面异常，如图
![2D8A67AC-124E-4CFA-86E6-51158C8929A9](https://user-images.githubusercontent.com/11692160/91673211-9ad38880-eb65-11ea-9ec5-5670432fbf4d.png)

**Comment by RikudouPatrickstar** [comment]
去 /usr/lib/lua/luci/view/themes/argon/footer.htm 里面把下面这段注释掉就好了：
<a class="luci-link" href="https://github.com/openwrt/luci">Powered by <%= ver.luciname 
<a href="https://github.com/jerrykuku/luci-theme-argon">
<%= ver.distversion %>

**Comment by jerrykuku** [comment]
下一个版本 我会针对 更小的屏幕 修复一下，最近比较忙。没有精力更新

**Comment by RikudouPatrickstar** [comment]
> 下一个版本 我会针对 更小的屏幕 修复一下，最近比较忙。没有精力更新

感谢也期待大佬改进，luci-theme-argon 细节处理越来越好了

**Comment by Paris0-0** [comment]
> 下一个版本 我会针对 更小的屏幕 修复一下，最近比较忙。没有精力更新

好的，谢谢大佬
