### ISSUE TITLE
How to activate blur mode ?

### ISSUE THREAD

**Issue by jakues** [jerrykuku/luci-theme-argon#119]

**Comment by jakues** [comment]
when I use chrome the blur is active but when I use firefox its not active

**Comment by jerrykuku** [comment]
Firefox From version 70: this feature is behind the layout.css.backdrop-filter.enabled preference (needs to be set to true) and the gfx.webrender.all preference (needs to be set to true). To change preferences in Firefox, visit about:config.

**Comment by jerrykuku** [comment]
![image](https://user-images.githubusercontent.com/9485680/92301638-d4f2bf00-ef97-11ea-9ad9-90ccd3bd9411.png)
backdrop-filter support information

**Comment by jakues** [comment]
> ![image](https://user-images.githubusercontent.com/9485680/92301638-d4f2bf00-ef97-11ea-9ad9-90ccd3bd9411.png)
> backdrop-filter support information

ok thanks. Will trying it

**Comment by jakues** [comment]
![image](https://user-images.githubusercontent.com/34295920/92347633-e4d6e400-f0fa-11ea-993f-6932135a10f4.png)
![image](https://user-images.githubusercontent.com/34295920/92347702-18b20980-f0fb-11ea-8e69-402106f3aac1.png)
![image](https://user-images.githubusercontent.com/34295920/92347726-2ff0f700-f0fb-11ea-95e7-a48a45b21b26.png)

**Comment by jerrykuku** [comment]
![image](https://user-images.githubusercontent.com/9485680/92377204-60a25200-f136-11ea-8e16-4bdefa888132.png)

**Comment by jakues** [comment]
how it looks good with blur. on my firefox wasn't blur

**Comment by jerrykuku** [comment]
what's version of your firefox?

**Comment by jakues** [comment]
I think 80.0.1.
firefox aarch64 ubuntu 20.04

**Comment by jerrykuku** [comment]
Maybe firefox of this platform does not support backdrop-filter. I tested on windows 10, and firefox version is 80.0.1 too.

**Comment by jakues** [comment]
nah I think soo
on windows I tested normal haha
