### ISSUE TITLE
Incompatible with IE11 of Windows10

### ISSUE THREAD

**Issue by fight-fly** [jerrykuku/luci-theme-argon#120]
Report a bug.

The left is gone.

![theme](https://user-images.githubusercontent.com/70288629/91825965-8b406680-ec6f-11ea-8732-6d489b8ff3ba.jpg)

Can you fix it?
Thank you.

OS: LuCI Master git-20.238.61574-c0e597c / OpenWrt SNAPSHOT

**Comment by jerrykuku** [comment]
I will test it tomorrow
