### ISSUE TITLE
luci-app-adguardhome显示错误

### ISSUE THREAD

**Issue by Hey-Leo** [jerrykuku/luci-theme-argon#121]
![image](https://user-images.githubusercontent.com/59218230/91971332-9bc60f00-ed4b-11ea-8041-a586660aee6d.png)
固件版本`R20.8.27`
Argon版本`V1.6.9`
插件源码
https://github.com/rufengsuixing/luci-app-adguardhome.git

**Comment by jerrykuku** [comment]
这是插件的问题 不是 主题引起的吧

**Comment by Hey-Leo** [comment]
好像是那么回事，那我关了，
