### ISSUE TITLE
Passwall 显示错误

### ISSUE THREAD

**Issue by People-11** [jerrykuku/luci-theme-argon#122]
![Screenshot_20200905-114206.png](https://user-images.githubusercontent.com/41558215/92296992-1c178a80-ef6d-11ea-8e99-70b56ced96b3.png)

**Comment by jerrykuku** [comment]
这个问题怎么说呢， 那个白色的问题 原因是passwall 自己定义了 块的背景颜色 ，不受主题的控制。 所以这不是主题能解决的。
