### ISSUE TITLE
我的登录界面显示不正常

### ISSUE THREAD

**Issue by vickeyrao** [jerrykuku/luci-theme-argon#125]
安装完皮肤，重启路由器，登录界面就变成这样，和简介里面的完全不同，使用了各种浏览器都是这样，请问这是什么问题。

![20200907162222](https://user-images.githubusercontent.com/70885220/92365143-55472a80-f126-11ea-800d-67c3ede89f94.png)

**Comment by jerrykuku** [comment]
试试看上一个版本呢

**Comment by vickeyrao** [comment]
依然是这样

![批注 2020-09-07 183511](https://user-images.githubusercontent.com/70885220/92378755-ea531f00-f138-11ea-8a2f-2d9d5043dd69.jpg)

**Comment by jerrykuku** [comment]
有telegram 么？ 有的话TG上联系我 https://t.me/jerryk6

**Comment by vickeyrao** [comment]
问题解决了，我把luci有关的软件全部更新后就好了，升级到最新的2.2.4也没有问题。谢谢你。
皮肤真的很赞！！
![批注 2020-09-07 191704](https://user-images.githubusercontent.com/70885220/92382203-cbf02200-f13e-11ea-9f86-0469c9481a71.jpg)
