### ISSUE TITLE
最新版没有自动切换夜间模式

### ISSUE THREAD

**Issue by jh0072110** [jerrykuku/luci-theme-argon#131]
<img width="595" alt="截屏2020-09-09 下午9 35 11" src="https://user-images.githubusercontent.com/50496854/92605589-7d7c8800-f2e4-11ea-8459-e009ba368e31.png">
如图所示，持续保持在日间模式，luci 18.06

**Comment by jerrykuku** [comment]
版本多少？

**Comment by jh0072110** [comment]
> 版本多少？

<img width="742" alt="截屏2020-09-09 下午9 43 12" src="https://user-images.githubusercontent.com/50496854/92606479-8d489c00-f2e5-11ea-9ffe-aa0a815114f4.png">
<img width="594" alt="截屏2020-09-09 下午9 43 24" src="https://user-images.githubusercontent.com/50496854/92606493-90438c80-f2e5-11ea-9b5e-af9ceaab71fd.png">

**Comment by jerrykuku** [comment]
麻烦右键 查看网页源代码 然后保存成txt 发一下

**Comment by jh0072110** [comment]
[未命名.txt](https://github.com/jerrykuku/luci-theme-argon/files/5195607/default.txt)

**Comment by jerrykuku** [comment]
多谢，一个小bug我来修复一下

**Comment by jerrykuku** [comment]
https://github.com/jerrykuku/luci-theme-argon/releases/tag/v1.7.0
问题已经修复，建议luci-app-argon-config 一起安装，可以自定义很多设置

**Comment by jh0072110** [comment]
> 多谢，一个小bug我来修复一下
> 或者你安装一下 luci-app-argon-config

没事，等你修复完我下回编译的时候更新一下就好
