### ISSUE TITLE
不能像1.69哪样用命令切换黑夜模式

### ISSUE THREAD

**Issue by mitsukileung** [jerrykuku/luci-theme-argon#133]
运行 touch /etc/dark 后也不会切换主题模式，之前1.69可以的

**Comment by jerrykuku** [comment]
改变了方式 使用luci-app-argon-config 来修改https://github.com/jerrykuku/luci-theme-argon/releases/download/v1.7.0/luci-app-argon-config_0.7-beta_all.ipk

**Comment by mitsukileung** [comment]
> 
> 
> 改变了方式 使用luci-app-argon-config 来修改https://github.com/jerrykuku/luci-theme-argon/releases/download/v1.7.0/luci-app-argon-config_0.7-beta_all.ipk

谢谢提醒！
