### ISSUE TITLE
建议：登录框最好能居中显示

### ISSUE THREAD

**Issue by weweyes** [jerrykuku/luci-theme-argon#134]
建议：登录框最好能居中显示，如果能在argon配置插件中设置就完美了

![Snipaste_2020-09-13_21-10-27](https://user-images.githubusercontent.com/59646715/93018873-b890fb00-f605-11ea-827f-3a5a7d40b8f9.jpg)

**Comment by jerrykuku** [comment]
目前这样竖条的效果 不太适合居中。或许未来的某个版本会还原成居中的。

**Comment by zkevinzh** [comment]
希望能够增加可以选择登录框右置的选项。有些图片被左侧登录框遮挡

**Comment by jerrykuku** [comment]
右置可以考虑

**Comment by tanst** [comment]
修改 `/www/luci-static/argon/css/cascade.css` 中的 `.login-page .login-container:margin-left: 36%;` 可以居中，36%差不多居中了
