### ISSUE TITLE
argon主题同名冲突怎么处理？

### ISSUE THREAD

**Issue by weweyes** [jerrykuku/luci-theme-argon#135]
请教各位，lean源码中已经有了argon主题，跟jerrykuku的argon主题同名了，想用jerrykuku的argon主题替换lean源码中的argon主题，应该怎么做？

**Comment by jerrykuku** [comment]
使用我的package https://github.com/jerrykuku/openwrt-package
theme 选择argon 18.06 即可

**Comment by weweyes** [comment]
> 使用我的package https://github.com/jerrykuku/openwrt-package
> theme 选择argon 18.06 即可

非常感谢
