### ISSUE TITLE
安装之后界面是一片空白

### ISSUE THREAD

**Issue by li-xunhuan** [jerrykuku/luci-theme-argon#136]
这是我的固件版本

![QQ20200914-165501](https://user-images.githubusercontent.com/10476982/93065307-1e838e00-f6ab-11ea-9e51-527539352b76.png)

**Comment by jerrykuku** [comment]
lean 源码 请安装 1.7.0

**Comment by li-xunhuan** [comment]
emmmmm
只能用老版本啊？

**Comment by jerrykuku** [comment]
两个功能和效果是一样的， 只不过不同的分支。lean 的luci 是老版本 只能用v1.7.0

**Comment by jerrykuku** [comment]
每次更新都是优先 lean 的源码

**Comment by li-xunhuan** [comment]
好的嘞~~
麻烦您啦！！
