### ISSUE TITLE
关于有地方汉化翻译失败

### ISSUE THREAD

**Issue by QingYis** [jerrykuku/luci-theme-argon#139]
主题依赖于luci-base中的po进行汉化
argon主题中的header.htm中检测到用户未设置密码后会提示：
There is no password set on this router. Please configure a root password to protect the web interface and enable SSH.
这段提示在luci-base中是：
There is no password set on this router. Please configure a root password to protect the web interface.
这两个不同导致了luci argon主题中的没有进行汉化翻译

**Comment by jerrykuku** [comment]
ok 近期修复
