### ISSUE TITLE
为什么手机端web界面默认是英语，应该怎么设置让手机端web界面也是默认中文

### ISSUE THREAD

**Issue by QingYis** [jerrykuku/luci-theme-argon#141]
为什么手机端web界面默认是英语，应该怎么设置让手机端web界面也是默认中文

**Comment by ganggangl** [comment]
make menuconfig  -> Modules -> Translations,勾选中文。我这边看到的是手机端和电脑端都是一致的，要么都是中文要么都是英文

**Comment by SpeedPartner** [comment]
无法复现,请先自行排除是否是你的手机系统或者浏览器的问题.
