### ISSUE TITLE
几种异常情况

### ISSUE THREAD

**Issue by lloyd18** [jerrykuku/luci-theme-argon#143]
### 浏览器是Firefox 81，Openwrt是官方master版本。

![Snipaste_2020-09-24_16-12-51](https://user-images.githubusercontent.com/10294460/94119336-5778eb00-fe81-11ea-89cb-be4365161d56.png)
**1.登录后正在载入视图...大概7-8秒后才能显示信息。**

![Snipaste_2020-09-24_16-13-41](https://user-images.githubusercontent.com/10294460/94119561-ab83cf80-fe81-11ea-8687-49b3a358ac23.png)
**2.按登录后需要等待5秒以上才能进入。**

![Snipaste_2020-09-24_16-14-00](https://user-images.githubusercontent.com/10294460/94119978-2947db00-fe82-11ea-95ce-48d4e723a593.png)
**3.左侧空白，刷新才能显示。**

![Snipaste_2020-09-24_16-23-28](https://user-images.githubusercontent.com/10294460/94120124-58f6e300-fe82-11ea-879e-6ca4dc8738a0.png)
**4.超时错误**

![Snipaste_2020-09-24_16-15-49](https://user-images.githubusercontent.com/10294460/94120244-7cba2900-fe82-11ea-8db3-6f6d43389915.png)
**5."退出"对应的图标也不太对吧。**

![Snipaste_2020-09-24_16-17-34](https://user-images.githubusercontent.com/10294460/94120390-a2dfc900-fe82-11ea-95e5-511c782f7604.png)
**6.有时一片空白**

**Comment by lexin8** [comment]
目前都没有这种情况，倒是有时候出现网址后带#符号就点击没反应。尝试下18.06版本吧。
git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git

**Comment by weweyes** [comment]
18.06适配lean的openwrt源码没有问题

**Comment by lysssssss** [comment]
我有登录界面白屏的情况，一直转圈，重新刷新一下就能秒进，经常会遇到这个问题

**Comment by chengxuncc** [comment]
等待5秒可能是路由器时间没有同步
