### ISSUE TITLE
安装主题后无法访问后台

### ISSUE THREAD

**Issue by niushuai233** [jerrykuku/luci-theme-argon#144]
路由：小米路由器青春版 r1c1
固件版本：openwrt lede R20.7.1

问题：
安装主题后无法访问后台
![image](https://user-images.githubusercontent.com/38598775/95422358-c110f300-0971-11eb-9212-c630c424d37d.png)

devtools 查看请求 403
![image](https://user-images.githubusercontent.com/38598775/95422380-cd954b80-0971-11eb-8c78-c93188083669.png)

**Comment by jerrykuku** [comment]
安装错了版本。请使用 18.06的 V1.7.0

**Comment by niushuai233** [comment]
好的 谢谢
