### ISSUE TITLE
直接在线安装后没法显示。

### ISSUE THREAD

**Issue by haihang5000** [jerrykuku/luci-theme-argon#150]
我直接安装。用文件传输后。安装。出现了没法显示。进入路由是空白的。只有恢复要不重格。。
![image](https://user-images.githubusercontent.com/66341226/100490734-7ed98600-3158-11eb-9c6d-30770756c361.png)

**Comment by XiWinnie8964** [comment]
版本装错了。2.*在lede上不能用。试试1.7.*版本。

**Comment by Xunflash** [comment]
> 我直接安装。用文件传输后。安装。出现了没法显示。进入路由是空白的。只有恢复要不重格。。
> ![image](https://user-images.githubusercontent.com/66341226/100490734-7ed98600-3158-11eb-9c6d-30770756c361.png)

应该是有问题，我也是一样的，装的1.7.1版本

**Comment by SpeedPartner** [comment]
应该是之前bing壁纸API的bug,目前已经修复了,如果还存在问题,请重提issue
