### ISSUE TITLE
资源跳出根目录

### ISSUE THREAD

**Issue by coLATin** [jerrykuku/luci-theme-argon#152]
魔改主题的时候发现加载dark模式后，根目录指向www目录了，不再在argon目录下。
<img width="925" alt="iShot2020-12-15 21 08 44" src="https://user-images.githubusercontent.com/749762/102219142-06294680-3f1a-11eb-8823-8b265dc16eb5.png">

另外请教下区分day-dark是通过独立的css文件？
其实提个小小建议能不能建立个识别方法，css变量成对去配就可以，魔改起来非常方便，哈哈
![iShot2020-12-15 21 12 34](https://user-images.githubusercontent.com/749762/102219620-ad0de280-3f1a-11eb-8a5f-d261a605a623.png)

**Comment by jerrykuku** [comment]
目前我是使用独立的css来区分的，你后面提到的方法特别好，我后面尝试下，至于你前面说的目录指向问题我不太明白

**Comment by jerrykuku** [comment]
这是我第一次做 黑白切换，也没有参考啥，就是自己随便想了下 就做了。你这个方法很赞。后面我来修改一版

**Comment by coLATin** [comment]
> 目前我是使用独立的css来区分的，你后面提到的方法特别好，我后面尝试下，至于你前面说的目录指向问题我不太明白

目录问题是这样的：
为了改顶部图，并实现白/黑2种模式，我得通过2张图片去实现，dark模式下，我理解目前是调用了dark.css文件。既然dark.css和cascade.css在同一目录(www/luci-static/argon/css/)下，但是在dark.css里，我发现图片要想准确调用，相对路径已经由原来的argon根目录变为www根目录了。

虽然不太深刻理解openwrt的主题依赖关系，但是这个调用逻辑的确不太对呢....

**Comment by jerrykuku** [comment]
这个其实是我的问题。是这样的，dark.css的加载并不是使用sytle link的方式引入的。我也忘记了当时是因为什么原因，我是通过lua把css文件读取，然后直接写到页面的。如下图。所以dark里面的图片才会变成在www目录下
![image](https://user-images.githubusercontent.com/9485680/102229884-35928000-3f27-11eb-9ade-7fd27e677eeb.png)

**Comment by coLATin** [comment]
> 这个其实是我的问题。是这样的，dark.css的加载并不是使用sytle link的方式引入的。我也忘记了当时是因为什么原因，我是通过lua把css文件读取，然后直接写到页面的。如下图。所以dark里面的图片才会变成在www目录下
> ![image](https://user-images.githubusercontent.com/9485680/102229884-35928000-3f27-11eb-9ade-7fd27e677eeb.png)

哈哈，我说怎么干着自家的装修影响整栋楼了呢，哈哈哈

**Comment by jerrykuku** [comment]
不过你前面那个dark light的切换方式非常好，我后面学习下，改下结构。这个里面好多历史遗留问题，代码乱的我都懒得改。重写又会花费非常多的时间。不过看你的截图，改的很赞。

**Comment by coLATin** [comment]
> 这是我第一次做 黑白切换，也没有参考啥，就是自己随便想了下 就做了。你这个方法很赞。后面我来修改一版

也是折腾过几天hexo的主题，根OP主题有点区别，但是逻辑相通。区别就是hexo后面玩家能自己插入JS和CSS，OP主题就只能指望大大给留个空白diy.css，后面想折腾样式的在这里做样式hacking就可以了。
大大你也可以把样式写在一起，维护方便些。::root下方通用定义，day和dark样式成对出现即可。

**Comment by jerrykuku** [comment]
> > 这是我第一次做 黑白切换，也没有参考啥，就是自己随便想了下 就做了。你这个方法很赞。后面我来修改一版
> 
> 也是折腾过几天hexo的主题，根OP主题有点区别，但是逻辑相通。区别就是hexo后面玩家能自己插入JS和CSS，OP主题就只能指望大大给留个空白diy.css，后面想折腾样式的在这里做样式hacking就可以了。
> 大大你也可以把样式写在一起，维护方便些。::root下方通用定义，day和dark样式成对出现即可。

值得学习。下次按照你的建议更新一下 不过这个diy.css只能存在于argon-config下。要不然就还得自己登录sftp 去修改样式，还是太麻烦，下次看看能不能在config里集成一个css文本编辑框，其实就像wordpress那样

**Comment by jerrykuku** [comment]
你这个魔改的主题样式介意我参考借鉴么？

**Comment by coLATin** [comment]
> 你这个魔改的主题样式介意我参考借鉴么？

不介意，我是基于苹果bigsur的设计和配色标准在你的css里直接改的。

[modcss.zip](https://github.com/jerrykuku/luci-theme-argon/files/5696725/modcss.zip)

所以建议后期能不能帮我们这种玩家插入一个空白diy.css，不直接改原装的css，这样备份还原都简单安全

**Comment by jerrykuku** [comment]
下一个版本应该会加上，上一次把那些散落的颜色值都改成变量我都已经头疼一次了 哈哈。不过以后要优化，还是要尽量的使用变量。这个主题现在也有些迷茫，说实话主题会很快厌倦。但是新的版本怎么变化，有多大的变化一直都是一个比较头疼的问题，可能最后的样子和最初差的很远很远，我怕是变成完全两个主题。

**Comment by coLATin** [comment]
看好你哦，哈哈，第一款支持diy的op主题。做好框架和抽取就可以了，改的美丑是玩家自己的审美，最近受苹果影响巨爱大圆角和极简
