### ISSUE TITLE
在Lean OpenWrt / 网络—交换机下无法显示接口速率

### ISSUE THREAD

**Issue by KevinMX** [jerrykuku/luci-theme-argon#156]
如图。使用其他主题（如netgear/bootstrap等）均正常。使用argon主题的时候不会显示接口协商速率。
使用的为Lean OpenWrt R20.12.12，于12月21日编译。

![image](https://user-images.githubusercontent.com/17025286/102981357-cbd82e80-4543-11eb-8ec0-89993bd11226.png)
![image](https://user-images.githubusercontent.com/17025286/102981382-d5fa2d00-4543-11eb-9dc7-dd579235cfbd.png)
![image](https://user-images.githubusercontent.com/17025286/102981396-d98db400-4543-11eb-9325-2684e2a9e47f.png)

**Comment by jerrykuku** [comment]
由于手上没有带交换机的设备 下次找个设备测试

**Comment by KevinMX** [comment]
![image_2021-02-26_18-05-18](https://user-images.githubusercontent.com/17025286/109286706-90b4ed00-785d-11eb-93e9-72ae7da8f57d.png)
![image_2021-02-26_18-05-40](https://user-images.githubusercontent.com/17025286/109286711-927eb080-785d-11eb-9319-a5a35b31f084.png)
今天看了下，去掉这个 `` style= "display: none;"``之后，端口状态就出来了。

**Comment by KevinMX** [comment]
可能和这里有关？代码看不太懂，不过大概是这里吧（
https://github.com/jerrykuku/luci-theme-argon/blob/dcc62fae29684df77b77cbff0d0940390a13476e/htdocs/luci-static/argon/less/cascade.less#L3708

**Comment by jerrykuku** [comment]
后面我来打个补丁
