### ISSUE TITLE
无法获取bing壁纸导致不能正常显示登陆界面

### ISSUE THREAD

**Issue by peterpei1186861238** [jerrykuku/luci-theme-argon#157]
作者你好，我的单臂路由和主路由都使用了您的主题，但是今天都无法成功加载后台了。
很遗憾现在不能提供版本号
![图片](https://user-images.githubusercontent.com/32994395/103199555-108a0e00-4926-11eb-8a08-3555d6694a7c.png)
用ssh连接路由，top命令发现系统正在一直wget某个bing源，是bing壁纸无法加载的错误，附上wget请求连接和响应
[请求连接](https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US)
`{"images":[{"startdate":"20201227","fullstartdate":"202012270800","enddate":"20201228","url":"/th?id=OHR.NabananoSato_EN-US0456707930_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp","urlbase":"/th?id=OHR.NabananoSato_EN-US0456707930","copyright":"Nabana no Sato garden at night in Kuwana, Japan (© Zoonar GmbH/Alamy)","copyrightlink":"https://www.bing.com/search?q=nabana+no+sato+winter+light+festival&form=hpcapt&filters=HpDate%3a%2220201227_0800%22","title":"Turning darkness into light","quiz":"/search?q=Bing+homepage+quiz&filters=WQOskey:%22HPQuiz_20201227_NabananoSato%22&FORM=HPQUIZ","wp":false,"hsh":"a42f707536efe668874872ee794bbe52","drk":1,"top":1,"bot":1,"hs":[]}],"tooltips":{"loading":"正在加载...","previous":"上一个图像","next":"下一个图像","walle":"此图片不能下载用作壁纸。","walls":"下载今日美图。仅限用作桌面壁纸。"}}`
![1](https://user-images.githubusercontent.com/32994395/103199825-bd648b00-4926-11eb-92b5-ea1318e768e6.PNG)
也许是bing壁纸的版权问题
希望能增加请求超时功能
最后希望作者能越做越好

**Comment by jerrykuku** [comment]
下一版会检查修复

**Comment by jerrykuku** [comment]
这个问题在最新的18.06分支我修复了一下。你可以试试看
