### ISSUE TITLE
对于“For Lean Lede 18.06 LuCI”的 v1.7.0版本登录页面部分显示的建议

### ISSUE THREAD

**Issue by HaneRo** [jerrykuku/luci-theme-argon#158]
对于“For Lean Lede 18.06 LuCI”的 v1.7.0版本
登录页面
当页面宽度小于480但大于420px时页面右侧会有部分非毛玻璃
当页面高度小于566px时背景会跟随页面滚动，建议不要跟随页面滚动

**Comment by jerrykuku** [comment]
近期会修复 多谢提议

**Comment by jerrykuku** [comment]
已经修复
