### ISSUE TITLE
亲，不准备支持下openwrt19.07吗？

### ISSUE THREAD

**Issue by geol** [jerrykuku/luci-theme-argon#16]
如题。在openwrt19.07的源码下编译出来，乍一看似乎没问题。但是！在总览，内存不显示（手机上看的，电脑没试）。还有左侧菜单的图标似乎有点儿问题，还有修改设置似乎都不能保存。

**Comment by jerrykuku** [comment]
之前初步看了下 要修改的东西很多 要花费很多时间 年后吧

**Comment by jerrykuku** [comment]
已经支持19.07和最新的 luci
