### ISSUE TITLE
progressbar 未使用主题色

### ISSUE THREAD

**Issue by helinyun98** [jerrykuku/luci-theme-argon#160]
.cbi-progressbar>div {
    width: 0;
    height: 100%;
    transition: width .25s ease-in;
    background: #5bc0de;
    background: var(--bar-bg);
}

这里取了--bar-bg 而不是--primary，是一个错误吗？

**Comment by jerrykuku** [comment]
master版本吧？ 可能是个错误，因为master测试的不是很多

**Comment by helinyun98** [comment]
我使用的是19.07的主题，使用luci-app-argon-config修改后发现内存使用显示的颜色没有修改
