### ISSUE TITLE
安装主题后，后台无法进去

### ISSUE THREAD

**Issue by calonye** [jerrykuku/luci-theme-argon#161]
![image](https://user-images.githubusercontent.com/45063293/103461518-e8514380-4d59-11eb-970f-c79ab9b4253b.png)
安装主题后，后台无法进去，如题
openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade-20201226.img.gz
固件

**Comment by calonye** [comment]
卸载后就能进去了。
![image](https://user-images.githubusercontent.com/45063293/103461902-aa095380-4d5c-11eb-810e-d85a2913fc27.png)

目前最新版本主题支持r20了么

**Comment by axiaoni** [comment]
貌似是壁纸的接口出问题了，自己放壁纸进去就正常了

**Comment by calonye** [comment]
> 貌似是壁纸的接口出问题了，自己放壁纸进去就正常了

需要怎么操作，感谢指点

**Comment by axiaoni** [comment]
路径/www/luci-static/argon/创建一个background文件夹，图片或者视频放里面

**Comment by calonye** [comment]
> 路径/www/luci-static/argon/创建一个background文件夹，图片或者视频放里面

谢谢，我去试试看

**Comment by jerrykuku** [comment]
主题中貌似不存在 userscript.html 你这个感觉是有问题的

**Comment by calonye** [comment]
> 主题中貌似不存在 userscript.html 你这个感觉是有问题的

不懂啊，我是按说明页面，在shh里面输入命令安装的，安装完就这样了，后面用命令把这个主题卸载了才能进
