### ISSUE TITLE
Versioning css files uncompressed?

### ISSUE THREAD

**Issue by thg2k** [jerrykuku/luci-theme-argon#162]
Hello, can you version the CSS files uncompressed? I might send some pull requests

**EDIT:** I realized the css files are an output of the `.less` files I did not notice before. Still, it would be nice to have the css generated with some indentation and let the final LuCI makefile take care of the css compression.

What is the exact command line you are using to produce them? Can you add it as a script to the repository?

**Comment by jerrykuku** [comment]
I use  vscode to edit and produce them. I am refactoring the style sheet.But did not submit.
you can look at here:https://code.visualstudio.com/docs/languages/css
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.LESSCompiler

**Comment by thg2k** [comment]
> I use vscode to edit and produce them. I am refactoring the style sheet.But did not submit.
> you can look at here:https://code.visualstudio.com/docs/languages/css
> https://marketplace.visualstudio.com/items?itemName=MadsKristensen.LESSCompiler

Ah, I see! You should be able to change this option then? It would be much better to disable compression.

I believe the first line of the file might be parsed by vscode, so maybe just change:

    // out: ../css/cascade.css, compress: true , sourceMap: false

to:

    // out: ../css/cascade.css, compress: false, sourceMap: false

on both cascade.less and dark.less

**Comment by jerrykuku** [comment]
Changes have been submitted,Enjoy！

**Comment by volcom1600** [comment]
Can you make a custom page with AT commands in a gui like with pull down menus or check boxes with custom AT commands to change the bands on radio’s like in the mofi fork router page nested under modem for users that are on GoldenOrb openwrt? Just an idea I had with this new theme?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
