### ISSUE TITLE
请Jerry大大修改一下，这个一直存在的BUG

### ISSUE THREAD

**Issue by lllrrr** [jerrykuku/luci-theme-argon#17]
这个地方的第一列无法显示
![image](https://user-images.githubusercontent.com/31834680/73607779-8510db80-45f5-11ea-8a88-92727d94374c.png)

**Comment by lllrrr** [comment]
网络-负载均衡

**Comment by lllrrr** [comment]
正常应该是这样的
![image](https://user-images.githubusercontent.com/31834680/73618465-f3d84e00-4662-11ea-8add-f4edfa9f593b.png)

**Comment by jerrykuku** [comment]
18.06 ？

**Comment by lllrrr** [comment]
是18.06，这个BUG一直都有，可能是很多人不用负载均衡，没有发现。

**Comment by lllrrr** [comment]
rosy和官方的主题都没有这个问题

**Comment by jerrykuku** [comment]
我抽空看下

**Comment by lllrrr** [comment]
感谢
