### ISSUE TITLE
Unable to use Argon Config Beta

### ISSUE THREAD

**Issue by AcidSlide** [jerrykuku/luci-theme-argon#170]
Hello.. i'm getting errors trying Argon Config on a Chrome browser (using argon config beta from [here](https://github.com/jerrykuku/luci-app-argon-config/releases/download/v0.8-beta/luci-app-argon-config_0.8-beta_all.ipk))

![image](https://user-images.githubusercontent.com/6833047/105922037-c1461300-6074-11eb-9ed9-eba5607bba68.png)

**Comment by jerrykuku** [comment]
opkg update
opkg install luci-lib-ipkg

**Comment by AcidSlide** [comment]
> opkg update
> opkg install luci-lib-ipkg

Thanks for this.. I hope you add it to your `README.md`
