### ISSUE TITLE
firefox和ie 无法显示亚克力效果且无法播放mp4格式

### ISSUE THREAD

**Issue by huanx9** [jerrykuku/luci-theme-argon#173]
RT

**Comment by jerrykuku** [comment]
强烈建议使用Chrome 浏览器。主题中使用了一些新的css3特性，目前只有Chrome有最佳的兼容性。 主线版本 IE 系列目前还有Bug有待解决。 FireFox 默认不开启backdrop-filter，开启方法见这里：https://developer.mozilla.org/zh-CN/docs/Web/CSS/backdrop-filter

**Comment by huanx9** [comment]
裂开
