### ISSUE TITLE
cbi-dynlist编辑框当值为空时，显示高度不正确（OpenWRT 19.*）

### ISSUE THREAD

**Issue by xiaozhuai** [jerrykuku/luci-theme-argon#174]
如图：
第一列的值为空，此时显示高度不正确，发现是span的高度问题。
复现：
随便找一个带这种数组编辑框的页面，将span内的文本清空即可复现。

![image](https://user-images.githubusercontent.com/4773701/106721060-21255680-663f-11eb-864b-5b40c869c115.png)

![image](https://user-images.githubusercontent.com/4773701/106720795-d86d9d80-663e-11eb-9f17-a2c0fa5f8e12.png)

**Comment by jerrykuku** [comment]
收到

**Comment by xiaozhuai** [comment]
@jerrykuku 这个问题有进展么？
