### ISSUE TITLE
登陆页面没有变成文中的样式

### ISSUE THREAD

**Issue by sunsetz** [jerrykuku/luci-theme-argon#176]
您好，我按照文件目录替换了lean目录的文件，但是里面样式都是改变的，就是登陆界面变成这种。
![2021-02-13](https://user-images.githubusercontent.com/56462790/107854138-ebf5e100-6e54-11eb-8774-0bb0c869a08b.png)

请问该怎么解决！期待您的回复。非常感谢！

**Comment by jerrykuku** [comment]
路由器本身网络可能有问题，这个问题 我要抽时间修复一下。

**Comment by sunsetz** [comment]
感谢您的回复！

**Comment by jerrykuku** [comment]
重看了你的问题，替换文件是不行的，你要重新安装ipk才可以。
