### ISSUE TITLE
How to Change background

### ISSUE THREAD

**Issue by rebahanelite** [jerrykuku/luci-theme-argon#177]
Hello,
I have a question, how do I change the background without going to / usr / lib / lua / luci / view / themes / argon
I see that this repository has a background folder, but after I installed it I didn't know where the background folder was, I also checked the System menu, there was no Argon Config menu.
I am using the latest version
Please help, thank you

**Comment by jerrykuku** [comment]
Which version did you install? Argon Config is a standalone luci app,if you want install it,you can download it from here https://github.com/jerrykuku/luci-app-argon-config/releases/download/v0.8-beta/luci-app-argon-config_0.8-beta_all.ipk

**Comment by rebahanelite** [comment]
Solved, Thank you very much
I really like your theme 😃

**Comment by jerrykuku** [comment]
Thanks
