### ISSUE TITLE
Luci Config進不去

### ISSUE THREAD

**Issue by nk950357** [jerrykuku/luci-theme-argon#178]
![image](https://user-images.githubusercontent.com/51433626/107984673-64020980-7003-11eb-9bff-448b09d712bd.png)
我的分享器是Archer C50 安裝最新的19.07跟最新版的主題 config也是從介紹頁面下載的
在麻煩您了 謝謝

**Comment by mario512** [comment]
I have the same problem

**Comment by W5x** [comment]
Install luci-lib-ipkg package

**Comment by nk950357** [comment]
> Install luci-lib-ipkg package

Confirm it works. Thanks!
![image](https://user-images.githubusercontent.com/51433626/108251680-ad349380-7192-11eb-9c60-994b9bb1e8b0.png)

**Comment by mario512** [comment]
On openwrt 19.7.6, installing the package helped. But in version 19.7.7 this method throws the same error
![pakage](https://user-images.githubusercontent.com/8013914/108340028-cfed9900-71e0-11eb-928a-65788e065d00.jpg)
Result:
![error](https://user-images.githubusercontent.com/8013914/108340126-e85db380-71e0-11eb-9a1e-30a329344959.jpg)

**Comment by W5x** [comment]
> 
> 
> On openwrt 19.7.6, installing the package helped. But in version 19.7.7 this method throws the same error
> ![pakage](https://user-images.githubusercontent.com/8013914/108340028-cfed9900-71e0-11eb-928a-65788e065d00.jpg)
> Result:
> ![error](https://user-images.githubusercontent.com/8013914/108340126-e85db380-71e0-11eb-9a1e-30a329344959.jpg)

i'm already on 19.07.7 and it works fine with it , try uninstall the theme config package and reinstall it again and reboot the router and check the result

**Comment by jerrykuku** [comment]
> On openwrt 19.7.6, installing the package helped. But in version 19.7.7 this method throws the same error
> ![pakage](https://user-images.githubusercontent.com/8013914/108340028-cfed9900-71e0-11eb-928a-65788e065d00.jpg)
> Result:
> ![error](https://user-images.githubusercontent.com/8013914/108340126-e85db380-71e0-11eb-9a1e-30a329344959.jpg)

try  opkg install luci-compat

**Comment by mario512** [comment]
Thank you so much. You are hero!
