### ISSUE TITLE
新主题卡死

### ISSUE THREAD

**Issue by hdydy** [jerrykuku/luci-theme-argon#18]
今天编译了一下新主题，结果在登陆界面卡住了，如下图。我把主题和OpenWRT合一起编译了之后，默认主题可以正常使用，各项服务均正常，然后我切换到了这个主题发现打不开登陆界面了。。。（以前均这样操作，没有问题）
现在想问一下如何通过命令行修改主题，让我换个正常的主题先登陆一下。

附图：[图](https://imgchr.com/i/1aQRHg)

**Comment by jerrykuku** [comment]
我今天修复了这个问题 你是今天的代码么？ 登录sftp 更新下 theme 但 header.htm 试试

**Comment by hdydy** [comment]
我用git pull直接拉的今天的最新代码（包括今天提交的那份代码），文件我看了是最新的。另外openwrt能不能通过命令行修改主题？

**Comment by jerrykuku** [comment]
你的是19.07的代码？ 可以修改主题 自己去修改 config 就行了

**Comment by hdydy** [comment]
嗯是19.07，用的是这个[固件](https://github.com/coolsnowwolf/lede)。

**Comment by jerrykuku** [comment]
lean的 我并没有测试 我是按照 官方的19.07 进行适配的

**Comment by jerrykuku** [comment]
lean的openwrt版本 貌似更新了 但好像 luci版本并没有更新 所以建议使用 旧版本试试看
修改 主题的配置文件 在 /etc/config/luci     option mediaurlbase 这里

**Comment by hdydy** [comment]
我刚刚试了一下，把那条option删除了重启，主题并没有改变。还好我有配置备份，我重装下openwrt吧2333

附图：[/etc/config/luci](https://imgchr.com/i/1dFjiT)

**Comment by jerrykuku** [comment]
修改成  option mediaurlbase '/luci-static/bootstrap' 应该是可以的

**Comment by hdydy** [comment]
眼拙看成下面那个theme里面的了，原来上面也有一个。修改完成功换主题，可以登陆了，谢谢大佬。
