### ISSUE TITLE
最新2.2.6登录界面半透明失效

### ISSUE THREAD

**Issue by gxhunter1982** [jerrykuku/luci-theme-argon#181]
用的几个大佬编译的版本，发现最新2.2.6的登录界面半透明失效。

默认设置，以及更改亮色和暗色模式外，透明效果怎么改都无效。

chrome_最新版_88.0.4324
亮色模式
![argon_2 2 6](https://user-images.githubusercontent.com/78349261/108623479-4658f800-747a-11eb-9a31-65d9994db6ee.PNG)

暗色模式
![argon_2 2 6_1](https://user-images.githubusercontent.com/78349261/108623484-4c4ed900-747a-11eb-99c6-206061568cd0.PNG)

ie11（EDGE未装）
亮色模式（毛玻璃效果也有问题）
![argon_2 2 6_2](https://user-images.githubusercontent.com/78349261/108623493-54a71400-747a-11eb-9a2d-cbae9a46d49f.PNG)

暗色模式
![argon_2 2 6_3](https://user-images.githubusercontent.com/78349261/108623518-65578a00-747a-11eb-83a4-800c05bc3808.PNG)

**Comment by jerrykuku** [comment]
晚点检查下
