### ISSUE TITLE
LEAN 18.06 编译主题，如何开启暗黑模式

### ISSUE THREAD

**Issue by czxinshui** [jerrykuku/luci-theme-argon#183]
编译主题LEAN 18.06 没有可以选择的地方，如何开启暗黑模式，

**Comment by shink** [comment]
好像是跟随系统的 :p

**Comment by shink** [comment]
> 编译主题LEAN 18.06 没有可以选择的地方，如何开启暗黑模式，

好像是跟随系统的吧 :p

**Comment by czxinshui** [comment]
> > 编译主题LEAN 18.06没有可以选择的地方，如何开启暗黑模式，
> 
> 好像是跟随系统的吧：p

不是可以强制吗？

**Comment by Immity** [comment]
> 编译主题LEAN 18.06 没有可以选择的地方，如何开启暗黑模式，

https://github.com/jerrykuku/luci-theme-argon/releases/download/v1.7.0/luci-app-argon-config_0.7-beta_all.ipk

**Comment by SpeedPartner** [comment]
请额外安装主题的设置
https://github.com/jerrykuku/luci-app-argon-config/releases
