### ISSUE TITLE
How do I get "CPU Info" in Overview?

### ISSUE THREAD

**Issue by dausruddin** [jerrykuku/luci-theme-argon#185]
Hi. I installed argon and argon config using ipk files and I have no "CPU Info" in my Overview. I would like to have the temperature feature.

How do I get it?

Thanks

**Comment by jerrykuku** [comment]
you need mod your luci amdin，theme can't show that

**Comment by dausruddin** [comment]
Do you have an example? I actually have been reading docs about modifying luci. Would be awesome if you can point me straight to the point.
 It is fine if you cannot show it :)

Thanks

Anyway, closing this issue since it is out of topic.
