### ISSUE TITLE
Unable to install 2.2.5 to OpenWRT 19.0.7.6

### ISSUE THREAD

**Issue by ngb** [jerrykuku/luci-theme-argon#187]
Attempted to install Argon 2.2.5 via SSH and via LuCI.  Receive the same message about control file both ways.  Full messages when attempting to install via LuCI:  

Collected errors:
 * wfopen: https://github.com/jerrykuku/luci-theme-argon/releases/download/v2.2.5/luci-theme-argon_2.2.5-20200914_all.ipk: No such file or directory.
 * pkg_init_from_file: Failed to extract control file from https://github.com/jerrykuku/luci-theme-argon/releases/download/v2.2.5/luci-theme-argon_2.2.5-20200914_all.ipk.
 
 Please advise.

**Comment by xkuza** [comment]
Same here

**Comment by maans2001** [comment]
same here as well have you found a fix

**Comment by mikekscholz** [comment]
wget isnt naming the downloaded file properly, its saving as something like 'f2383380-f6e3-11ea-9936-81d1784fa4d5?X-Amz-Algorithm=AWS4-HMAC-SHA256'

you have to do a ls and copy whatever yours is named and then
```
mv f2383380-f6e3-11ea-9936-81d1784fa4d5?X-Amz-Algorithm=AWS4-HMAC-SHA256 luci-theme-argon.ipk
```

to rename the file
