### ISSUE TITLE
登录界面白屏

### ISSUE THREAD

**Issue by Xunflash** [jerrykuku/luci-theme-argon#188]
使用这个固件安装主题1.7.1 或者1.7.0后（其他版本未测试），无法显示登录界面，登录界面白屏https://www.right.com.cn/forum/thread-4015141-1-1.html
其他界面正常

![image](https://user-images.githubusercontent.com/71567536/110279760-9c01d880-8014-11eb-99f4-7d2d5845cf06.png)
后台其他界面正常，就登录界面报错403
192.168.1.1/:1 GET http://192.168.1.1/ net::ERR_INCOMPLETE_CHUNKED_ENCODING 403 (Forbidden)

![image](https://user-images.githubusercontent.com/71567536/110279837-bc319780-8014-11eb-8b0d-72af5ef677f0.png)

**Comment by 1Misaka** [comment]
我也遇到了这个情况。切换回默认的material就没问题。

**Comment by jerrykuku** [comment]
多半是因为请求背景的api一直获取不到导致的，近期会修复 关闭默认的bing 壁纸，自己手动开启

**Comment by 1Misaka** [comment]
> 多半是因为请求背景的api一直获取不到导致的，近期会修复 关闭默认的bing 壁纸，自己手动开启

OK

**Comment by Xunflash** [comment]
> 多半是因为请求背景的api一直获取不到导致的，近期会修复 关闭默认的bing 壁纸，自己手动开启

感谢，能不能再加一个自定义图源功能？
