### ISSUE TITLE
安装后无法进入web界面

### ISSUE THREAD

**Issue by onlyJinx** [jerrykuku/luci-theme-argon#19]
执行安装命令后就挂到了。。。

root@OpenWrt:/tmp# opkg install luci-theme-argon_1.3-01-20191111_all.ipk
Installing luci-theme-argon (1.3-01-20191111) to root...
Configuring luci-theme-argon.
uci: Entry not found
uci: Entry not found

uci: Entry not found

root@OpenWrt:/tmp#

这是uname
==================
root@OpenWrt:~# uname -a
Linux OpenWrt 4.19.100 #0 SMP Fri Jan 31 07:42:38 2020 mips GNU/Linux
root@OpenWrt:~#

![批注 2020-02-03 174818](https://user-images.githubusercontent.com/21324835/73677457-3f393d80-46f1-11ea-9a55-3c88a7214690.png)

**Comment by ermiao** [comment]
我也是

**Comment by jerrykuku** [comment]
请提供 openwrt的版本 和来源

**Comment by onlyJinx** [comment]
固件来自恩山论坛的以为大佬，链接如下
https://www.right.com.cn/forum/thread-1712318-1-1.html

版本的话不知道怎么看。。。。
uname是显示这个
Linux OpenWrt 4.19.100

**Comment by jerrykuku** [comment]
看帖子里的截图 看上去像是官方的snapshot 大版本貌似是19x了 试试我的2.0版本 如果不行的话 那就是完全的不兼容了。

**Comment by onlyJinx** [comment]
OK，那我等下在刷回openwrt，有问题再继续反馈

**Comment by onlyJinx** [comment]
还是一样装完直接暴毙，opkg完后刷新页面直接没了，我还没来得及换主题就没了。。。下面有一张是我在安装之前的截图

![批注 2020-02-04 234206](https://user-images.githubusercontent.com/21324835/73760361-2cce0b00-47a8-11ea-8fb6-6544a5030eef.png)
![批注 2020-02-04 234221](https://user-images.githubusercontent.com/21324835/73760362-2d66a180-47a8-11ea-86cf-e455c32a4e8a.png)
![批注 2020-02-04 233723](https://user-images.githubusercontent.com/21324835/73760471-52f3ab00-47a8-11ea-9326-3156f45d8dcc.png)

**Comment by Mrjia1011** [comment]
大佬，4.19内核的lean源码的固件，2.01和2.1都进不去web，又装回1.4了。。。。1.4可以。
