### ISSUE TITLE
Modify blur and trasparency manually

### ISSUE THREAD

**Issue by robiulawalemon** [jerrykuku/luci-theme-argon#191]
I'm having some problem using the configaration app. I think dependency problem. So how can I modify blur and transparency manually?

![IMG_20210309_144513](https://user-images.githubusercontent.com/65068418/110488986-321f2700-8119-11eb-8eb5-d87a289401fa.jpg)

**Comment by jerrykuku** [comment]
Try this:  opkg install  luci-lib-ipkg

**Comment by robiulawalemon** [comment]
> Try this:  opkg install  luci-lib-ipkg

Sir I've tried this already. But getting an error.

"Unknown package 'luci-lib-ipkg'.
Collected errors:
 * opkg_install_cmd: Cannot install package luci-lib-ipkg."

I think this package is not present in my version's repository.

**Comment by jerrykuku** [comment]
run: opkg update  
first

**Comment by robiulawalemon** [comment]
> run: opkg update  
> first

Ok sir luci-lib-ipkg installed after doing opkg update. Anything I have to do to use the configuration app?

**Comment by jerrykuku** [comment]
visit admin/system/argon-config

**Comment by robiulawalemon** [comment]
> visit admin/system/argon-config
> edit the options and save

Sorry Sir, I didn't get that. Visit that on gui or command line?

**Comment by jerrykuku** [comment]
Frosted Glass Radius  Larger value will more blurred ; ( Suggest:  clear: 1 or blur preset: 10 )

**Comment by robiulawalemon** [comment]
> Frosted Glass Radius  Larger value will more blurred ; ( Suggest:  clear: 1 or blur preset: 10 )

Sir can I decrease the whiteness level?

![IMG_20210309_213305.jpg](https://user-images.githubusercontent.com/65068418/110496033-4e25c700-811f-11eb-930c-0fabe698b93b.jpg)

**Comment by robiulawalemon** [comment]
> Frosted Glass Radius  Larger value will more blurred ; ( Suggest:  clear: 1 or blur preset: 10 )

Thanks a lot sir. The problem is solved.
