### ISSUE TITLE
lean源码加入此主题后经常性的出现无法进入后台的情况

### ISSUE THREAD

**Issue by bleach1991** [jerrykuku/luci-theme-argon#193]
我在lean源码https://github.com/coolsnowwolf/lede
加入此主题后经常性的出现无法进入后台的情况，
用的是1.7.2的版本
换个主题后就没出现此问题了

**Comment by jerrykuku** [comment]
是不是经常白屏？

**Comment by Noo13-man** [comment]
一个类似的问题。
安装`luci-app-argon-config_0.9-20210309_all.ipk `后，无法进入后台。
卸载后，可以正常进入后台。

**Comment by sszling** [comment]
最近编译5.4.101版，加入这个主题也是使用一段时间后就无法进入web页面，修改luci配置文件改成默认的主题就可以，不知道哪的问题。。。。

**Comment by sszling** [comment]
> 是不是经常白屏？

使用一段时间（几十分钟到几小时）后白屏，然后就算重启路由访问也还是白屏。只能进ssh修改为默认主题才暂时解决管理问题

**Comment by jerrykuku** [comment]
最新的代码么？ 最新的代码默认已经关闭了 bing api

**Comment by sszling** [comment]
> 最新的代码么？ 最新的代码默认已经关闭了 bing api

是最新的代码，应该不是bing api的问题，我用config查看默认是用本地背景的，后来我调成暗黑模式暂时没有重现这个问题。

**Comment by super27035** [comment]
我这边也出现这个用1.7.2版本的最新主题而登录不了路由器的问题，只能断电重启才能解决。
已经编译几个固件也是如此，所以在作者github这边看看也没有相同问题的朋友们。
