### ISSUE TITLE
登录界面会出现滚动条，可以滚动页面

### ISSUE THREAD

**Issue by touchsola** [jerrykuku/luci-theme-argon#195]
登录页面看上去应该是全屏显示，没有滚动条的，但现在可以小幅滚动，感觉不和谐
![图片](https://user-images.githubusercontent.com/72115940/111071606-eb16a480-8511-11eb-9643-1a95dfaa349b.png)

**Comment by jerrykuku** [comment]
麻烦报告下浏览器的类型和版本

**Comment by touchsola** [comment]
> 
> 
> 麻烦报告下浏览器的类型和版本

名称: Firefox
版本: 86.0.1
更新通道: release
操作系统: Windows_NT 10.0 19042

请知悉

**Comment by touchsola** [comment]
目前2.2.7也有这个问题，
并且从2.2.5开始，Firefox浏览器的透明及模糊效果不起作用，about:config中已开启相应功能，同一个浏览器浏览2.2.5版正常，请知悉

名称: Firefox
版本: 86.0.1
更新通道: release
操作系统: Windows_NT 10.0 19042

**Comment by mochaaP** [comment]
![Animation](https://user-images.githubusercontent.com/21154023/124376242-9c676300-dcd8-11eb-8a03-d35b4487531d.gif)

Firefox `89.0.2` 中开启 `backdrop-filter` flag 后透明效果正常。

Overflow 为 `.cbi-tooltip` 导致的。
