### ISSUE TITLE
2.2.7移动端无法呼出侧边栏

### ISSUE THREAD

**Issue by jh0072110** [jerrykuku/luci-theme-argon#199]
RT，用iOS和安卓都试了

**Comment by lovedreamland** [comment]
菜单选中状态也有问题。
/usr/lib/lua/luci/view/themes/argon/footer.htm
/usr/lib/lua/luci/view/themes/argon/header.htm
我暂时把这两个文件还原成2.2.6的版本，可以正常使用。
看了下代码应该是L.require('menu')这个动态加载有问题，等待作者修复。

**Comment by jh0072110** [comment]
BTW 2.X版本的这些问题有木有方法处理一下啊，其实也没什么影响就是看着挺…难过的+。+
![image](https://user-images.githubusercontent.com/50496854/111868294-1be45700-89b4-11eb-91c7-42f64f4a8155.png)

**Comment by jh0072110** [comment]
啊…这……还没有修复……

**Comment by lovedreamland** [comment]
> 啊…这……还没有修复……

自己改下得了，干嘛非要等修复？

**Comment by jerrykuku** [comment]
近期忙于工作，下周尽量一起修复

**Comment by jerrykuku** [comment]
> BTW 2.X版本的这些问题有木有方法处理一下啊，其实也没什么影响就是看着挺…难过的+。+
> ![image](https://user-images.githubusercontent.com/50496854/111868294-1be45700-89b4-11eb-91c7-42f64f4a8155.png)

此问题不在于主题，而是插件自己强制定义了div的背景颜色。不受主题约束
