### ISSUE TITLE
是不是把jpg换成webp或者svg

### ISSUE THREAD

**Issue by daiaji** [jerrykuku/luci-theme-argon#20]
背景整成低模风然后弄成小尺寸svg……
矢量图放大也没所谓
体积应该能小很多……

**Comment by jerrykuku** [comment]
背景图 其实可以自己按需求修改 或者删减。这个其实并不构成太大问题。

**Comment by daiaji** [comment]
问题是落实很麻烦……
如何压缩主题大小到几十K这样
全删了又很丑
几M的主题往8Mflash的设备上塞又完全不可能……

**Comment by jerrykuku** [comment]
因为设计之初基本放弃了小rom设备。 现在主题的大小是1.5M。你可以只保留一张,问题不大。最终大小应该能控制在800K左右的样子。如果只有一个主题 应该是可以接受的 或者自己换一张更简单的主题图片。

**Comment by zhouym233** [comment]
同意。从jpg改成webp，画质基本不变的情况下体积能小好多... 
现在16M的设备有点顶不住。

**Comment by zhouym233** [comment]
对16M的设备来说这几张图还是有点大了....压缩成webp会好一些。
