### ISSUE TITLE
2.2.7版移动端无法呼出侧边栏，左上角三明治按钮无效

### ISSUE THREAD

**Issue by wwjj999** [jerrykuku/luci-theme-argon#200]
2.2.7版移动端无法呼出侧边栏，左上角三明治按钮无效。只能横屏使用。Chromium内核、firefox内核的多数浏览器都有这样的问题，但safari浏览器正常。此外竖屏时，底部链接也不能显示。恳请作者尽快修复。否则严重影响移动端的操作。这里先谢谢作者的辛苦付出。

**Comment by michealhansun** [comment]
今天刚升级2.2.7版，ios、安卓的手机浏览器都无法呼出菜单栏，PC端的浏览器正常；另外我使用 “safari浏览器”也是无法呼出的。

**Comment by michealhansun** [comment]
降回2.2.6版本正常使用ing

**Comment by wwjj999** [comment]
感谢老竭力！！！！！



在 2021-03-31 16:59:03，"老竭力" ***@***.***> 写道：

近期忙于工作，下周尽量一起修复

**Comment by uamrws** [comment]
修改argon的文件footer.htm文件，增加<script src="<%=media%>/js/script.js?v=2.2.7">

**Comment by uamrws** [comment]
@ wwjj999
