### ISSUE TITLE
安装config插件后无法使用壁纸

### ISSUE THREAD

**Issue by BakaReimu** [jerrykuku/luci-theme-argon#201]
固件版本：Compiled by Lusty on Oct.19,2020 @ OpenWrt R20.9.15 / LuCI Master (git-20.256.12360-1a54222)
插件版本1.7.2
config版本 0.9

**Comment by jerrykuku** [comment]
近期忙于工作，下周尽量一起修复

**Comment by BakaReimu** [comment]
麻烦大佬了

**Comment by moesnow** [comment]
+1 删除后能正常用自定义壁纸 否则一直是bing壁纸

**Comment by qin9125** [comment]
> 近期忙于工作，下周尽量一起修复

麻烦问一下
<img width="523" alt="image" src="https://user-images.githubusercontent.com/32502941/163527423-4e6cbd74-599b-4bcb-aa50-4d3c1312502d.png">
这是我软路由固件信息 装的主题和配置是argon-18.06_1.7.2-20210309 argon-config_0.9-20210309 无论用 config 怎么设置 bing 和内置壁纸都只显示 bing 壁纸无法使用内置壁纸，我应该怎么办？谢谢
