### ISSUE TITLE
暗黑模式下磁盘管理界面，分区表文字显示与背景太接近

### ISSUE THREAD

**Issue by xylz0928** [jerrykuku/luci-theme-argon#202]
**Describe the bug**
暗黑模式下磁盘管理界面，分区表文字显示与背景太接近
body里所有文字使用的是#CCCCCC颜色（灰），
在light模式下视觉效果正常，
在dark模式下，如下图：背景颜色与字体颜色分辨不清晰，难以看清。

**To Reproduce**
1. Go to '/cgi-bin/luci/admin/system/diskman'

**Expected behavior**
针对这部分字体颜色重新更改为更黑颜色。

**Screenshots**
![iShot2021-03-30 12 53 35](https://user-images.githubusercontent.com/34766756/112935752-fe9f4d80-9156-11eb-905c-2495bd40f6e4.png)

**Openwrt (please complete the following information):**
 - Versiosn: [18.06-lean]
 - Theme [argon, dark mode]
 - Version [v1.7.2]
 - **Regarding plugin version [luci-app-diskman v0.2.10-beta]**

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [89]

**Additional context**
diskman这个颜色搞的让人很难适配，分区表图这地方，应该它自己定义锁死其内部字体颜色

**Comment by jerrykuku** [comment]
近期忙于工作，下周尽量一起修复
