### ISSUE TITLE
lede使用18.06分支源码编译后只会显示默认壁纸不显示bing

### ISSUE THREAD

**Issue by zhucaidan** [jerrykuku/luci-theme-argon#203]
使用lede最新源码，git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git
分支后，编译后连接网络也无法显示bing的当日壁纸了，只能显示默认的 bg1.jpg

**Comment by zhucaidan** [comment]
哦哦好的，我去试试

**Comment by Kaze1027** [comment]
> 需要同时编译config来设置
> https://github.com/jerrykuku/luci-app-argon-config

我编译添加了该插件，在其中设置了bing壁纸一样无法变为bing壁纸

**Comment by shink** [comment]
我也遇到了这个问题，主页是默认壁纸，argon-config 中没有 bing 壁纸选项

> 虚拟机装的 eSir 的高大全：
环境：ESXI 7
型号：Intel(R) Celeron(R) J4125 CPU @ 2.00GHz : 1 Core 2 Thread (CpuMark : 30128.422400 Scores)
固件版本：OpenWrt R21.8.6 GDQ v9.1[2021] Compiled by eSir / LuCI Master (git-21.238.35254-83494a9)
内核版本：5.4.132
系统和版本：Windows 10
浏览器类型：Google Chrome 95.0.4638.69（正式版本） （64 位）

![image](https://user-images.githubusercontent.com/49934421/142858511-35b02637-0135-4377-a096-b5f0ba77d4db.png)
