### ISSUE TITLE
lean 的 OpenWrt R20.1.24 argon2.0无限圈圈 无法进入web

### ISSUE THREAD

**Issue by DFOUD** [jerrykuku/luci-theme-argon#21]
编译后修改主题，刷新页面就无限圈圈，上一个版本没问题

**Comment by DFOUD** [comment]
不知该如何提交，1.3版本是蓝底圈圈，也就转1秒就进入了，2.0版本是白底圈圈，就卡住了

**Comment by LittleTurtle2333** [comment]
我也是，1.3没毛病

**Comment by jerrykuku** [comment]
> 不知该如何提交，1.3版本是蓝底圈圈，也就转1秒就进入了，2.0版本是白底圈圈，就卡住了

lean 新的r20 的luci 还是旧版本 并没有更新到官方的luci 19.07 所以请使用1.3
