### ISSUE TITLE
能不能适配一下openwrt v21.02呢？

### ISSUE THREAD

**Issue by learnman1994** [jerrykuku/luci-theme-argon#214]
希望作者有时间可以 适配一下 openwrtv21.02，谢谢

**Comment by uamrws** [comment]
在21.02下面编译是没有问题的
我用的就是原版的21.02rc1的代码

**Comment by juvenn** [comment]
在 21.02-rc2 上安装成功。

安装依赖：

```
opkg install luci-lib-ipkg
opkg install luci-compat
```

下载安装主题：

```
opkg install luci-theme-argon_2.2.5-20200914_all.ipk
opkg install luci-app-argon-config_0.9-20210309_all.ipk
```

重启后，自动切到了该主题。

**Comment by xzxiaoshan** [comment]
目前在 Software 中心还搜索不到 2.2.5 版本的 argon 主题，所以需要通过下面的方法进行安装（未来 Software 中心如果会有就方便了）
-----------------------------------
先在 Software 中心安装  luci-lib-ipkg 和 luci-compat，然后在进行下面的操作
-----------------------------------
我的版本： OpenWrt 21.02 stable 
-----------------------------------
1、使用SSH登录openwrt
2、wget --no-check-certificate https://github.com/jerrykuku/luci-theme-argon/releases/download/v2.2.5/luci-theme-argon_2.2.5-20200914_all.ipk
3、opkg install luci-theme-argon*.ipk
4、重启openwrt后就是新的主题了（或者到系统里面去修改一下默认主题）

注：github如果被墙，可以使用下面一个我下载好的上传到gitee中的包，这个国内的码云可以直接下载成功。
wget https://gitee.com/catoop/files/raw/master/luci-theme-argon_2.2.5-20200914_all.ipk
---------------------------
安装后，点了一遍，整体上没有什么问题
