### ISSUE TITLE
X-wrt好像不用，尝试了好几个主题，是不是X-wrt不能用openwrt的主题

### ISSUE THREAD

**Issue by wwppp** [jerrykuku/luci-theme-argon#219]
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'view'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/argon/header'.
A runtime error occurred: [string "/usr/lib/lua/luci/view/themes/argon/header...."]:23: attempt to call field 'node_childs' (a nil value)
stack traceback:
	[string "/usr/lib/lua/luci/view/themes/argon/header...."]:23: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:757: in function 'include'
	[string "/usr/lib/lua/luci/view/header.htm"]:3: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:757: in function 'include'
	[string "/usr/lib/lua/luci/view/view.htm"]:1: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function </usr/lib/lua/luci/template.lua:85>
	(tail call): ?
	/usr/lib/lua/luci/dispatcher.lua:965: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:482: in function </usr/lib/lua/luci/dispatcher.lua:481>

**Comment by hue715** [comment]
可以尝试18.06分支的argon

**Comment by wwppp** [comment]
> 可以尝试18.06分支的argon
也是一样，后来我刷了openwrp-21.02.0-rc2安装主题也是这样，是版本不支持吗

**Comment by wwppp** [comment]
> 可以尝试18.06分支的argon

18.06也是如此，后来我刷了openwrt-21.02-rc2安装主题也是这样，版本不支持吗

**Comment by hue715** [comment]
> > 可以尝试18.06分支的argon
> 
> 18.06也是如此，后来我刷了openwrt-21.02-rc2安装主题也是这样，版本不支持吗

我在openwrt官方master分支下使用，没问题。可能是缺少依赖包。
```
opkg install luci-lib-ipkg
opkg install luci-compat
```

**Comment by wwppp** [comment]
> > > 可以尝试18.06分支的argon
> > 
> > 
> > 18.06也是如此，后来我刷了openwrt-21.02-rc2安装主题也是这样，版本不支持吗
> 
> 我在openwrt官方master分支下使用，没问题。可能是缺少依赖包。
> 
> ```
> opkg install luci-lib-ipkg
> opkg install luci-compat
> ``

**Comment by wwppp** [comment]
> > > > 可以尝试18.06分支的argon
> > > 
> > > 
> > > 18.06也是这样，以后我刷了openwrt-21.02-rc2安装主题也是这样，版本不支持吗
> > 
> > 
> > 我在openwrt官方master下分支使用，没问题。可能是缺少依赖包。
> > ```
> > opkg install luci-lib-ipkg
> > opkg install luci-compat
> > ``
> > ```

**Comment by wwppp** [comment]
> > > > > 可以尝试18.06分支的argon
> > > > 
> > > > 
> > > > 18.06也是这样，以后我刷了openwrt-21.02-rc2安装主题也是这样，版本不支持吗
> > > 
> > > 
> > > 我在openwrt官方master下分支使用，没问题。可能是缺少依赖包。
> > > ```
> > > opkg install luci-lib-ipkg
> > > opkg install luci-compat
> > > ``
> > > ```

安装这两个包后依旧/usr/lib/lua/luci/template.lua:97: Failed to execute template 'sysauth'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/argon/header'.
A runtime error occurred: [string "/usr/lib/lua/luci/view/themes/argon/header...."]:23: attempt to call field 'node_childs' (a nil value)
stack traceback:
	[string "/usr/lib/lua/luci/view/themes/argon/header...."]:23: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:756: in function 'include'
	[string "/usr/lib/lua/luci/view/header.htm"]:3: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:756: in function 'include'
	[string "/usr/lib/lua/luci/view/sysauth.htm"]:1: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function </usr/lib/lua/luci/template.lua:85>
	(tail call): ?
	(tail call): ?
	/usr/lib/lua/luci/dispatcher.lua:985: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

**Comment by hue715** [comment]
> > > > > > 可以尝试18.06分支的argon
> > > > > 
> > > > > 
> > > > > 18.06也是这样，以后我刷了openwrt-21.02-rc2安装主题也是这样，版本不支持吗
> > > > 
> > > > 
> > > > 我在openwrt官方master下分支使用，没问题。可能是缺少依赖包。
> > > > ```
> > > > opkg install luci-lib-ipkg
> > > > opkg install luci-compat
> > > > ``
> > > > ```
> 
> 安装这两个包后依旧/usr/lib/lua/luci/template.lua:97: Failed to execute template 'sysauth'.
> A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
> A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/argon/header'.
> A runtime error occurred: [string "/usr/lib/lua/luci/view/themes/argon/header...."]:23: attempt to call field 'node_childs' (a nil value)
> stack traceback:
> [string "/usr/lib/lua/luci/view/themes/argon/header...."]:23: in main chunk
> stack traceback:
> [C]: in function 'error'
> /usr/lib/lua/luci/template.lua:97: in function 'render'
> /usr/lib/lua/luci/dispatcher.lua:756: in function 'include'
> [string "/usr/lib/lua/luci/view/header.htm"]:3: in main chunk
> stack traceback:
> [C]: in function 'error'
> /usr/lib/lua/luci/template.lua:97: in function 'render'
> /usr/lib/lua/luci/dispatcher.lua:756: in function 'include'
> [string "/usr/lib/lua/luci/view/sysauth.htm"]:1: in main chunk
> stack traceback:
> [C]: in function 'error'
> /usr/lib/lua/luci/template.lua:97: in function </usr/lib/lua/luci/template.lua:85>
> (tail call): ?
> (tail call): ?
> /usr/lib/lua/luci/dispatcher.lua:985: in function 'dispatch'
> /usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

用这里的主题，可以正常显示吗？
![image](https://user-images.githubusercontent.com/22958922/121862075-0ec5d280-cd2d-11eb-993f-f37d9c21c207.png)

**Comment by wwppp** [comment]
> > > > > > > 可以尝试18.06分支的argon
> > > > > > 
> > > > > > 
> > > > > > 18.06也是这样，以后我刷了openwrt-21.02-rc2安装主题也是这样，版本不支持吗
> > > > > 
> > > > > 
> > > > > 我在openwrt官方master下分支使用，没问题。可能是缺少依赖包。
> > > > > ```
> > > > > opkg install luci-lib-ipkg
> > > > > opkg install luci-compat
> > > > > ``
> > > > > ```
> > 
> > 
> > 安装这两个包后依旧/usr/lib/lua/luci/template.lua:97: Failed to execute template 'sysauth'.
> > A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
> > A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/argon/header'.
> > A runtime error occurred: [string "/usr/lib/lua/luci/view/themes/argon/header...."]:23: attempt to call field 'node_childs' (a nil value)
> > stack traceback:
> > [string "/usr/lib/lua/luci/view/themes/argon/header...."]:23: in main chunk
> > stack traceback:
> > [C]: in function 'error'
> > /usr/lib/lua/luci/template.lua:97: in function 'render'
> > /usr/lib/lua/luci/dispatcher.lua:756: in function 'include'
> > [string "/usr/lib/lua/luci/view/header.htm"]:3: in main chunk
> > stack traceback:
> > [C]: in function 'error'
> > /usr/lib/lua/luci/template.lua:97: in function 'render'
> > /usr/lib/lua/luci/dispatcher.lua:756: in function 'include'
> > [string "/usr/lib/lua/luci/view/sysauth.htm"]:1: in main chunk
> > stack traceback:
> > [C]: in function 'error'
> > /usr/lib/lua/luci/template.lua:97: in function </usr/lib/lua/luci/template.lua:85>
> > (tail call): ?
> > (tail call): ?
> > /usr/lib/lua/luci/dispatcher.lua:985: in function 'dispatch'
> > /usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>
> 
> 用这里的主题，可以正常显示吗？
> ![image](https://user-images.githubusercontent.com/22958922/121862075-0ec5d280-cd2d-11eb-993f-f37d9c21c207.png)

这个主题正常显示
![2021-06-14 16-34-42 的屏幕截图](https://user-images.githubusercontent.com/38174375/121863626-a0820f80-cd2e-11eb-9223-8b1816438d9e.png)

**Comment by hue715** [comment]
> > > > > > > > 可以尝试18.06分支的argon
> > > > > > > 
> > > > > > > 
> > > > > > > 18.06也是这样，以后我刷了openwrt-21.02-rc2安装主题也是这样，版本不支持吗
> > > > > > 
> > > > > > 
> > > > > > 我在openwrt官方master下分支使用，没问题。可能是缺少依赖包。
> > > > > > ```
> > > > > > opkg install luci-lib-ipkg
> > > > > > opkg install luci-compat
> > > > > > ``
> > > > > > ```
> > > 
> > > 
> > > 安装这两个包后依旧/usr/lib/lua/luci/template.lua:97: Failed to execute template 'sysauth'.
> > > A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
> > > A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/argon/header'.
> > > A runtime error occurred: [string "/usr/lib/lua/luci/view/themes/argon/header...."]:23: attempt to call field 'node_childs' (a nil value)
> > > stack traceback:
> > > [string "/usr/lib/lua/luci/view/themes/argon/header...."]:23: in main chunk
> > > stack traceback:
> > > [C]: in function 'error'
> > > /usr/lib/lua/luci/template.lua:97: in function 'render'
> > > /usr/lib/lua/luci/dispatcher.lua:756: in function 'include'
> > > [string "/usr/lib/lua/luci/view/header.htm"]:3: in main chunk
> > > stack traceback:
> > > [C]: in function 'error'
> > > /usr/lib/lua/luci/template.lua:97: in function 'render'
> > > /usr/lib/lua/luci/dispatcher.lua:756: in function 'include'
> > > [string "/usr/lib/lua/luci/view/sysauth.htm"]:1: in main chunk
> > > stack traceback:
> > > [C]: in function 'error'
> > > /usr/lib/lua/luci/template.lua:97: in function </usr/lib/lua/luci/template.lua:85>
> > > (tail call): ?
> > > (tail call): ?
> > > /usr/lib/lua/luci/dispatcher.lua:985: in function 'dispatch'
> > > /usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>
> > 
> > 
> > 用这里的主题，可以正常显示吗？
> > ![image](https://user-images.githubusercontent.com/22958922/121862075-0ec5d280-cd2d-11eb-993f-f37d9c21c207.png)
> 
> 这里的主题正常显示
> ![2021-06-14 16-34-42 的屏幕截图](https://user-images.githubusercontent.com/38174375/121863626-a0820f80-cd2e-11eb-9223-8b1816438d9e.png)

有试过直接安装release中的2.2.5版本吗？

**Comment by wwppp** [comment]
直接安装2.2.5可用，谢谢
