### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by lloyd18** [jerrykuku/luci-theme-argon#22]
首先感谢你做出这么好看的主题，现在提几个小问题
固件用的是大雕源码 https://github.com/coolsnowwolf/lede
因为目前不兼容大雕源码，主题版本还是用的旧版，
![1](https://user-images.githubusercontent.com/10294460/73857803-6703df00-4872-11ea-8e01-04c68f30e1e2.jpg)
1.未设置密码时，登陆按钮会挡住提示，这都是小事，不修复也无伤大雅
![2](https://user-images.githubusercontent.com/10294460/73857897-8ac72500-4872-11ea-9a89-a4c8ffcf87de.jpg)
2.不知道是这个插件的问题还是主题的问题，（支持SS/SSR/V2RAY）这个提示是不该存在的
![4](https://user-images.githubusercontent.com/10294460/73858464-661f7d00-4873-11ea-8cbf-f46509a4f3e0.jpg)
3.和你的vssr搭配使用延迟有三位数的话浏览器100%缩放会有重合现象
![3](https://user-images.githubusercontent.com/10294460/73858554-8c451d00-4873-11ea-9bf1-5961c7bf4f13.jpg)
4.能否给这个Docker这个新的分类添加一个图标，项目https://github.com/lisaac/luci-app-dockerman

**Comment by jerrykuku** [comment]
关于问题:
1.近期我会修复这个问题。
2.这个应该是和hw的语言文件冲突了。（同样的命名）
3.这个问题在特定的宽度下 会出现 我会尽量的调整 这个是hw 的问题 不是主题的。
4.这个图标我尽量添加上。

**Comment by lloyd18** [comment]
> 关于问题:
> 1.近期我会修复这个问题。
> 2.这个应该是和hw的语言文件冲突了。（同样的命名）
> 3.这个问题在特定的宽度下 会出现 我会尽量的调整 这个是hw 的问题 不是主题的。
> 4.这个图标我尽量添加上。

谢谢
