### ISSUE TITLE
增加对webp的支持

### ISSUE THREAD

**Issue by ihuanx** [jerrykuku/luci-theme-argon#220]
RT 谢谢开发者

**Comment by jerrykuku** [comment]
webp 应该是要看浏览器是否支持吧

**Comment by ihuanx** [comment]
浏览器支持阿  但是把图片丢到目录下  主题无法识别。

**Comment by fernvenue** [comment]
I have no idea why this issue closed, all modern browsers support webp natively, and only god knows why this theme choose to use jpg/png...
