### ISSUE TITLE
最新源码编译完成后，登陆界面白屏

### ISSUE THREAD

**Issue by mzl0408** [jerrykuku/luci-theme-argon#226]
最新源码，编译完成进入192.168.2.1，登陆界面就是白屏，但是用自己收藏的书签http://192.168.2.1/cgi-bin/luci/admin/status/overview，登陆界面又正常了，已经试过主题设置，无论关闭bing壁纸还是开着的，都是一样的

**Comment by SpeedPartner** [comment]
反馈请提供较为详细的信息,如luci版本和主题版本.
如还存在相同问题,请重提issue.
