### ISSUE TITLE
Login page failed to load

### ISSUE THREAD

**Issue by ulic75** [jerrykuku/luci-theme-argon#228]
I think I narrowed this issue down to the Bing image.  It looks like the system had a bunch hung processes trying to get a bing wallpaper.  I think the url was https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US

When I went that that url in a browser I received this response:

```
{"images":[{"startdate":"20210621","fullstartdate":"202106210700","enddate":"20210622","url":"/th?id=OHR.RothschildGiraffe_EN-US4621962761_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp","urlbase":"/th?id=OHR.RothschildGiraffe_EN-US4621962761","copyright":"Rothschild's giraffe in Lake Nakuru National Park, Kenya (© Theo Allofs/Minden Pictures)","copyrightlink":"https://www.bing.com/search?q=World+Giraffe+Day&form=hpcapt&filters=HpDate%3a%2220210621_0700%22","title":"Stretching into a new season","quiz":"/search?q=Bing+homepage+quiz&filters=WQOskey:%22HPQuiz_20210621_RothschildGiraffe%22&FORM=HPQUIZ","wp":true,"hsh":"f61d5886a32298c740a020d81535ec1a","drk":1,"top":1,"bot":1,"hs":[]}],"tooltips":{"loading":"Loading...","previous":"Previous image","next":"Next image","walle":"This image is not available to download as wallpaper.","walls":"Download this image. Use of this image is restricted to wallpaper only."}}
```

**Openwrt (please complete the following information):**
 - Versiosn: 19.07
 - Theme aragon
 - Version 2.2.5

**Comment by jerrykuku** [comment]
Just only one process to get bing api .And I have already set a 0.5 second timeout for that

**Comment by ulic75** [comment]
After this had noticed some other network weirdness.  I think it was ipv6 related.  If the issue returns I'll try to get more concrete information for you.
