### ISSUE TITLE
v2.2.7主题在LEDE显示有问题 

### ISSUE THREAD

**Issue by dengchan0416** [jerrykuku/luci-theme-argon#229]
![QQ截图20210622151400](https://user-images.githubusercontent.com/41529838/122880385-8965a200-d36c-11eb-9634-472721766487.png)

**Comment by r1172464137** [comment]
确实

**Comment by annce** [comment]
解决办法，先在软件包里移除主题，然后重新上传安装，即可，但是登入时不会显示实时图片，不炫酷了

**Comment by hue715** [comment]
Chrome浏览器有什么报错吗？

**Comment by SpeedPartner** [comment]
LEDE请使用本主题18.06分支.
