### ISSUE TITLE
lede版本主题无法显示菜单，不能上网

### ISSUE THREAD

**Issue by xiangfeigao** [jerrykuku/luci-theme-argon#231]
Q：lede源码编译，切换主体后不能上网，不能显示树形菜单。
硬件：hc5962

**Comment by dengchan0416** [comment]
我也是这样

**Comment by annce** [comment]
我也是，可能是不兼容，版本lede 5.10.46

**Comment by annce** [comment]
解决办法，先在软件包里移除主题，然后重新上传安装，即可，但是登入时不会显示实时图片

**Comment by annce** [comment]
找到原因了，默认安装的是Openwrt 官方源码的V2.2.5版本，所以不兼容
