### ISSUE TITLE
lede 5.10.46出现菜单无法显示

### ISSUE THREAD

**Issue by annce** [jerrykuku/luci-theme-argon#234]
lede 5.10.46出现菜单无法显示

**Comment by annce** [comment]
解决办法，先在软件包里移除主题，然后重新上传安装，即可，但是登入时不会显示实时图片

**Comment by Moebyte** [comment]
我是登录界面没有图片了，菜单还在，内核版本5.10.46

**Comment by arbaleast** [comment]
![Screenshot_2021-07-05_12-42-59](https://user-images.githubusercontent.com/57560360/124418791-d6933c00-dd8e-11eb-98d5-4ff24bfd3c08.png)
cpu也没显示，

**Comment by CDLLY** [comment]
+1，更新5.10之后吓了一跳...

**Comment by arbaleast** [comment]
> +1，更新5.10之后吓了一跳...

更换18.06分支后，没问题了

**Comment by CDLLY** [comment]
> > +1，更新5.10之后吓了一跳...
> 
> 更换18.06分支后，没问题了

wc,分支拉错了合着，怪不得安了新版本才出问题😂
