### ISSUE TITLE
求助，安装完后登录界面怎么是这样

### ISSUE THREAD

**Issue by zorrose82** [jerrykuku/luci-theme-argon#235]
![捕获](https://user-images.githubusercontent.com/71229443/123735799-71dd6a80-d8d2-11eb-98ef-1bf6a2643dfb.JPG)

没有好看的登录画面

没有集成在lede中编译
是后面再安装的

wget --no-check-certificate https://github.com/jerrykuku/luci-theme-argon/releases/download/v1.7.2/luci-theme-argon-18.06_1.7.2-20210309_all.ipk
opkg install luci-theme-argon*.ipk

感谢各位大佬

**Comment by msdos03** [comment]
求助，你是怎么解决的啊
