### ISSUE TITLE
argon-config 的V0.9版本无法安装

### ISSUE THREAD

**Issue by annce** [jerrykuku/luci-theme-argon#236]
argon-config 的V0.9版本无法安装

**Comment by EYW-015** [comment]
去把argon-config源码加进编译里，自己编译个新的出来就行了

**Comment by wuelliott** [comment]
我也是一样的情况，路由是红米AX6，集成到系统里就可以，随着系统一起编译出来的argon-config 的V0.9版本ipk却无法安装。

**Comment by galaxyskyknight** [comment]
> 
> 
> 去把argon-config源码加进编译里，自己编译个新的出来就行了

请问config源码在哪里，这里好像没有，直接装release里编号的config工具到5.10.x的lede版本上Luci里刷不出来。

**Comment by EYW-015** [comment]
> > 去把argon-config源码加进编译里，自己编译个新的出来就行了
> 
> 请问config源码在哪里，这里好像没有，直接装release里编号的config工具到5.10.x的lede版本上Luci里刷不出来。

[luci-app-argon-config](https://github.com/jerrykuku/luci-app-argon-config)
