### ISSUE TITLE
最新lean源码编译的AX6固件，无法使用bing壁纸。

### ISSUE THREAD

**Issue by wuelliott** [jerrykuku/luci-theme-argon#239]
固件版本 | OpenWrt R21.7.1.100
内核版本 | 5.10.46
设置为bing壁纸后，还是一直显示默认的壁纸，上传自定义壁纸可以正常显示。

**Comment by abc2251259** [comment]
一样的问题...

**Comment by wuelliott** [comment]
我发现可能不是主题的问题，是lean大源码编译出的AX6固件是0MB缓存造成的。

**Comment by abc2251259** [comment]
是吗？我好像找到原因了，我打开科学上网就正常了？

**Comment by wuelliott** [comment]
我一直是开着科学上网的，照样不会更新。但其他路由上都没这问题，只有AX6会这样。

**Comment by Kaze1027** [comment]
同样的情况，有一瞬间加载出来了又变回默认了

**Comment by Kaze1027** [comment]
我发现好像不能用18.06分支，用master分支可以，一会儿到家详细试一下

**Comment by drfccv** [comment]
> 我发现好像不能用18.06分支，用master分支可以，一会儿到家详细试一下

QSDK YYDS！

**Comment by Kaze1027** [comment]
试过了，master页面背景都没有了

**Comment by Kaze1027** [comment]
我自己摸索出来了，打开梯子后bing.com被代理就无法自动更新，需要到梯子里将"bing.com"强制不走代理。
