### ISSUE TITLE
lean源码安装了1.7.2版本，无法加载主题，主题选项也没有argon

### ISSUE THREAD

**Issue by ericshunhawk** [jerrykuku/luci-theme-argon#240]
lean版本 OpenWrt R21.6.14 / LuCI Master (git-21.166.54162-5c1f01e)

安装主题版本 luci-theme-argon_1.7.2-20210309_all.ipk

![image](https://user-images.githubusercontent.com/18033606/125390103-dcaf9b00-e3d4-11eb-9daa-34b691f8d099.png)

![image](https://user-images.githubusercontent.com/18033606/125390173-fa7d0000-e3d4-11eb-9497-3bfe44cafba2.png)

**Comment by Kaze1027** [comment]
这个不存在把，你仔细看看说明，我的都没问题

**Comment by 110010110** [comment]
Try to reboot.

**Comment by Paris0-0** [comment]
我昨天编译了最新的也是这样，设备newifi d2

**Comment by 281677160** [comment]
我一直用这个主题，没发现这个问题啊，LEDE源码用18.06分支的，还有就是LEDE源码自带一个同样名称的主题，我都是先删除LEDE源码自带同样名称的主题再拉取这个主题使用

**Comment by Paris0-0** [comment]
我之前也没问题都正常的，就最近升级到5.10内核就不行了

**Comment by 453974158** [comment]
刚安装完重启前也是这样，重启后就已经自动启用argon主题了。

**Comment by puzzle9** [comment]
重启后出来了
