### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by 281677160** [jerrykuku/luci-theme-argon#241]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Openwrt (please complete the following information):**
 - Versiosn: [e.g. 18.06-lean]
 - Theme [e.g. argon]
 - Version [e.g. 2.27]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

希望在显示主机名称的那里可以显示出 - 横杠，现在不显示，主机名称带横杠就显示空白的
还有就是在21.02上使用该主题，在点击菜单的时候没有一个过渡往下拉伸的效果了，一点菜单立马显示子菜单，很不习惯啊
希望作者可以修复修复，呵呵
这个主题其实还真是挺好用的，在20年前的单核电脑安装WIN7系统上进openwrt后台，用其他主题卡的飞起，很难受，用这个主题流畅的很，作者的功力还是很不错的，感谢作者的好作品！

![QQ截图20210718131515](https://user-images.githubusercontent.com/66651997/126056703-c50a8ddb-f4cf-492c-bdb3-17ddecc5675b.png)

**Comment by VergilGao** [comment]
> 还有就是在21.02上使用该主题，在点击菜单的时候没有一个过渡往下拉伸的效果了，一点菜单立马显示子菜单，很不习惯啊

刚用21.02编译了一份，有拉伸效果。

**Comment by 281677160** [comment]
哦，你拉取的是什么分支，我拉取的是master分支的，完全没拉伸的效果了，一点菜单立马就显示子菜单，速度太快了，很不习惯，没有18.06那种点菜单后有点缓慢拉伸的效果




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jerrykuku/luci-theme-argon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 下午3:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jerrykuku/luci-theme-argon] 两个小建议 (#241)





  
还有就是在21.02上使用该主题，在点击菜单的时候没有一个过渡往下拉伸的效果了，一点菜单立马显示子菜单，很不习惯啊
  
刚用21.02编译了一份，有拉伸效果。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by VergilGao** [comment]
openwrt-21.02

**Comment by 281677160** [comment]
感谢大佬，非常感谢！那个甜糖收星愿的弄好了吗？不能登录，我还是拉的你以前的源码用呢，最新的不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jerrykuku/luci-theme-argon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月16日(星期六) 晚上7:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jerrykuku/luci-theme-argon] 两个小建议 (#241)





 
菜单滑动效果已经添加
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SpeedPartner** [comment]
至于那个"-"的符号,我觉得没有更好
