### ISSUE TITLE
这里的白背景好奇怪

### ISSUE THREAD

**Issue by ysslang** [jerrykuku/luci-theme-argon#244]
![Uploading image.png…]()
扒了下css， 似乎是这里导致的
https://github.com/jerrykuku/luci-theme-argon/blob/8fda1c2498c17cf1839ca3115fd3df9b47ef59db/htdocs/luci-static/argon/css/cascade.css#L1608

**Comment by smallprogram** [comment]
这个是背景颜色css样式而已，白背景是因为没加载到图片或视频导致的只显示背景颜色。
