### ISSUE TITLE
OpenWrt 21.02 can‘t use luci-theme-argon

### ISSUE THREAD

**Issue by DapengWei** [jerrykuku/luci-theme-argon#252]
**Describe the bug**
After manual install luci-theme-argon_2.2.5-20200914_all.ipk
Don’t see argon in system -> Language and Style

**To Reproduce**
1. wget https://github.com/jerrykuku/luci-theme-argon/releases/download/v2.2.5/luci-theme-argon_2.2.5-20200914_all.ipk
2. opkg install luci-theme-argon_2.2.5-20200914_all.ipk
Installing luci-theme-argon (2.2.5-20200914) to root...
Configuring luci-theme-argon.

**Screenshots**
<img width="772" alt="Screen Shot 2021-10-11 at 12 58 15" src="https://user-images.githubusercontent.com/7387971/136735610-229bb732-0016-445a-b3d0-16f0cce10874.png">

**Openwrt (please complete the following information):**
 - Versiosn:  21.02

**Comment by 60MilesPerHour** [comment]
opkg install luci-compat
opkg install luci-lib-ipkg
wget --no-check-certificate https://github.com/jerrykuku/luci-theme-argon/releases/download/v2.2.5/luci-theme-argon_2.2.5-20200914_all.ipk
opkg install luci-theme-argon*.ipk

**Comment by alexdelprete** [comment]
> only found this out after tons of head-scratching and like a thousand resets later.

you're installing 2.2.5. Check post above yours: 2.2.9 + config app. tons of head-scratching too...that's why I made that post. :)
