### ISSUE TITLE
用Lienol的源码编译PC浏览器显示不正常

### ISSUE THREAD

**Issue by xiaotan8** [jerrykuku/luci-theme-argon#253]
用Lienol的源码编译Google Chrome及Internet Explorer 11 浏览器概况和接口页面显示不正常 ，手机端正常
![20211011212129](https://user-images.githubusercontent.com/62252056/136798797-ea3eb2b6-1d07-4e42-a60d-2e8b617dad76.jpg)
![20211011212210](https://user-images.githubusercontent.com/62252056/136798816-40500aeb-de5e-48ca-bd86-069e2f0e6d41.jpg)

。

**Comment by SpeedPartner** [comment]
建议将luci的源换成官方的18.06或者lede的18.06
