### ISSUE TITLE
Menu button does not work

### ISSUE THREAD

**Issue by J0rmo** [jerrykuku/luci-theme-argon#254]
Menu button does not work on my iPhone

**Screenshots**
![微信图片_20211015213527](https://user-images.githubusercontent.com/7736858/137497280-8d7bed33-32c9-4c91-bbbc-f510d49ff83a.jpg)

**Openwrt**
 - Versiosn: 21.0.2
 - Theme argon
 - Version 2.2.8

**Smartphone**
 - Device:  iPhone12 mini
 - OS: iOS 14.8
 - Browser Safari

**Comment by jerrykuku** [comment]
ok ，I will test ,Thanks for  feedback

**Comment by jerrykuku** [comment]
New version 2.2.9 has fixed this problem.welcome to try.
