### ISSUE TITLE
luci-app-argon-config 无法运行

### ISSUE THREAD

**Issue by charley008** [jerrykuku/luci-theme-argon#257]
...ib/lua/luci/model/cbi/argon-config/configuration.lua:3: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	...ib/lua/luci/model/cbi/argon-config/configuration.lua:3: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1501: in function '_form'
	/usr/lib/lua/luci/dispatcher.lua:1029: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

**Screenshots**

**Openwrt (please complete the following information):**
 - Versiosn: [21.02.1]
 - Theme [argon]

**Comment by jerrykuku** [comment]
opkg update
opkg install luci-compat
opkg install luci-lib-ipkg 

Try this.

**Comment by charley008** [comment]
opkg install luci-lib-ipkg 装好后就没问题了。。

**Comment by ZhuSky** [comment]
![image](https://user-images.githubusercontent.com/18596232/141609584-f6a57c4d-0e46-48ce-b01d-519c465a93b6.png)
