### ISSUE TITLE
observer未定义

### ISSUE THREAD

**Issue by jjm2473** [jerrykuku/luci-theme-argon#258]
打开网络接口设置，控制台会报错，导航栏也不会激活当前节点

https://github.com/jerrykuku/luci-theme-argon/blob/cb52e4d07f07b22241ac4a32fc18420770dfb4d3/htdocs/luci-static/argon/js/script.js#L128

**Comment by SpeedPartner** [comment]
已经修复咯~

**Comment by jjm2473** [comment]
哈，我已经切换到21了
