### ISSUE TITLE
本主题的master分支只支持官方luci仓库的master分支吗?

### ISSUE THREAD

**Issue by garypang13** [jerrykuku/luci-theme-argon#26]
我测试了用master分支的代码编译出的主题无法兼容openwrt/luci仓库里的luci-19.07分支,后台一片空白,换成luci master分支后可以正常使用.还是希望以luci-19.07分支为主线,openwrt的master分支问题很多基本没法正常使用的.

**Comment by jerrykuku** [comment]
适配对象 V2.01 是基于官方19.07 stable 镜像 适配的。
V2.1 是基于 官方Snapshot 的镜像适配的 
你可以参考readme中的三个 不同的版本  分别安装下试试看，哪个能用 就check 对应的commit 。

**Comment by garypang13** [comment]
为啥不把luci19.07的两个版本弄成独立的两个branch呢,难道V2.01以后都不考虑更新了么?

**Comment by jerrykuku** [comment]
我不知道 官方stable 会不会立刻更新到snapshots的版本 现在分支没有来得及分开，抽空分开。
