### ISSUE TITLE
lean源码编译后打开页面白屏

### ISSUE THREAD

**Issue by L-vivi** [jerrykuku/luci-theme-argon#27]
lean源码编译后打开页面白屏

**Comment by martin0607** [comment]
我也是，都是最新的源码。打开空白的。

**Comment by jerrykuku** [comment]
仔细看看 readme 我有强调过 Lean源码要用哪个branch

**Comment by Mrjia1011** [comment]
> 仔细看看 readme 我有强调过 Lean源码要用哪个branch

大佬，非常喜欢这个主题，用的lean源码的openwrt，想知道怎么用，对代码不懂。谢谢大佬。

**Comment by jerrykuku** [comment]
`cd lede/package/lean  
rm -rf luci-theme-argon  
git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git`

**Comment by choyung** [comment]
@jerrykuku 大佬，lean的openwrt不小心装错了不兼容的，白屏，有办法挽回，设置回默认的那个皮肤吗？

**Comment by jerrykuku** [comment]
> @jerrykuku 大佬，lean的openwrt不小心装错了不兼容的，白屏，有办法挽回，设置回默认的那个皮肤吗？

能ssh么？能的话 进ssh  修改 vi /etc/config/luci  修改 option mediaurlbase '/luci-static/argon' 这个选项为  option mediaurlbase '/luci-static/bootstrap' 然后保存 重启

**Comment by choyung** [comment]
@jerrykuku 感谢，现在可以进入页面了，显示不能降级，尴尬
Not downgrading package luci-theme-argon on root from 2.1-20200206 to 1.4-01-20200101.

**Comment by jerrykuku** [comment]
opkg install  时候 添加 参数  --force-downgrade

**Comment by choyung** [comment]
@jerrykuku 完美了，谢谢你。

**Comment by Ailick** [comment]
借个位置，编译进lede固件，主题使用的18.06分支，但是登陆页面背景是全黑，修改`header.htm`中`bg<%=math.random(1,bgcount)%>.jpg`为`bg1.jpg`依然黑屏，不知道问题出在哪里。请指教。

**Comment by Ailick** [comment]
@jerrykuku 借个位置，编译进lede固件，主题使用的18.06分支，但是登陆页面背景是全黑，修改`header.htm`中`bg<%=math.random(1,bgcount)%>.jpg`为`bg1.jpg`依然黑屏，不知道问题出在哪里。请指教。

**Comment by Ailick** [comment]
@jerrykuku 趁没关闭，前来求救。编译进 lede固件，使用的18.06分支，可以正常登陆和使用，就是登陆页面背景是全黑，尝试修改`header.htm`中的`bg<%=math.random(1,bgcount)%>.jpg`为`bg1.jpg`依然黑屏，不知道是咋了，请大佬指教。

**Comment by onlyJinx** [comment]
挤挤,大佬,我用L大的19.07, 安装图中第一个主题会无限卡动画,安装第二个就会直接白屏,
![image](https://user-images.githubusercontent.com/21324835/76140769-9e93c000-6098-11ea-89e7-ad5e69395309.png)
![image](https://user-images.githubusercontent.com/21324835/76140772-a7849180-6098-11ea-8aba-af97cb51fca5.png)

**Comment by jerrykuku** [comment]
> 挤挤,大佬,我用L大的19.07, 安装图中第一个主题会无限卡动画,安装第二个就会直接白屏,
> ![image](https://user-images.githubusercontent.com/21324835/76140769-9e93c000-6098-11ea-89e7-ad5e69395309.png)
> ![image](https://user-images.githubusercontent.com/21324835/76140772-a7849180-6098-11ea-8aba-af97cb51fca5.png)

你截图的是第二第三个  我第一个是 For Lean openwrt！！！！

**Comment by onlyJinx** [comment]
> > 挤挤,大佬,我用L大的19.07, 安装图中第一个主题会无限卡动画,安装第二个就会直接白屏,
> > ![image](https://user-images.githubusercontent.com/21324835/76140769-9e93c000-6098-11ea-89e7-ad5e69395309.png)
> > ![image](https://user-images.githubusercontent.com/21324835/76140772-a7849180-6098-11ea-8aba-af97cb51fca5.png)
> 
> 你截图的是第二第三个 我第一个是 For Lean openwrt！！！！

用了第一个还真可以了,谢谢. 不过主题看起来整个都被放大了一样,就是屏幕内显示的元素变少了,这个可以自己调整吗?

![image](https://user-images.githubusercontent.com/21324835/76140865-a6a02f80-6099-11ea-8b4f-e6cdbd20314b.png)
