### ISSUE TITLE
Lean固件下的argon怎么设置每次登录更换背景图或者自定义图?

### ISSUE THREAD

**Issue by lindwwei** [jerrykuku/luci-theme-argon#273]
Lean固件下的argon怎么设置每次登录更换背景图或者自定义图?

1.7.2一直都是固定的一张 = =

想更换一下~

**Comment by jerrykuku** [comment]
安装  https://github.com/jerrykuku/luci-theme-argon/releases/download/v2.2.9/luci-app-argon-config_0.9-20210309_all.ipk

**Comment by King-Of-Knights** [comment]
@jerrykuku 大神，能不能在Lean固件编译里面加入这个主题的设定，每次更新固件还要多装一个ipk，有点强迫症

**Comment by zorrose82** [comment]
> @jerrykuku 大神，能不能在Lean固件编译里面加入这个主题的设定，每次更新固件还要多装一个ipk，有点强迫症

大佬的说明里有：
lede下面，覆盖lede的argon主题后编译

cd lede/package/lean  
rm -rf luci-theme-argon  
git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git  
make menuconfig #choose LUCI->Theme->Luci-theme-argon  
make -j1 V=s

**Comment by King-Of-Knights** [comment]
@zorrose82 你写的是对的，但是这样还得自己装一个luci-app-argon-config_0.9-20210309_all.ipk，我是想知道能不能直接在git环节把这个ipk一起包含了，每次编译就不用再额外装了

**Comment by zorrose82** [comment]
> 额外

cd package/lean  
rm -rf luci-theme-argon  
git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git  
**git clone  https://github.com/jerrykuku/luci-app-argon-config**

加上一行不就行了，把config也拉过去

**Comment by King-Of-Knights** [comment]
@zorrose82 大聪明！！我试试！

**Comment by zorrose82** [comment]
> @zorrose82 大聪明！！我试试！

down下来后，make  menuconfig   下的luci-app 下要选中 luci-app-argon-config

**Comment by King-Of-Knights** [comment]
@zorrose82 非常感谢 我试试！

**Comment by lucikap** [comment]
如何在源码中直接调用bing的背景？
