### ISSUE TITLE
希望支持来自Unsplash的壁纸

### ISSUE THREAD

**Issue by MkQtS** [jerrykuku/luci-theme-argon#276]
目前只支持本地文件和bing壁纸，前几天bing挂了，就只能用本地文件。

Unsplash的图片允许免费使用，比如一个浏览器插件`Tabliss`在unsplash上的[collection](https://unsplash.com/collections/1053828/tabliss-official)，也很漂亮

**Comment by OiCkilL** [comment]
+1，Unsplash的壁纸确实不错，免费而且质量高

**Comment by jerrykuku** [comment]
我也一直用unspalsh 但是貌似没有找到合适的接口

**Comment by MkQtS** [comment]
Unsplash提供了[开发者文档](https://unsplash.com/documentation)，需要注册以后获取Unsplash的Access Key，然后就可以使用Unsplash的api了

**Comment by moonerick** [comment]
> Unsplash提供了[开发者文档](https://unsplash.com/documentation)，需要注册以后获取Unsplash的Access Key，然后就可以使用Unsplash的api了

> 我也一直用unspalsh 但是貌似没有找到合适的接口

https://www.mangoxo.com/blog/OozZLnog
可以参考这个

**Comment by jerrykuku** [comment]
可以考虑，只是argon目前在做大的css重构，进行了一半，鸽子了好久。。。。
