### ISSUE TITLE
安装包有点大，建议优化一下图片资源

### ISSUE THREAD

**Issue by ZiYang1989** [jerrykuku/luci-theme-argon#28]
4个img占了900k，建议是否可以优化一下图片资源，用矢量图或者降低图片的质量，否则安装完你这个主题就没法按照其他pkg了:(

BTW主题风格还是做得很赞的

**Comment by jerrykuku** [comment]
自行删减 或者替换背景图片是可以的，背景图片是随机的，自动检测文件夹内图片的数量 要求就是从1开始，你可以精简到只保1.jpg 并且替换其内容。这样就会小很多了。

**Comment by ZiYang1989** [comment]
帮你压了下图片，大小减半，质量基本不变。方便的话可以替换一下，我这网络太慢就不提MR了。

自行删减倒是能达到目的，但如果遇到本来空间不够没法安装这个ipkg的情况话，还得重新编译这个包，不一定有编译环境，就很麻烦了

![bg1_small](https://user-images.githubusercontent.com/3201938/74732187-ad026f00-5284-11ea-9e52-39f564ec4877.jpg)
![bg2_small](https://user-images.githubusercontent.com/3201938/74732425-2c903e00-5285-11ea-9b56-8e3917acfa7d.jpg)
![bg3_small](https://user-images.githubusercontent.com/3201938/74732196-b12e8c80-5284-11ea-9564-9204771842f8.jpg)
![bg4_small](https://user-images.githubusercontent.com/3201938/74732200-b2f85000-5284-11ea-85eb-f009cfebd03b.jpg)
