### ISSUE TITLE
设置主题之后无法正常加载视图

### ISSUE THREAD

**Issue by Sorakage033** [jerrykuku/luci-theme-argon#286]
![image](https://user-images.githubusercontent.com/63045601/151674921-627387a9-d61f-4a9a-9e0c-2cfcaf7c77dc.png)
![image](https://user-images.githubusercontent.com/63045601/151674986-10fa0db3-2471-488d-9344-a6180e4f821c.png)

如图，只有登录页面正常，其它几乎所有页面都无法正常显示。
OpenWrt版本是OpenWrt 21.02.0，机器是小米AC2100

**Comment by jerrykuku** [comment]
可能版本错了，试试1.72

**Comment by Sorakage033** [comment]
上传并应用1.7.2版本之后页面无法正常加载，报错代码为
`/usr/lib/lua/luci/template.lua:97: Failed to execute template 'view'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/argon/header'.
A runtime error occurred: [string "/usr/lib/lua/luci/view/themes/argon/header...."]:23: attempt to call field 'node_childs' (a nil value)
stack traceback:
	[string "/usr/lib/lua/luci/view/themes/argon/header...."]:23: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:756: in function 'include'
	[string "/usr/lib/lua/luci/view/header.htm"]:3: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:756: in function 'include'
	[string "/usr/lib/lua/luci/view/view.htm"]:1: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function </usr/lib/lua/luci/template.lua:85>
	(tail call): ?
	/usr/lib/lua/luci/dispatcher.lua:954: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>`
请问如何解决呢？

**Comment by jerrykuku** [comment]
先设置用默认主题吧，我也不确定是什么问题，可以问问同设备的人用的什么版本

**Comment by Sorakage033** [comment]
好的，感谢

**Comment by MBRjun** [comment]
同问题，我是 x86_64 OpenWrt R22.1.1 ，使用最新 Release

**Comment by c939984606** [comment]
同问题，我是 x86_64 OpenWrt R22.1.1 ，使用最新 Release +1

**Comment by MBRjun** [comment]
> 

换成 1.7.2

**Comment by MBRjun** [comment]
> 同问题，我是 x86_64 OpenWrt R22.1.1 ，使用最新 Release +1

换成 1.7.2

**Comment by lr085818** [comment]
换个版本吧带不起来
