### ISSUE TITLE
Lean下Argon Bug

### ISSUE THREAD

**Issue by King-Of-Knights** [jerrykuku/luci-theme-argon#288]
**Describe the bug**
Lean系统，出现以下错误：
```
/usr/lib/lua/luci/dispatcher.lua:474: Failed to execute function dispatcher target for entry '/'.
The called action terminated with an exception:
/usr/lib/lua/luci/util.lua:627: Unable to establish ubus connection
stack traceback:
 [C]: in function 'assert'
 /usr/lib/lua/luci/dispatcher.lua:474: in function 'dispatch'
 /usr/lib/lua/luci/dispatcher.lua:126: in function </usr/lib/lua/luci/dispatcher.lua:125>
```

**To Reproduce**
Lean编译代码：
```
cd package/lean
rm -rf luci-theme-argon
git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git
git clone https://github.com/jerrykuku/luci-app-argon-config
```
过段时间，“系统"处会出现这个错误

**Expected behavior**
此类错误影响进入后台，需要手动修改Luci更换皮肤

**Screenshots**
[![HcsyjS.md.png](https://s4.ax1x.com/2022/02/15/HcsyjS.md.png)](https://imgtu.com/i/HcsyjS)

**Openwrt (please complete the following information):**
 - Versiosn: [e.g. 18.06-lean]
 - Theme [e.g. argon]
 - Version [e.g. 2.27]

**Comment by jerrykuku** [comment]
看上去你弄错了版本 lean源码 要拉取18.06 分支
