### ISSUE TITLE
在官方openwrt出现乱码

### ISSUE THREAD

**Issue by HAN5201** [jerrykuku/luci-theme-argon#290]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Openwrt (please complete the following information):**
 - Versiosn: [e.g. 18.06-lean]
 - Theme [e.g. argon]
 - Version [e.g. 2.27]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SpeedPartner** [comment]
请提供相对完整的反馈信息.
如还存在问题,请重新提出issue
