### ISSUE TITLE
建议 概况 页面精简一下

### ISSUE THREAD

**Issue by lon91ong** [jerrykuku/luci-theme-argon#294]
![2022-02-25_154129](https://user-images.githubusercontent.com/16462258/155675389-b765b724-ec30-4ce1-bd55-5a1545fb5972.png)
如上图所示, CPU 的可用和已用 一条就明朗了, 两条反而迷惑, 显示"可用"的进度条与传统UI直觉矛盾, 建议保留"已使用"即可
下面的类似, "已缓存"和"空闲交换区"一直都没有变化过, 迷惑的进度条, 建议去掉

**Comment by jerrykuku** [comment]
本页面不在主题页面的控制范围内

**Comment by MBRjun** [comment]
这是你固件的问题。请更换固件

**Comment by lon91ong** [comment]
> 这是你固件的问题。请更换固件

这个是自己在线编译的, 用的Lienol/openwrt/main源码, 不知需要修改源码的哪些配置文件呢?

**Comment by MBRjun** [comment]
不知道 我是 openwrt/openwrt

**Comment by lon91ong** [comment]
> 



> 不知道 我是 openwrt/openwrt

就你的openwrt/openwrt情况说说, 需要改哪里的配置文件, 给我照猫画虎个指引

**Comment by MBRjun** [comment]
默认就这样）

**Comment by HiJwm** [comment]
![33](https://user-images.githubusercontent.com/104122387/166588695-6cc60297-f4a0-4954-ad8b-098967a74c2c.png)

**Comment by lon91ong** [comment]
@HiJwm 求教
