### ISSUE TITLE
网络-接口页面报错："firewall.getZoneColorStyle is not a function"

### ISSUE THREAD

**Issue by VergilGao** [jerrykuku/luci-theme-argon#295]
点击网络-接口，页面上会报错：firewall.getZoneColorStyle is not a function
![Uploading 2022-03-03_20-11-52.png…]()

**Openwrt (please complete the following information):**
 - Versiosn: [21.02.2]
 - Theme [argon]
 - Version [commit [46906ac](https://github.com/jerrykuku/luci-theme-argon/commit/46906ac8ab96e63b8e2a5fc2f349a6961f5ef136)]

**Desktop (please complete the following information):**
 - OS: [window 10]
 - Browser [edge]
 - Version [lastest]

**Comment by chanfried** [comment]
21.02.1是正常的，升级到21.02.2后出现该问题。

**Comment by jerrykuku** [comment]
我来排查一下

**Comment by mingxiaoyu** [comment]
OpenWrt 21.02.1
也有这个问题

**Comment by chanfried** [comment]
我这里重启一下能解决了，原因未知。

**Comment by wulfy23** [comment]
flush browser cache manually, try alternate browser
