### ISSUE TITLE
排版问题，希望大佬修修！

### ISSUE THREAD

**Issue by zxlhhyccc** [jerrykuku/luci-theme-argon#296]
不在合适的位置展示：
![image](https://user-images.githubusercontent.com/45259624/156867094-5cbcee1c-d023-4eaf-bea3-c0b698f9f4ba.png)
2020主题及其他主题展示的更合理：
![image](https://user-images.githubusercontent.com/45259624/156867123-73a310b7-762a-4a5a-9992-d5be5a68708e.png)

**Comment by SpeedPartner** [comment]
这就是本主题的layout设计啊
