### ISSUE TITLE
lede的编译替换问题

### ISSUE THREAD

**Issue by zorrose82** [jerrykuku/luci-theme-argon#297]
cd lede/package/lean  
rm -rf luci-theme-argon  
git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git  
make menuconfig #choose LUCI->Theme->Luci-theme-argon  
make -j1 V=s  

命令中的替换lede/package/lean   下的包，但是目前lead代码下，这个目录已经没有了

搜了一下，是在下面目录，是要替换这个路径的包编译吗
/lede/feeds/luci/themes/luci-theme-argon

**Comment by zorrose82** [comment]
Commits on Feb 15, 2022 [package/lean: move to luci feeds (](https://github.com/coolsnowwolf/lede/commit/cc9ce1dbb53b58c66fd5e72e6ec7a5e7428d91d2)https://github.com/coolsnowwolf/lede/pull/8882[)](https://github.com/coolsnowwolf/lede/commit/cc9ce1dbb53b58c66fd5e72e6ec7a5e7428d91d2)

看到是2022-2-15 把这些包移除了

**Comment by jerrykuku** [comment]
尝试 git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git luci-theme-argon-18.06

**Comment by zrw-cxy** [comment]
> > 尝试 git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git luci-theme-argon-18.06
> 
> 搞定，感谢



> > 试用 git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git luci-theme-argon-18.06
> 
> 搞定，谢谢

你好呀，我有几个疑问想请教一下🧐

1. 请问是先去/lede/feeds/luci/themes/目录下把原来的luci-theme-argon删掉然后再git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git luci-theme-argon-18.06
2. 还是说cd 进入/lede/feeds/luci/themes/目录下不删掉原来的直接克隆git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git luci-theme-argon-18.06
3. 还是说进入原来的lede/package/lean下运行git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git luci-theme-argon-18.06

因为每次我编译完后都进不入后台，后来我也发现了lede/package/lean下的包转移去/lede/feeds/luci/themes/目录下了，我试过直接替换，但是编译出来还是一片空白😢......若是方便的话可以指教一下吗？谢谢💖

**Comment by jerrykuku** [comment]
直接添加 我的package就可以了 不冲突。参考这里：https://github.com/jerrykuku/openwrt-package

**Comment by zrw-cxy** [comment]
> 直接添加 我的package就可以了 不冲突。参考这里：https://github.com/jerrykuku/openwrt-package 编译的时候 Theme选 luci-theme-argon-18.06

搞定了，thanks😘

**Comment by nrjycyd** [comment]
> 直接添加 我的package就可以了 不冲突。参考这里：https://github.com/jerrykuku/openwrt-package 编译的时候 Theme选 luci-theme-argon-18.06

直接用大神的package ,“luci-theme-argon-18.06”可正常编译，但是"luci-app-argon-config"编译时提示WARNING: Not overriding core package 'luci-app-argon-config'; use -f to force，无法正常选择插件。

**Comment by zhengmz** [comment]
是否考虑把 18.06 分支推送到 <https://github.com/coolsnowwolf/luci> 

这样，我们就不用先删除，再添加

**Comment by Fddh2012** [comment]
> 是否考虑把 18.06 分支推送到 https://github.com/coolsnowwolf/luci
> 
> 这样，我们就不用先删除，再添加

的确，感觉这样最好，

**Comment by jerrykuku** [comment]
拉取我的package就行了 选argon18.06
