### ISSUE TITLE
登陆界面会强制重定向到https

### ISSUE THREAD

**Issue by zhangdp** [jerrykuku/luci-theme-argon#298]
登陆界面首先报错403然后强制重定向到https，配置使用内建，有上传本地壁纸
![微信截图_20220313150554](https://user-images.githubusercontent.com/26567414/158049262-55b90d4a-9d73-4306-9b0f-0b89c1549346.png)
![微信截图_20220313150640](https://user-images.githubusercontent.com/26567414/158049265-26680f9c-35f7-4bda-90b2-b0916a80e7b4.png)
![微信截图_20220313150650](https://user-images.githubusercontent.com/26567414/158049266-d6991b6d-3bde-44a4-909b-9c8f1f2e82a8.png)

**Comment by MBRjun** [comment]
换个主题也有这个情况吗？这可能是您固件的问题
