### ISSUE TITLE
可否写一个编译教程，谢谢

### ISSUE THREAD

**Issue by snakwu** [jerrykuku/luci-theme-argon#3]
可否写一个编译教程，谢谢

**Comment by jerrykuku** [comment]
参见 lean 的openwrt 编译教程

**Comment by snakwu** [comment]
编译我会，但是怎么加主题编译不会，谢谢

**Comment by jerrykuku** [comment]
此主题只适配lean 的openwrt 其实lean 的已经集成了 自己搞的话 直接扔进package/lean 然后 make menuconfig 在luci theme 里选中即可 和普通app 一样的

**Comment by snakwu** [comment]
明白了，谢谢

**Comment by snakwu** [comment]
官方源码的不能用吗？

**Comment by jerrykuku** [comment]
暂时不适配
