### ISSUE TITLE
图标不显示

### ISSUE THREAD

**Issue by lloyd18** [jerrykuku/luci-theme-argon#30]
图标不显示，依稀记得之前有人问过，不过找完iss没看到有，大佬说说怎么回事

**Comment by lloyd18** [comment]
![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/75325963-bdce6880-58b4-11ea-8660-e3c2cf741a07.jpg)

**Comment by YYiiEt** [comment]
参考#23 ，编译时把luci->moudle的minify css关闭
