### ISSUE TITLE
lede固件的luci-theme-argon-config上传图片后没有生效，依旧是默认界面

### ISSUE THREAD

**Issue by nuo12138** [jerrykuku/luci-theme-argon#302]
![截图_20225327075323](https://user-images.githubusercontent.com/41539650/160280229-acdc6499-67c6-4741-b392-41ed355d74a0.png)
![截图_20225327075332](https://user-images.githubusercontent.com/41539650/160280235-e422da6d-4d06-47ea-9e90-08a4af1bcd13.png)
上传图片后依旧是默认的首页

**Comment by xiaoxielei** [comment]
楼主这是啥路由器，配置这么高

**Comment by nuo12138** [comment]
> 楼主这是啥路由器，配置这么高

R4S,内存卡分的空间大一点了而已

**Comment by nuo12138** [comment]
> 图片需要小写`.jpg`结尾
谢谢 可以了！
