### ISSUE TITLE
编译进固件字体显示不正常

### ISSUE THREAD

**Issue by jakiro6708** [jerrykuku/luci-theme-argon#303]
openwrt官方源21.02，将主题编译进固件，左上角的openwrt字体显示不正常，重新安装主题ipk文件后正常
![Snipaste_2022-04-02_12-08-25](https://user-images.githubusercontent.com/99260672/161365736-d9741c22-3b40-440f-9405-ebdc5e485fe7.png)

**Comment by castillofrancodamian** [comment]
In snapshots you can also see these errors. I compiled my own image

**Comment by jerrykuku** [comment]
Please disable the minimize css option before compiling.
