### ISSUE TITLE
1.7.2版本設置內建壁紙但依舊會顯示bing壁紙

### ISSUE THREAD

**Issue by RGHSSS** [jerrykuku/luci-theme-argon#306]
1.7.2版本設置內建壁紙但依舊會顯示bing壁紙
版本：OpenWrt R22.2.2 compiled by ES on 21.02.2022 / LuCI Master (git-22.052.34668-380e994)

**Comment by jim3ma** [comment]
相同的问题，我刚好在研究代码，看看哪里的问题

**Comment by jim3ma** [comment]
https://github.com/jerrykuku/luci-theme-argon/blob/v1.7.2/luasrc/view/themes/argon/sysauth.htm#L73
这里判断写错了：

```
if ( bing_background == 0 ) then
```

应该为

```
if ( bing_background == "0" ) then
```

**Comment by RGHSSS** [comment]
> https://github.com/jerrykuku/luci-theme-argon/blob/v1.7.2/luasrc/view/themes/argon/sysauth.htm#L73
> 
> 这里判断写错了：
> 
> ```
> if ( bing_background == 0 ) then
> ```
> 
> 应该为
> 
> ```
> if ( bing_background == "0" ) then
> ```
> 
> 手动修改 `/usr/lib/lua/luci/view/themes/argon/sysauth.htm` 后可用。

謝謝，能用了

**Comment by jerrykuku** [comment]
> > https://github.com/jerrykuku/luci-theme-argon/blob/v1.7.2/luasrc/view/themes/argon/sysauth.htm#L73
> > 这里判断写错了：
> > ```
> > if ( bing_background == 0 ) then
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 应该为
> > ```
> > if ( bing_background == "0" ) then
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 手动修改 `/usr/lib/lua/luci/view/themes/argon/sysauth.htm` 后可用。
> 
> 謝謝，能用了



> https://github.com/jerrykuku/luci-theme-argon/blob/v1.7.2/luasrc/view/themes/argon/sysauth.htm#L73
> 
> 这里判断写错了：
> 
> ```
> if ( bing_background == 0 ) then
> ```
> 
> 应该为
> 
> ```
> if ( bing_background == "0" ) then
> ```
> 
> 手动修改 `/usr/lib/lua/luci/view/themes/argon/sysauth.htm` 后可用。

感谢提醒
