### ISSUE TITLE
更新 1.7.3 版本后，点击二级菜单后每次都会自动收回

### ISSUE THREAD

**Issue by davidtall** [jerrykuku/luci-theme-argon#309]
使用lean 的源码编译 1.7.3 版本，每次点击二级菜单，一级菜单就会自动收回,每次都得重新点开菜单。而1.7.2没有这个问题

https://github.com/kenzok78/luci-theme-argonne/issues/4

**Comment by jerrykuku** [comment]
问题已经修复，重新拉取编译应该能够解决。感谢反馈。

**Comment by davidtall** [comment]
解决了，谢谢

**Comment by davidtall** [comment]
【v1.7.3】修复访问状态/防火墙页面时，左边导航长时间无响应问题。

修复了上面的自动收回的问题后，这个防火墙问题似乎又出现了，点击防火墙时，条目过多时加载要好几秒，这几秒内左边的导航菜单无法操作，不知道这个是不是bug

**Comment by jerrykuku** [comment]
我自己测试，也找其他朋友测试了，新编译的固件，防火墙页面的左侧菜单是正常的，不受右边加载影响。

**Comment by davidtall** [comment]
@jerrykuku 1.7.2版本点击防火墙，左侧菜单全部是收回的，防火墙没加载完的几秒内无法点击任何按钮。

现在最新版：点击防火墙后，“状态”一级菜单是展开的，“状态”下所有的二级菜单都可以点击跳转，但是除“状态”外其他所有一级菜单都无法点击切换展开，必须等防火墙加载完后才能操作其他菜单。 例如点击防火墙后，接着点击 “系统”一级菜单无反应，必须几秒过后等“防火墙”加载完毕才能操作

**Comment by jerrykuku** [comment]
尝试清空缓存试试看。

**Comment by davidtall** [comment]
@jerrykuku 试过了，清空缓存，CTRL + F5 刷新，换浏览器，都是一样的情况，我用了passwall 插件，防火墙条目比较多，我算了一下加载完要15秒，这15秒内我无法点击任何的一级菜单
![image](https://user-images.githubusercontent.com/9320941/164991555-21bb39ba-87f2-4fd8-85fd-523adc5bac4f.png)
![image](https://user-images.githubusercontent.com/9320941/164991572-c72d5b21-5681-4c5b-b6bb-06fcfb150972.png)
![image](https://user-images.githubusercontent.com/9320941/164991602-86145cd7-5d8a-4269-99dc-22fbc5d163bc.png)

**Comment by jerrykuku** [comment]
是全新编译的还是下载的release?

**Comment by davidtall** [comment]
@jerrykuku 全新编译 ，x86 平台，如果你用虚拟机防火墙条目少加载很快的话可能无法复现，我是生产环境加载 要15秒。我看了script.js 文件，又的确是你修复后的最新版
```
rm -rf luci-theme-argon  
git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git  
```

我已经到百度网盘了，你可以试试看
链接: https://pan.baidu.com/s/1vHsQ1_e9AGv4rVdKWbCP1Q?pwd=bjdi 提取码: bjdi 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by davidtall** [comment]
@jerrykuku 我编译了一个星际宝盒的全新固件，也是一样的情况。你那边测试正常，可以编译一个lean 源码的x86固件让我试试吗？没找到是哪里的问题

**Comment by CDLLY** [comment]
Emm, 刚更新完，不太确定，就不开issues了..
借地确认一下，咱是换登录界面了嘛，还是说是我这边编译出问题了...
![image](https://user-images.githubusercontent.com/20614068/165515426-5b77387f-2789-4e03-a04e-99fe04f870eb.png)

**Comment by davidtall** [comment]
@jerrykuku 请问这个确定是bug对吗？我好像知道怎么回事了，luci-static/argon/js/script.js 这个文件要等cgi-bin/luci/admin/status/iptables 加载完才会加载,那是不是把 script.js 挪到文件头部就能解决了？

**Comment by leslieqwq** [comment]
大神什么时候更新下release

**Comment by ausmas** [comment]
能不能麻烦大神更新下release

**Comment by davidtall** [comment]
> @jerrykuku 1.7.2版本点击防火墙，左侧菜单全部是收回的，防火墙没加载完的几秒内无法点击任何按钮。
> 
> 现在最新版：点击防火墙后，“状态”一级菜单是展开的，“状态”下所有的二级菜单都可以点击跳转，但是除“状态”外其他所有一级菜单都无法点击切换展开，必须等防火墙加载完后才能操作其他菜单。 例如点击防火墙后，接着点击 “系统”一级菜单无反应，必须几秒过后等“防火墙”加载完毕才能操作

1.7.7 版本，这个问题依然存在，另外出现前缀相同的插件时，二级菜单不会展开，例如同时安装 luci-app-passwall 和 luci-app-passwall2 时，点击 passwall 二级菜单不会展开

**Comment by SpeedPartner** [comment]
一般用户不会经常去看iptables吧?点错了按返回键就行,不用等它加载完.当然如果你有好的办法,欢迎PR,我个人能力有限.

至于问题2,有人在1.7.7版本后已经PR,可以试试用18.06分支全新编译试试
https://github.com/jerrykuku/luci-theme-argon/pull/391

**Comment by SpeedPartner** [comment]
刚抽空检查了下,应该能解决了iptables加载时导航菜单卡住的问题了,我测试几天,稳定的话就PR
