### ISSUE TITLE
Tab背景色不会受到luci-theme-argon-config的主色调设置影响

### ISSUE THREAD

**Issue by TGSAN** [jerrykuku/luci-theme-argon#311]
![image](https://user-images.githubusercontent.com/7440847/164976443-7d7e92ca-5e0e-4beb-9631-81aede1b61e0.png)
如图所示，如`.cbi-tabmenu li[class~="cbi-tab"]`这样的背景色不会受到设置里的主色调影响，无论设置什么颜色都是蓝色的，看上去怪怪的。
**Openwrt:**
 - Versiosn: OpenWrt R22.2.2 / LuCI Master (git-21.335.48743-5f363d9) lean
 - Theme: luci-theme-argon-18.06
 - Version: 1.7.3-20220421

**Comment by jerrykuku** [comment]
未来尽力修复，估计要等到黄金周了。

**Comment by TGSAN** [comment]
> 未来尽力修复，估计要等到黄金周了。

辛苦了~

**Comment by SpeedPartner** [comment]
太细了,我都没注意到....我来改进下
