### ISSUE TITLE
增加强制暗色模式，好像不能强制

### ISSUE THREAD

**Issue by zhoujinshi** [jerrykuku/luci-theme-argon#313]
**Describe the bug**
进入ssh 输入 "touch /etc/dark" 进行开启
创建了这个文件好像不能强制暗色模式

**Comment by Howard20181** [comment]
- `【v2.2.5】Modify the file structure to adapt to luci-app-argon-config. The old method of turning on dark mode is no longer applicable, please use it with luci-app-argon-config.`

**Comment by jerrykuku** [comment]
will check that.
