### ISSUE TITLE
登陆界面似乎异常了..

### ISSUE THREAD

**Issue by Kissycat** [jerrykuku/luci-theme-argon#315]
**Describe the bug**
如图，没有壁纸，界面好像也有些异常...
选自自建或者bing都是这样

**To Reproduce**
从1.7.2更新上了就这样了，编译最新master或者安装releases里的18.06都是这样的

**Expected behavior**
这个界面应该是不对的吧，不会是新界面应该的亚子吧，请帮帮我让它显示出该有的样子..

**Screenshots**
![image](https://user-images.githubusercontent.com/20614068/165518363-f01cdcc2-d1b3-4e6b-abf6-55379edfddd0.png)

**Openwrt (please complete the following information):**
 - Versiosn: lean的R22.4.1 和lienol的luci 18.06
 - Theme [argon]
 - Version [1.7.3]

电脑手机chrome 101都是这样..

**Comment by Kissycat** [comment]
回滚验证界面htm后正常了，新版不会真的是设计成这样的吧，不要啊😭
![S20427-22382284](https://user-images.githubusercontent.com/20614068/165544402-6962de1e-757c-4d02-834b-9974d98b0a43.png)

**Comment by msdos03** [comment]
我也这样了，请问你是执行了什么操作才正常的啊？我只是更新了feeds就这样了😥

**Comment by Kissycat** [comment]
> 我也这样了，请问你是执行了什么操作才正常的啊？我只是更新了feeds就这样了😥

不造，重新拉了18.06就正常了，估计是那天没睡醒，本地操作的时候弄错文件夹了😪

**Comment by msdos03** [comment]
> > 我也这样了，请问你是执行了什么操作才正常的啊？我只是更新了feeds就这样了😥
> 
> 不造，重新拉了18.06就正常了，估计是那天没睡醒，本地操作的时候弄错文件夹了😪

更新到最新版snapshot luci试试，就又会炸了。还不是我一个人的问题
