### ISSUE TITLE
有计划开发op22.03主题吗

### ISSUE THREAD

**Issue by HiJwm** [jerrykuku/luci-theme-argon#316]
如题，请问老大有计划开发吗

**Comment by jerrykuku** [comment]
22.03不能用么？

**Comment by HiJwm** [comment]
argon-config 不可以用

**Comment by zzz6839** [comment]
自测可以，如果出现Lua之类的文字错误，在软件包安装luci-lib-ipkg

OpenWrt 22.03.0-rc1 r19302-df622768da / LuCI openwrt-22.03 branch git-22.083.69105-af8e91c
