### ISSUE TITLE
请问OpenWrt R22.3.23 / LuCI Master (git-22.068.45502-a50e601)应该下载安装哪个版本的？

### ISSUE THREAD

**Issue by calonye** [jerrykuku/luci-theme-argon#317]
请问OpenWrt R22.3.23 / LuCI Master (git-22.068.45502-a50e601)应该下载安装哪个版本的？

看系统版本号的话，应该是安装[luci-theme-argon-master_2.2.9.4_all.ipk]，但是安装启用主题后页面一片空白；
换了尝试[luci-theme-argon-18.06_1.7.3-20220421_all.ipk]也会同样问题，瞬间懵了。不清楚是不是系统版本还没被适配还是什么缘故。

**Comment by calonye** [comment]
哦，知道了，标注[lean源码可用]的即可，谢谢

**Comment by Yinsel** [comment]
需要手动选择安装某些依赖吗？
