### ISSUE TITLE
最近用Bing源好像拉不到资源了？

### ISSUE THREAD

**Issue by Fddh2012** [jerrykuku/luci-theme-argon#326]
最近老是会出现黑屏问题，以为是不兼容，结果发现自己是用的Bing源，切换到内置图片就没问题了。

**Comment by wpsdoo** [comment]
确实,还会出现白屏,黑屏的问题.最新的 1.7.3在lean源码下的op 会出现点击二级菜单自动收回的问题

**Comment by SpeedPartner** [comment]
比如PassWalll,可以在规则列表中把bing.com从代理列表中移除或者注释.

**Comment by Fddh2012** [comment]
那是之前，就拉取bug，现在不会了。

**Comment by SpeedPartner** [comment]
Emmm....但是18.06分支这边的还没解决
