### ISSUE TITLE
自动刷新按钮的文字不会反色

### ISSUE THREAD

**Issue by HahahahaChen** [jerrykuku/luci-theme-argon#327]
如下图：
开启自动刷新
![image](https://user-images.githubusercontent.com/42169759/168408593-142bfde4-22d2-4689-826f-164eb4788292.png)
关闭自动刷新
![image](https://user-images.githubusercontent.com/42169759/168408609-16f85bcf-c5e8-43dc-9304-dce6b50f9310.png)
固件版本为op官方版本21.02.2

**Comment by clonin216** [comment]
我也有同樣問題
