### ISSUE TITLE
lean固件下软件包页面显示异常

### ISSUE THREAD

**Issue by gq20110204** [jerrykuku/luci-theme-argon#331]
软件包空闲空间条显示异常 变成了原始的样式
![捕获](https://user-images.githubusercontent.com/22221191/168960779-e557b4f6-b404-4d8a-bd58-4bc186cffda3.PNG)
更新1.7.3后出现异常 尝试替换旧版的script.js后恢复正常

**Comment by jerrykuku** [comment]
近期修复
