### ISSUE TITLE
视频背景无法开启音频

### ISSUE THREAD

**Issue by Tigerest** [jerrykuku/luci-theme-argon#333]
固件版本为：OpenWrt R22.1.1 GDQ Winter[2022] Compiled by eSir / LuCI Master (git-21.335.48743-5f363d9)
使用luci-theme-argon-18.06 | 1.7.3-20220421版本主题时背景导入mp4视频，格式如下
![image](https://user-images.githubusercontent.com/45537505/169217067-735b7df6-c928-46df-84d0-808c7c216d8e.png)
在登录页面处音频按钮失效，始终处于静音状态无法打开

**Comment by jerrykuku** [comment]
我再测试下看看是什么问题
