### ISSUE TITLE
請問左邊選單無法顯示的問題

### ISSUE THREAD

**Issue by clonin216** [jerrykuku/luci-theme-argon#336]
版本:
[Powered by LuCI branch (git-22.143.36230-ba1f116)](https://github.com/openwrt/luci) / [ArgonTheme v2.2.9.4](https://github.com/jerrykuku/luci-theme-argon) / LEDE 1.14.0 r10947-65030d81f3 v19.07.2_maxlinear

請問我將最新的 luci-theme-argon 模組加入我們的 openwrt，但左邊的選單始終無法顯示，請問可能原因是什麼? 另外負責左邊選單的布置是在哪一個檔案做處理，目前初步懷疑是 menu-argon.js 這個檔案裡面引用到 'require baseclass'; 我們的系統似乎不支援它

![pic1](https://user-images.githubusercontent.com/19902816/169869547-18fbbe9d-d722-4cde-af9e-57b463a091fc.jpg)

**Comment by clonin216** [comment]
已解決~將luci更新至最新版本

**Comment by LAOZTK** [comment]
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/38147713/179345340-562a0f29-9477-44de-8e58-63f123344494.png">
我也遇到了同样的问题
使用的 luci-theme-argon-18.06_1.7.3-20220421_all.ipk

**Comment by SpeedPartner** [comment]
各种安装错版本的
