### ISSUE TITLE
OpenWrt R20.2.15 安装最新2.2.9.4左侧不显示

### ISSUE THREAD

**Issue by greedisgoood** [jerrykuku/luci-theme-argon#338]
<html>
<body>

固件版本 | OpenWrt R20.2.15 / LuCI Master (git-19.299.52050-0b735ea)

安装For openwrt official 21.02 Snapshots LuCI master，侧边栏无显示
-- | --

</body>
</html>

**Comment by jerrykuku** [comment]
是大雕版固件吧，请选择 V1.7.x

**Comment by greedisgoood** [comment]
[For Lean Lede 18.06 LuCI](https://github.com/jerrykuku/luci-theme-argon/releases/tag/v1.7.3)

**Comment by greedisgoood** [comment]
是的  我发现问题所在了  谢谢
