### ISSUE TITLE
The login screen does not play audio

### ISSUE THREAD

**Issue by Kirito666233** [jerrykuku/luci-theme-argon#343]
OpenWrt R22.7.7 / LuCI Master (git-22.190.54720-e2af321)
ArgonTheme v1.7.3
The login screen does not play audio,
The mute button at the top right of the interface cannot be cancelled

![_2{R58HAW}%T)% IJ(}F6KY](https://user-images.githubusercontent.com/65284806/178398152-f233c80b-55a2-4a7d-bd1a-35d835c8501b.png)
![O{2QPQE@UYUKB%WJLEX~I0H](https://user-images.githubusercontent.com/65284806/178398163-947efa32-636c-4470-bf06-97ea9ed00c47.png)

**Comment by TendernessRadif** [comment]
me too
