### ISSUE TITLE
没有显示Argon config, openWRT21.02, 小米AC2100

### ISSUE THREAD

**Issue by MMMMMoris** [jerrykuku/luci-theme-argon#348]
![image](https://user-images.githubusercontent.com/63332824/188792014-723e13f3-747e-467b-a2b8-2582de9358f3.png)
![image](https://user-images.githubusercontent.com/63332824/188792040-95e76468-39eb-4e18-85e0-1259dd29a279.png)
请问这是为什么？有什么方法可以解决吗？

**Comment by Leesace** [comment]
`argon-config` 是额外的 app，可能你没有安装，可以在此 repo 的 Releases 里面找到安装包。
