### ISSUE TITLE
无法访问github

### ISSUE THREAD

**Issue by token361** [jerrykuku/luci-theme-argon#349]
**Describe the bug**
在旁路由的docker里面安装了这个 测试giuhub和谷歌都成功 也能正常访问油管和谷歌  就是无法访问github 明明代理域名里面有这个giuhub.com 也不是梯子的问题 我在电脑上用v2rayn可以访问giuhub 但是passwall设置全局模式也不能访问github

**To Reproduce**
点击giuhub网站 显示拒绝访问

**Expected behavior**
正常访问github

**Screenshots**
![屏幕截图 2022-09-20 165856](https://user-images.githubusercontent.com/59979044/191216166-3e72725e-a547-45c4-a14e-9f60e0bd10e4.png)

**Openwrt (please complete the following information):**
 - Versiosn: [e.g. 18.06-lean][Powered by LuCI openwrt-18.06-k5.4 branch (git-22.131.38469-92a7844)](https://github.com/openwrt/luci)
 - Theme [e.g. argon] [ArgonTheme v1.7.3](https://github.com/jerrykuku/luci-theme-argon)
 - Version [e.g. 2.27] ImmortalWrt 18.06-k5.4-SNAPSHOT r12001-b57fb59041

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jerrykuku** [comment]
抱歉这并不属于 主题的管辖范畴。
