### ISSUE TITLE
bing.com random wallpaper not working when including repo in custom builds (latest openwrt snapshots)

### ISSUE THREAD

**Issue by AcidSlide** [jerrykuku/luci-theme-argon#352]
**Describe the bug**
The wallpaper does not change, or bing.com load script not working.  I'm doing custom builds and have included the theme as described here: https://github.com/jerrykuku/luci-theme-argon#openwrt-official-snapshots and all my builds and test builds, the wallpaper doesn't change, it's just stuck on the bg1.jpg image (picture of grass with morning dews).

**To Reproduce**
1. Included in OpenWRT package directory the cloned source as described in https://github.com/jerrykuku/luci-theme-argon#openwrt-official-snapshots
2. Include in the `make menuconfig` in Luci -> Themes -> luci-theme-argon (using '*')
3. Compile the custom build `make -j9`
4. Install/setup the compiled image

**Expected behavior**

**Screenshots**

**Openwrt (please complete the following information):**
 - Versios: Latest OpenWRT Snapshot (openwrt/openwrt -> master branch)
 - Theme: argon
 - Version: latest via direct git pull from source

**Desktop (please complete the following information):**
 - OS: iOS, Android, Mac OS (Monterey), Win 11, Win 10, Ubuntu 20.04, Ubuntu 22.04
 - Browser: chrome, safari, edge
 - Version: various but latest versions of each

**Smartphone (please complete the following information):**
 - Device: various devices
 - OS: various versions
 - Browser : safari, chrome and edge
 - Version: various versions

**Additional context**
Haven't tried not including in build and manually install the IPK.  But I have tried to reinstall via `opkg` using the latest release version of `luci-theme-argon` on the installed custom builds but same issue.

**Comment by jerrykuku** [comment]
You should install luci-app-argon-config
