### ISSUE TITLE
Lean固件samba4插件共享目录输入框过小

### ISSUE THREAD

**Issue by gsh1209** [jerrykuku/luci-theme-argon#355]
**Describe the bug**
Lean固件samba4插件共享目录的 名称、目录 输入框过小

**To Reproduce**
网络存储 > 网络共享 > 共享目录

**Screenshots**
![bug](https://user-images.githubusercontent.com/113790912/203336562-13893f5e-8660-4a88-b2df-90b5e8f24b3a.png)
更换其他主题后正常
![20221122222700](https://user-images.githubusercontent.com/113790912/203339297-4b21ef54-c73d-4519-a4dd-303200efc9c4.png)

**Openwrt (please complete the following information):**

`Powered by LuCI Master (git-22.323.58461-c7fb305)/ ArgonTheme v1.7.3/ OpenWrt R22.11.11`
自编译lean固件，`commit SHA 3c707a2ef840b14edd75a00fcfa09c9d95891b8b`
主题随固件一起编译
```
rm -rf package/feeds/luci/luci-theme-argon
git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/feeds/luci/luci-theme-argon
```

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser Google Chrome
 - Version 版本 107.0.5304.107（正式版本） （64 位）

**Comment by fxxccp** [comment]
遇到同样的bug，期待修复。

**Comment by Fyred** [comment]
同样问题，是不是lean的问题呢
