### ISSUE TITLE
"接口 - LAN"页面的标题“一般配置"和"DHCP 服务器"不显示（luci-theme-argon-1.7.3）

### ISSUE THREAD

**Issue by xbinghu** [jerrykuku/luci-theme-argon#361]
![1670313848906](https://user-images.githubusercontent.com/52552701/205859323-7f5a2c95-0666-40f9-9601-748f8aa0e5eb.jpg)
如图所示，“网络”-->“接口”-->"LAN"-->"修改"，"接口 - LAN"页面标题“一般配置"、"DHCP 服务器"不显示。"接口 - WAN"页面显示则正常

页面提示有如下错误：
![image](https://user-images.githubusercontent.com/52552701/205864806-07d2175e-19b8-428d-938c-e5e8af1604ea.png)

Versiosn: OpenWrt R21.4.18 / LuCI Master (git-22.211.60098-feaa27a)  LEDE v17.01
Theme: luci-theme-argon-1.7.3
Version: 1.7.3-20220421

**Comment by SpeedPartner** [comment]
没有定义observer...
在script.js的`if ($("#cbi-dhcp-lan-ignore").length > 0) {`上面增加一个observer定义
```
	const observer = new MutationObserver(() => {
	console.log("callback that runs when observer is triggered");
	});
```
