### ISSUE TITLE
插件名问题

### ISSUE THREAD

**Issue by Bunnui** [jerrykuku/luci-theme-argon#362]
有没有考虑一下修改一下名称，不然每次还得删除lede自带相同主题名称。

命名方案
luci-theme-argon-plus
luci-theme-argon-new
luci-theme-argon+
......

**Comment by Bunnui** [comment]
> 都是我的主题啊，为啥要因为这个改名？

emmm......好吧,主要lede库里的包和这名字冲突，得删除，有点麻烦。lede没有更新源码，感觉好丑

**Comment by jerrykuku** [comment]
lede是，最早期的版本，后面可能没有同步？
