### ISSUE TITLE
[master] 添加列表 加号错位

### ISSUE THREAD

**Issue by ningnao** [jerrykuku/luci-theme-argon#366]
![image](https://user-images.githubusercontent.com/118373565/208668473-9def00ef-8532-4406-b165-3febeaaaaa85.png)

**Comment by sjkhsl** [comment]
[https://halo.sjkhsl.site:8000/i/2022/12/21/63a2bbbd6884f.png](url)
passwall状态显示也不太完善！openwrt-22.03 master版本

**Comment by chendajun000104** [comment]
我遇到了跟你一样的问题，不知道这是openwrt更新引入的问题还是主题更新引入的问题。

**Comment by sjkhsl** [comment]
找到问题了，修改htdocs/luci-static/argon/css/cascade.css文件，搜索item:not([ondrop])>input，将{}中width:100%修改为80%。passwall的颜色问题可以搜索background-color:var(--lighter)第一个，h4{}标签中，删除background-color:var(--lighter);，将前面的background-color:#e9ecef改为background-color:#ffffff。

**Comment by jerrykuku** [comment]
这个问题已经修复了，见最新的更新。
