### ISSUE TITLE
PPTP VPN连接之后内网设备可以访问外网却无法正常访问

### ISSUE THREAD

**Issue by fengUi** [jerrykuku/luci-theme-argon#373]
1.因为有时候想通过家里联通网络科学上网，发现用pptp连接之后无法正常访问外网。百度都打不开。求教。

**Comment by rwmwan** [comment]
Good day @fengUi  i think this is more related to OpenWRT then the argon theme you might need to open a thread for this on OpenWRT forum to get assistance.
