### ISSUE TITLE
Cound't find Argon Settings

### ISSUE THREAD

**Issue by BinTofajjal** [jerrykuku/luci-theme-argon#376]
Couldn't find Settings for Argon.

**Expected behavior**
An Argon settings menubar on the left.

**Openwrt:**
 - Version:  OpenWrt 22.03.3
 - Theme: Argon
 - Version: 21.02

**Additional context**
I've directly installed ipk packages from GitHub by default it's dark mode, but I want to use the light mode.
The problem is there's no option for changing Argon Themes Dark to Light mode or configuring other things.
Completely missing a dedicated left-side menu bar.

**Comment by jerrykuku** [comment]
You should install https://github.com/jerrykuku/luci-theme-argon/releases/download/v1.7.3/luci-app-argon-config_0.9-20210309_all.ipk

**Comment by BinTofajjal** [comment]
When I click on the argon settings from the sidebar it shows - 

...ib/lua/luci/model/cbi/argon-config/configuration.lua:3: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	...ib/lua/luci/model/cbi/argon-config/configuration.lua:3: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1531: in function '_form'
	/usr/lib/lua/luci/dispatcher.lua:1059: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:483: in function </usr/lib/lua/luci/dispatcher.lua:482>

**Comment by BinTofajjal** [comment]
Solve by installing install luci-lib-ipkg

**Comment by kimlulz** [comment]
@BinTofajjal Thanks!

**Comment by BinTofajjal** [comment]
> @BinTofajjal Thanks!

Welcome :)

**Comment by rn777** [comment]
It's work perfectly. Thank's.
