### ISSUE TITLE
The hidden password button shows a misplacement and automatically jumps to the next line

### ISSUE THREAD

**Issue by openwrtdiy** [jerrykuku/luci-theme-argon#378]
After changing the luci-theme-argon theme, the hidden password button in the password bar is displayed in a misplaced position, and it automatically jumps to the next line! When using a mobile browser, the hidden password button is still displayed in a misplaced position, and the distance between the enabled button display is too large!

![20230212162749](https://user-images.githubusercontent.com/57249132/218301308-77fdcd65-f464-4023-a292-b252d9cb2f27.png)
![20230212163353](https://user-images.githubusercontent.com/57249132/218301322-d34a7018-68ac-49c2-9c31-b05ba61c5820.png)
![20230212163407](https://user-images.githubusercontent.com/57249132/218301326-644ea3de-49ae-406f-b596-a68d08e09806.png)
![20230212163418](https://user-images.githubusercontent.com/57249132/218301329-e19c2bda-546d-40eb-87ac-7d86115a980c.png)

**Comment by castillofrancodamian** [comment]
English please.

**Comment by openwrtdiy** [comment]
> English please.

It has been updated to English! At the same time, the wrong location is indicated with a red arrow
