### ISSUE TITLE
你好，问一下问题可以吗？

### ISSUE THREAD

**Issue by cjlhll** [jerrykuku/luci-theme-argon#379]
你好，我也是一名前端开发，我想fork你的仓库优化一下。请问怎么才能实时看到效果呢。难道要在F12的source里修改再看效果吗？但是一刷新就没了。很不方便。

**Comment by jerrykuku** [comment]
我自己是部署好以后使用sftp 同步更改，就是不能热更新，要不停的f5刷新。

**Comment by cjlhll** [comment]
> 

好的。我明白了。感谢。我以为有能直接运行源代码的方法呢。

**Comment by jerrykuku** [comment]
欢迎优化好 回来pr。

**Comment by cjlhll** [comment]
> 欢迎优化好 回来pr。

有时间就整。^_^

**Comment by cjlhll** [comment]
> 欢迎优化好 回来pr。

我的fork提交了一版。调整了openclash的样式。特别是移动端的。调整了概览。网络接口的移动端样式。
