### ISSUE TITLE
大佬，18.06分支还更新吗

### ISSUE THREAD

**Issue by lloyd18** [jerrykuku/luci-theme-argon#38]
luci-app-nlbwmon 这个插件显示异常
表现在点上方的MAC地址查看详情会被表格遮挡，最下面的可以正常显示

**不正常显示**
![2](https://user-images.githubusercontent.com/10294460/76616859-f1b9b700-655f-11ea-80a0-0164316f63d0.png)

**正常显示**
![1](https://user-images.githubusercontent.com/10294460/76616902-0bf39500-6560-11ea-9363-691dd81b2f70.png)

**Comment by DongfeiSay** [comment]
确实该更新下了，希望能优化了，以及新版的上面的紫块，我总感觉很别扭啊。。。
![99](https://user-images.githubusercontent.com/49421020/76640904-af0dd400-658b-11ea-9c8a-e48daa6b3482.JPG)
![999](https://user-images.githubusercontent.com/49421020/76640922-b6cd7880-658b-11ea-9568-7d9aa804e5d3.JPG)

**Comment by DongfeiSay** [comment]
> 确实该更新下了，希望能优化了，以及新样式上面的紫块，我总感觉很别扭啊。。。
> ![99](https://user-images.githubusercontent.com/49421020/76640904-af0dd400-658b-11ea-9c8a-e48daa6b3482.JPG)
> ![999](https://user-images.githubusercontent.com/49421020/76640922-b6cd7880-658b-11ea-9568-7d9aa804e5d3.JPG)

看到这么大个紫块上面的一条线了吗？紫色到哪就差不多了，线下面的很影响美观

**Comment by jerrykuku** [comment]
会考虑 最近忙 后面会重新优化
