### ISSUE TITLE
最新版无法适应lede版吗

### ISSUE THREAD

**Issue by threerog** [jerrykuku/luci-theme-argon#381]
最新版无法适应lede版吗

**Comment by davidtall** [comment]
lean的源码编译要用18.06的版本

**Comment by threerog** [comment]
我的意思是新版的无法适配吗，毕竟新版2.x了，18.06的才1.7.3
另外新版是基于openwrt原版适配的吗

**Comment by davidtall** [comment]
如果你的lede指的是lean大的lede，就只能用18.06的，因为lean的LUCI是18.06的。openwrt官方的源码或者lienol的21.02 可以适配这个主题的2.x 版本

**Comment by jerrykuku** [comment]
两个版本在实际的功能上没有区别，实际上几乎是同时开发的。只是为了区分luci18.06和最新版 所以做了两个分支的版本。

**Comment by miyouzi** [comment]
我编译了一下最近的 lean 大的 lede （04147dcaf5dfcf88e7f5ef0507dd16982bbc8a51），好像 Luci 已经升级到新版了？

![image](https://user-images.githubusercontent.com/24269465/230752483-3c16150e-fa09-4fd4-be18-2b389f5b58a8.png)

**Comment by SpeedPartner** [comment]
> 我编译了一下最近的 lean 大的 lede （04147dcaf5dfcf88e7f5ef0507dd16982bbc8a51），好像 Luci 已经升级到新版了？
> 
> ![image](https://user-images.githubusercontent.com/24269465/230752483-3c16150e-fa09-4fd4-be18-2b389f5b58a8.png)

LuCI的老分支也是在维护更新的,这个只是通过github自动生成的版本号,比如
**[Powered by LuCI openwrt-18.06 branch (git-23.084.35146-6d4e767)](https://github.com/openwrt/luci)**
