### ISSUE TITLE
1.73发现两个问题。

### ISSUE THREAD

**Issue by superzjg** [jerrykuku/luci-theme-argon#386]
1、luci界面输入内容不匹配数据类型时，不能用颜色定位错误点位：
如图：红框输入框错误，点击应用&保存 后，下方也有文字提示，但输入框未变色。op自带主题会将**输入框边框和字体颜色变红** 显示。

![网页捕获_1](https://user-images.githubusercontent.com/115226261/226920081-33070229-5834-4d76-b008-bc4e95631ad0.jpeg)

2、无线页面，在暗色主题时，**信号栏 底色是白色，字体也是白色，看不清**。图中红框 底色 是我自己修正过css样式文件的。
如图：修正后
![网页捕获_2](https://user-images.githubusercontent.com/115226261/226920673-6f4aed58-c4e2-4dc7-909c-d5c2eab99b8b.jpeg)

css加了最后一小段，如图：

![捕获](https://user-images.githubusercontent.com/115226261/226920885-05629ec9-6e83-4b72-a82d-da6b8481edfe.JPG)

**Comment by SpeedPartner** [comment]
![test](https://user-images.githubusercontent.com/6158590/226995021-fc299493-52bb-44fe-967e-271905f57d9a.png)
在搞了...

**Comment by jerrykuku** [comment]
楼上大哥已经更新了，我就关了哈。
