### ISSUE TITLE
v2.2.9.4 release changes package name

### ISSUE THREAD

**Issue by TheRealGramdalf** [jerrykuku/luci-theme-argon#387]
**Describe the bug**
As of the [v2.2.9.4](https://github.com/jerrykuku/luci-theme-argon/releases/tag/v2.2.9.4) release, the package name changed from `luci-theme-argon` to `luci-theme-argon-master`. This breaks scripts such as [okibcn's image builder script](https://forum.openwrt.org/t/theme-argon-main-thread/122457/2?u=therealgramdalf), and makes a lot of the information available online incorrect.

**To Reproduce**
- Download https://github.com/jerrykuku/luci-theme-argon/releases/download/v2.2.9.4/luci-theme-argon-master_2.2.9.4_all.ipk
- Extract it as an archive
- Within the archive is another archive, `control.tar.gz`. Unzip this
- Within the `control` archive, open the `control` file with any text editor.
- `luci-theme-argon-master_2.2.9.4_all.ipk/control.tar.gz/control:1` says `Package: luci-theme-argon-master`

**Expected behavior**
- Same as the process above, but `luci-theme-argon-master_2.2.9.4_all.ipk/control.tar.gz/control:1` should be `Package: luci-theme-argon`, to be consistent with the previous [v2.2.9](https://github.com/jerrykuku/luci-theme-argon/releases/tag/v2.2.9) release.

**Screenshots**
`luci-theme-argon-master_2.2.9.4_all.ipk/control.tar.gz/control` (Bugged version - v2.2.9.4)
![image](https://user-images.githubusercontent.com/79593869/227405599-b61cb3f8-fbad-4642-94df-b56017eb5d41.png)
`luci-theme-argon_2.2.9-20211016-1_all.ipk/control.tar.gz/control` (What it should be - v2.2.9)
![image](https://user-images.githubusercontent.com/79593869/227405675-47975d19-c8cf-494c-95e9-9bd6d05f1442.png)

**Openwrt (please complete the following information):**
N/A

**Desktop (please complete the following information):**
 - OS: Fedora 37 Workstation
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

I believe this may be caused by the name of the folder the git repository was cloned into being named `luci-theme-argon-master`, referring to the `master` branch here on github. Make sure the repository is cloned into the correct directory (and is named correctly).
I think it would be a good idea to release a new package that solves this problem, and remove the old entry (or mark it as buggy) from the github releases page.

**Comment by jerrykuku** [comment]
Sorry, it was a build error, I will update the correct package as soon as possible, meanwhile v2.3 has been released, you can wait for the latest version.
