### ISSUE TITLE
snapshots版本 菜单前后图标不显示

### ISSUE THREAD

**Issue by ClayMoreBoy** [jerrykuku/luci-theme-argon#39]
![image](https://user-images.githubusercontent.com/6189207/76938537-bb9a7f80-6931-11ea-9379-2a17d23a6ddd.png)

**Comment by jerrykuku** [comment]
编译的时候 关闭 minimal css

**Comment by ClayMoreBoy** [comment]
> 编译的时候 关闭 minimal css

@jerrykuku 能找的 CONFIG_LIBSODIUM_MINIMAL=y 这个关键词搜索不出关于主题的

**Comment by ClayMoreBoy** [comment]
@jerrykuku 请问怎么操作你说的

**Comment by jerrykuku** [comment]
https://github.com/jerrykuku/luci-theme-argon/issues/30#issuecomment-592263328

**Comment by ClayMoreBoy** [comment]
云编译的 终于找到你说的
# CONFIG_LUCI_CSSTIDY is not set #修复argon主题图标无法显示
