### ISSUE TITLE
Link to latest luci-app-config

### ISSUE THREAD

**Issue by alexdelprete** [jerrykuku/luci-theme-argon#392]
Hi @jerrykuku,

in the readme there's the link to the 0.8-beta version of luci-app-config, but that is not the latest.

I used 0.9-20210309 available [here](https://github.com/jerrykuku/luci-theme-argon/releases/download/v2.2.9/luci-app-argon-config_0.9-20210309_all.ipk) to enable Bing wallpapers, option not present in 0.8.

Is there a more recent version than 0.9? Could you add the latest .ipk to the releases file of luci-theme-argon please?

Thanks.

**Comment by jerrykuku** [comment]
I updated the readme file to include the latest luci-app-argon-config.

**Comment by alexdelprete** [comment]
Thanks a lot Jerry. :)
