### ISSUE TITLE
启动项--本地启动脚本  下面的框里面不能下滑

### ISSUE THREAD

**Issue by ooingram** [jerrykuku/luci-theme-argon#394]
启动项--本地启动脚本  下面的框里面不能下滑

此处为 /etc/rc.local 的内容。启动脚本插入到“exit 0”之前即可随系统启动运行。

这里面的启动项当超过（超过21行）下面的空间以后，这个框并不会像其它的框边上会有下滑框出来

只能用键盘光标来移动，非常不方便

**Comment by jerrykuku** [comment]
我来检测一下

**Comment by jerrykuku** [comment]
已经修复，可以重新编译看看

**Comment by ooingram** [comment]
👌

老竭力 ***@***.***> 于2023年4月23日周日 23:30写道：
