### ISSUE TITLE
侧栏的退出图标变成了应用商店图标

### ISSUE THREAD

**Issue by HahahahaChen** [jerrykuku/luci-theme-argon#396]
**Describe the bug**
侧栏的退出图标变成了应用商店图标

**Openwrt (please complete the following information):**
 - Versiosn: 21.02.5-openwrt
 - Theme: argon
 - Version: v2.3 master

**Comment by jerrykuku** [comment]
也发现了这个问题，会尽快修复

**Comment by jerrykuku** [comment]
已经修复，可以重新编译看看
