### ISSUE TITLE
Argon的向上箭头显示问题

### ISSUE THREAD

**Issue by R3pl4c3r** [jerrykuku/luci-theme-argon#40]
如图，无法显示
![image](https://user-images.githubusercontent.com/30682790/77500867-3fec8580-6e91-11ea-8633-8a666871aebf.png)

**Comment by jerrykuku** [comment]
已经发现此问题稍后修复

**Comment by R3pl4c3r** [comment]
> 已经发现此问题稍后修复

好的，谢谢
