### ISSUE TITLE
Tab UI 异常 LEDE 分支 V 1.8.1 

### ISSUE THREAD

**Issue by BenjaminX** [jerrykuku/luci-theme-argon#419]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Openwrt (please complete the following information):**
 - Versiosn: [e.g. 18.06-lean]
 - Theme [e.g. argon]
 - Version [e.g. 2.27]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BenjaminX** [comment]
![SCR-20230605-kdo](https://github.com/jerrykuku/luci-theme-argon/assets/612858/4f51aaa0-4609-4ce6-9e6f-07474008098a)
![SCR-20230605-kdr](https://github.com/jerrykuku/luci-theme-argon/assets/612858/5c25b4a1-cba6-434d-a05d-89f4212d562a)

**Comment by SpeedPartner** [comment]
得给均衡负载状态擦屁股单独改进了....均衡负载的状态LuCI中,其实应该使用和其他LuCI相同的规范,先使用主选项卡(这个位置如果是主选项卡,也就是`<ul class="tabs">`,那么显示是没有问题的)
如以下预期布局:
![Load_Balancing](https://github.com/jerrykuku/luci-theme-argon/assets/6158590/6731a96e-886d-4635-bba6-5c1c71bfeab6)

但它上来就用了子选项卡`<ul class="cbi-tabmenu">`,那就会导致本主题显示的是非预期的布局,加上v1.8.1改了已选中和指针悬浮时的子选项卡的背景颜色,就出现颜色重叠了....

下次更新给均衡负载状态打补丁改进子选项卡的显示位置

**Comment by BenjaminX** [comment]
Thx a lot.
