### ISSUE TITLE
登录页面，版本号挡住登录按钮

### ISSUE THREAD

**Issue by rianjskis** [jerrykuku/luci-theme-argon#421]
![1](https://github.com/jerrykuku/luci-theme-argon/assets/86937445/d70eba4d-3745-4582-a19c-2f976894c62c)
之前使用如下代码把登录界面移动到中间,版本号会在右下角，请问该做哪些修改能让版本号显示在右下角，

#<details>
#<summary>点击以显示配置</summary>
sed -i "/.login-page {/i\\
.login-container {\n\
  margin: auto;\n\
  height: 420px\!important;\n\
  min-height: 420px\!important;\n\
  left: 0;\n\
  right: 0;\n\
  bottom: 0;\n\
  margin-left: auto\!important;\n\
  border-radius: 15px;\n\
  width: 350px\!important;\n\
}\n\
.login-form {\n\
  background-color: rgba(255, 255, 255, 0)\!important;\n\
  border-radius: 15px;\n\
}\n\
.login-form .brand {\n\
  margin: 15px auto\!important;\n\
}\n\
.login-form .form-login {\n\
    padding: 10px 50px\!important;\n\
}\n\
.login-form .errorbox {\n\
  padding: 10px\!important;\n\
}\n\
.login-form .cbi-button-apply {\n\
  margin: 15px auto\!important;\n\
}\n\
.input-group {\n\
  margin-bottom: 1rem\!important;\n\
}\n\
.input-group input {\n\
  margin-bottom: 0\!important;\n\
}\n\
.ftc {\n\
  bottom: 10px!important;\n\
  right: 10px!important;\n\
}" feeds/luci/themes/luci-theme-argon/htdocs/luci-static/argon/css/cascade.css
sed -i "s/margin-left: 0rem \!important;/margin-left: auto\!important;/g" feeds/luci/themes/luci-theme-argon/htdocs/luci-static/argon/css/cascade.css

#</details>

**Comment by SpeedPartner** [comment]
建议是写js,检测窗口高度,在窗口小于预期可显示`.ftc`(也就是footer)的最低高度时,隐藏`.ftc`
目前18.06分支已经解决这个问题.主分支目前我没有其他设备,暂时帮不上忙.

你可以参考此段script:https://github.com/jerrykuku/luci-theme-argon/commit/12b3c8831ad9428f3aa082faf02b5e4fca793395

**Comment by rianjskis** [comment]
> 建议是写js,检测窗口高度,在窗口小于预期可显示 `.ftc`(也就是footer)的最低高度时,隐藏 `.ftc` 目前18.06分支已经解决这个问题.主分支目前我没有其他设备,暂时帮不上忙.
> 
> 你可以参考此段script: [12b3c88 ](https://github.com/jerrykuku/luci-theme-argon/commit/12b3c8831ad9428f3aa082faf02b5e4fca793395)

好的感谢
