### ISSUE TITLE
Error loading theme

### ISSUE THREAD

**Issue by kuroyki** [jerrykuku/luci-theme-argon#423]
![image](https://github.com/jerrykuku/luci-theme-argon/assets/102038202/627a9903-55e3-4a48-ab90-ba5868d716cc)

Netgear WAX202
OpenWrt 23.05.0-rc1
luci-theme-argon_2.3.1
How to slove it thanks!

**Comment by kuroyki** [comment]
sloved

**Comment by nassaleh** [comment]
How did you solve it?
