### ISSUE TITLE
lede下textarea应该去掉阴影

### ISSUE THREAD

**Issue by yhl452493373** [jerrykuku/luci-theme-argon#425]
lede下文本输入框没有阴影，textarea多增加了阴影，整体不协调

![网页捕获_24-6-2023_193457_192 168 2 1](https://github.com/jerrykuku/luci-theme-argon/assets/26134687/0ced43d5-7316-4092-8eb7-737fd512fd72)

**Comment by SpeedPartner** [comment]
去掉内部阴影的话,我个人认为日志相关的textarea又会比较丑...

**Comment by yhl452493373** [comment]
> 去掉内部阴影的话,我个人认为日志相关的textarea又会比较丑...

我试了下，也没有很丑吧
<img width="1149" alt="image" src="https://github.com/jerrykuku/luci-theme-argon/assets/26134687/ef219a59-04ae-4362-b9aa-4c4e80d3a040">

**Comment by yhl452493373** [comment]
我后面打包试下效果，没问题的话我提个pr
