### ISSUE TITLE
新添加后台管理分类，缺失图标

### ISSUE THREAD

**Issue by ledewrt** [jerrykuku/luci-theme-argon#43]
在后台管理添加 QOS 和 control 分类，显示无图标，麻烦大佬抽空一并修复。主题很好用。大佬给力。
![argon](https://user-images.githubusercontent.com/61609258/77840489-b0a9df80-71ba-11ea-91d7-cc007524380d.png)

**Comment by jerrykuku** [comment]
这个图标不可能无限制的添加的，因为这里如果要随意自己定制的话 根本没办法适配。

**Comment by jerrykuku** [comment]
我后面做个基础的图标吧

**Comment by ledewrt** [comment]
好的，麻烦了
