### ISSUE TITLE
Not installing 

### ISSUE THREAD

**Issue by mahbubzone** [jerrykuku/luci-theme-argon#430]
root@MZONE:/tmp/okibcn# opkg install luci-theme-argon_2.3.1_all.ipk
Unknown package 'luci-theme-argon'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency curl for luci-theme-a                                         rgon
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-theme-arg                                         on found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-theme-argon.

**Comment by SpeedPartner** [comment]
`cannot find dependency curl for luci-theme-argon`
