### ISSUE TITLE
Error with bing wallpaper set.

### ISSUE THREAD

**Issue by butinhi** [jerrykuku/luci-theme-argon#432]
Can not change wallpaper with latest lede openwrt
![Screenshot_2023-08-14-17-32-54-433_com android chrome-edit](https://github.com/jerrykuku/luci-theme-argon/assets/30124327/ef100da5-44e1-4c99-9daf-c995a0164c6f)

**Comment by SpeedPartner** [comment]
Make sure you have the latest 18.06 branch of Argon theme installed.
This issue may come from an older version of the Argon theme that comes with the firmware itself.

**Comment by butinhi** [comment]
> Make sure you have the latest 18.06 branch of Argon theme installed. This issue may come from an older version of the Argon theme that comes with the firmware itself.

I am on this version
[Powered by LuCI Master (git-23.222.42836-72f2f76)](https://github.com/openwrt/luci) / [ArgonTheme v1.8.3](https://github.com/jerrykuku/luci-theme-argon) / OpenWrt R23.7.7

**Comment by SpeedPartner** [comment]
Does your firmware itself contain an older version of the Argon theme?
**This issue may come from an older version of the Argon theme that comes with the firmware itself.**
You can also try `rm -rf /usr/libexec/argon/online_wallpaper`, then reinstall Argon theme v1.8.3

**Comment by butinhi** [comment]
> Does your firmware itself contain an older version of the Argon theme? **This issue may come from an older version of the Argon theme that comes with the firmware itself.** You can also try `rm -rf /usr/libexec/argon/online_wallpaper`, then reinstall Argon theme v1.8.3

I am on latest lede firmware. I removed oder argon and git latest argon to build firmware for myself

**Comment by SpeedPartner** [comment]
Sorry, this problem cannot be reproduced;
Suggest you try installing the ipk from [Releases](https://github.com/jerrykuku/luci-theme-argon/releases/tag/v1.8.3) .

**Comment by SpeedPartner** [comment]
I'm not sure exactly how you cloned the Argon theme source code.
Please confirm whether the file permission of [online_wallpaper](https://github.com/jerrykuku/luci-theme-argon/blob/18.06/root/usr/libexec/argon/online_wallpaper) is 0755;
Yep, it's supposed to be an ”Executable File“.

**Comment by butinhi** [comment]
> I'm not sure exactly how you cloned the Argon theme source code. Please confirm whether the file permission of [online_wallpaper](https://github.com/jerrykuku/luci-theme-argon/blob/18.06/root/usr/libexec/argon/online_wallpaper) is 0755; Yep, it's supposed to be an ”Executable File“.
I cloned to get luci-theme-argon folder then deleta luci-theme-argon from lede source then
./scripts/feeds update -a
./scripts/feeds install -a

And build lede firmware

**Comment by SpeedPartner** [comment]
Cloned folder? How did you do it?
Did you download the ZIP archive?

**Comment by butinhi** [comment]
> Cloned folder? How did you do it? Did you download the ZIP archive?

I used git clone to download luci-theme-argon to my pc

**Comment by butinhi** [comment]
> Please use the `cd` command to enter the cloned Argon theme source directory in the LEDE source directory， then use the command `ls -l /usr/libexec/argon/online_wallpaper` to check this file permission; **It's supposed to be an ”Executable File“, permissions are: -rwxr-xr-x (0755)**
Do you use telegram? I want to ask you something.

**Comment by SpeedPartner** [comment]
It may be that your way of cloned the source code of the Argon theme is incorrect.

What I know: 
1. Download the ZIP archive will lose file permissions; 
2. Using the SVN download command will also lose file permissions; 
3. Copy the source code of the Argon theme from Windows to WSL, would also result in the same situation.

**Comment by butinhi** [comment]
> It may be that your way of cloned the source code of the Argon theme is incorrect.
> 
> What I know:
> 
> 1. Download the ZIP archive will lose file permissions;
> 2. Using the SVN download command will also lose file permissions;
> 3. Copy the source code of the Argon theme from Windows to WSL, would also result in the same situation.
How to clone it without problem?

**Comment by butinhi** [comment]
Use this right?
cd lede/package/lean
rm -rf luci-theme-argon
git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git luci-theme-argon
make menuconfig #choose LUCI->Theme->Luci-theme-argon
make -j1 V=s

**Comment by SpeedPartner** [comment]
Yep，Just follow the instruction - README.md
**git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git luci-theme-argon**

**Comment by butinhi** [comment]
Ok I will try it now

**Comment by SpeedPartner** [comment]
Confirm that the file permissions are correct before continuing to compile the firmware.

**Comment by butinhi** [comment]
Working bro!

[url=https://ibb.co/Wz4S5FM][img]https://i.ibb.co/Wz4S5FM/A-nh-chu-p-ma-n-hi-nh-2023-08-16-234640.png[/img][/url]

**Comment by SpeedPartner** [comment]
🎉
