### ISSUE TITLE
装alist时，把默认的服务栏里，变成网络存储

### ISSUE THREAD

**Issue by chancat87** [jerrykuku/luci-theme-argon#433]
ArgonTheme v1.8.3
大雕源的固件，安装alist之后，把原"服务"栏变成了网络存储

![1000074110.jpg](https://pic1.58cdn.com.cn/nowater/webim/big/n_v2dcb15f273977449cb85db1f0b746e6af.jpg)

**Comment by SpeedPartner** [comment]
请确认安装alist之后,其它主题,或者默认主题是否也会导致该问题出现.

**Comment by chancat87** [comment]
> 请确认安装 alist 之后，其他主题，默认或者主题是否出现导致该问题的出现。

已经常识了，确实，全部都有这个问题。

**Comment by SpeedPartner** [comment]
那么就不属于本主题的问题，请核实获取alist的渠道是否是第三方经过修改；因为我也使用，没出现该问题.

**Comment by chancat87** [comment]
> 那么就不属于本主题的问题，请核实获取alist的渠道是否是第三方经过修改；因为我也使用，没出现该问题.

周末研究出来了，发现luci-app-alist的问题，用alits项目页curl方式安装的无问题。这里做个记录
