### ISSUE TITLE
No change wallpaper.

### ISSUE THREAD

**Issue by butinhi** [jerrykuku/luci-theme-argon#434]
I set Wallpaper Source to Bing wallpapers from Argon config but only change 1 wallpaper when I set. No change for 2 days
LedeOpenwrt 23.7.7
Argon 1.8.3

**Comment by SpeedPartner** [comment]
Still no changed?

**Comment by butinhi** [comment]
> Still no changed?

It changed but for along time. I do not know how along it will change?

**Comment by SpeedPartner** [comment]
Update online wallpaper every 12 hours;
If Bing's daily wallpaper is not updated, it will be postponed to the next time.

**Comment by SpeedPartner** [comment]
Any news?

**Comment by butinhi** [comment]
> Any news?

Changed. But why can not use 2.3.1 version for lede?

**Comment by SpeedPartner** [comment]
## Branch Introduction

There are currently two main branches that are adapted to different versions of the **OpenWrt** source code.  
The table below will provide a detailed introduction:

| Branch | Version | Description                        | Matching source                                           |
| ------ | ------- | ---------------------------------- | --------------------------------------------------------- |
| master | v2.x.x  | Support the latest version of LuCI | [Official OpenWrt][official] • [ImmortalWrt][immortalwrt] |
| 18.06  | v1.x.x  | Support the 18.06 version of LuCI  | [Lean's LEDE][lede]                                         |

Related to version compatibility with LuCI
