### ISSUE TITLE
黑色模式下，nftables状态页面的链名与背景色相同，不可阅读

### ISSUE THREAD

**Issue by john5du** [jerrykuku/luci-theme-argon#437]
**Describe the bug**
Per title

**To Reproduce**
1. Go to '状态'
2. Click on '防火墙'

**Screenshots**
![image](https://github.com/jerrykuku/luci-theme-argon/assets/45614150/b7347992-12cf-4804-8d31-d9ef11460964)
![image](https://github.com/jerrykuku/luci-theme-argon/assets/45614150/5fb1a795-ce7a-4866-8db4-b7123bf87b71)

**Openwrt (please complete the following information):**
 - Versiosn: 23.05-rc2 firewall4
 - Theme:  argon
 - Version: 2.3.1

**Desktop (please complete the following information):**
 - OS: windows
 - Browser  chrome
 - Version 116

**Comment by muink** [comment]
Dark Reader save you life

**Comment by yhl452493373** [comment]
已处理，等更新

**Comment by john5du** [comment]
![image](https://github.com/jerrykuku/luci-theme-argon/assets/45614150/94744bbf-d165-4647-b8f8-49237b8d0c47)
Fixd. thanks
