### ISSUE TITLE
18.06 登录页面无背景图

### ISSUE THREAD

**Issue by ChrisYH20** [jerrykuku/luci-theme-argon#438]
登录页面无背景图，登录后一切正常，尝试用argon-config设置背景过但无效
![image](https://github.com/jerrykuku/luci-theme-argon/assets/140259582/d563d56b-8f28-4bbf-b879-5e1b14346ae1)

**Comment by SpeedPartner** [comment]
热知识,自述文件有简体中文;
请先弄清楚你这个QWRT的LuCI版本是18.06,还是21.02+

**Comment by ChrisYH20** [comment]
luci版本是18.06，两个版本的argon我都尝试过但都一样，是否和luci-base有关呢?

**Comment by SpeedPartner** [comment]
.....之前没看你issue标题
请更新主题版本,此v1.7.3版本还是去年的,壁纸更新逻辑也还是以前的.

**Comment by ChrisYH20** [comment]
![image](https://github.com/jerrykuku/luci-theme-argon/assets/140259582/958d53af-0795-45c1-8659-3e001a76f5f5)
QWQ

**Comment by Kimaru-bili** [comment]
(虽然最新的是1.8.3)
我是最新的有相同问题，已经在[#354](https://github.com/jerrykuku/luci-theme-argon/issues/354) 提过了(建议关闭

**Comment by SpeedPartner** [comment]
> (虽然最新的是1.8.3) 我是最新的有相同问题，已经在[#354](https://github.com/jerrykuku/luci-theme-argon/issues/354) 提过了(建议关闭

#354 是LuCI主线分支的issue,我目前没空维护,你在此issue下继续讨论即可,你们两位的情况应该是一样的

**Comment by Kimaru-bili** [comment]
> > (虽然最新的是1.8.3) 我是最新的有相同问题，已经在[#354](https://github.com/jerrykuku/luci-theme-argon/issues/354) 提过了(建议关闭
> 
> #354 是LuCI主线分支的issue,我目前没空维护,你在此issue下继续讨论即可,你们两位的情况应该是一样的

行 麻烦了(

**Comment by SpeedPartner** [comment]
我这边尝试LEDE最新源码,x86云编译,主题登录界面正常

**Comment by Kimaru-bili** [comment]
> 我这边尝试LEDE最新源码,x86云编译固件,主题登录界面正常

我是ARM64的(悲 跟架构有关系么？

**Comment by SpeedPartner** [comment]
你们俩哪位愿意协助我远程看下你们的编译操作方法,也也很好奇这啥会出现这个问题...

**Comment by Kimaru-bili** [comment]
> > 我这边尝试LEDE最新源码,x86云编译固件,主题登录界面正常
> 
> 我是ARM64的(悲 跟架构有关系么？



> 你们俩哪位愿意协助我远程看下你们的编译操作方法,我也很好奇这啥会出现这个问题...

我是WSL2编译的 就按照LEDE介绍来的(emmm电脑暂时在干别的 )

**Comment by ChrisYH20** [comment]
我是用的大雕的固件，不是自己编译的（QAQ）

**Comment by SpeedPartner** [comment]
> 我是用的大雕的固件，不是自己编译的（QAQ）

你原来v1.7.3的主题是固件自带的,还是哪里获取后安装的?

**Comment by SpeedPartner** [comment]
> 我是WSL2编译的 就按照LEDE介绍来的(emmm电脑暂时在干别的 )

问下你是不是把主题源码从Windows复制到WSL2了?还是直接按自述文件克隆的?

**Comment by ChrisYH20** [comment]
目前的luci-base版本是21.02中的，我尝试过将luci-base重新安装至[18.06-k5.4-SNAPSHOT]中的版本，之后登录界面恢复正常，但是无线状态显示不太正常，我就又退回固件最初的版本了

**Comment by ChrisYH20** [comment]
> > 我是用的大雕的固件，不是自己编译的（QAQ）
> 
> 你原来v1.7.3的主题是固件自带的,还是哪里获取后安装的?

v1.7.3是之前安装的luci-theme-argonv3

**Comment by Kimaru-bili** [comment]
> > 我是WSL2编译的 就按照LEDE介绍来的(emmm电脑暂时在干别的 )
> 
> 问下你是不是把主题源码从Windows复制到WSL2了?还是直接按自述文件在WSL2中克隆的?

克隆的 先是把feeds里的主题删了然后克隆的这个到package里

**Comment by SpeedPartner** [comment]
> 克隆的 先是把feeds里的主题删了然后克隆的这个到package里

你要不先试试`make clean`后全新编译看看

**Comment by Kimaru-bili** [comment]
> > 克隆的 先是把feeds里的主题删了然后克隆的这个到package里
> 
> 你要不先试试`make clean`后全新编译看看

那个 有没有可能是内核问题(我为了兼容Docker用了5.15.128版本的内核emmm

**Comment by SpeedPartner** [comment]
> v1.7.3是之前安装的luci-theme-argonv3

要不你试试重刷固件或者恢复出厂设置,之后再安装本主题的v1.8.5 release 试下;不排除是你之前安装的旧版本主题冲突导致.
另外,QWRT是闭源的,还是不行的话我也没办法版了,没源码不好诊断.

**Comment by SpeedPartner** [comment]
> 那个 有没有可能是内核问题(我为了兼容Docker用了5.15.128版本的内核emmm

理论上应该不会,但是换内核编译必须要先make clean

**Comment by Kimaru-bili** [comment]
> > 那个 有没有可能是内核问题(我为了兼容Docker用了5.15.128版本的内核emmm
> 
> 理论上应该不会,但是换内核编译必须要先`make clean`

那我可以把现在的这个卸载再装Ipk可行么(emm docker都部署完了重新刷固件好难顶 不行的话就这样吧 也不是不能用 有空了再重新刷一下哈哈哈

**Comment by SpeedPartner** [comment]
> 那我可以把现在的这个卸载再装Ipk可行么(emm docker都部署完了重新刷固件好难顶 不行的话就这样吧 也不是不能用 有空了再重新刷一下哈哈哈

卸载软件包,比如本主题,实际还会有残留文件,应该是不行的,你可以尝试下

**Comment by SpeedPartner** [comment]
看下是否会有其他人反馈🤨

**Comment by SpeedPartner** [comment]
长时间没有其他人反馈或讨论相同情况, @ChrisYH20  请问是否已经解决?
