### ISSUE TITLE
登录界面没有用户名

### ISSUE THREAD

**Issue by wangweiwei104** [jerrykuku/luci-theme-argon#44]
如图所示![image](https://user-images.githubusercontent.com/45837773/77982259-7bc69580-733e-11ea-8e3c-aee6316f7f2a.png)

**Comment by jerrykuku** [comment]
18.06的设计 就是没有用户名 默认root

**Comment by wangweiwei104** [comment]
> 18.06版的设计 就是没有用户名 默认root （隐藏了 没有显示）

请问现在lean的代码是不是可以用最新的argon主题，不用18.06版本了？

**Comment by jerrykuku** [comment]
不能

**Comment by wangweiwei104** [comment]
> 不能

请问怎样才能把用户名显示出来？因为某些情况下由于浏览器自动表单填写的缘故，导致登录的用户名错误！
