### ISSUE TITLE
反馈个小问题

### ISSUE THREAD

**Issue by ssm1588** [jerrykuku/luci-theme-argon#440]
luci版本 18.06
argon主题版本 v1.8.3
用手机端登录路由器后台，发现网络状态中的ipv4和ipv6没有对齐，看起来不协调，如图
![Screenshot_20230902_171557](https://github.com/jerrykuku/luci-theme-argon/assets/142860496/96c32c40-4d82-4c7b-812c-97bf5bfa6412)
请修复下

**Comment by SpeedPartner** [comment]
https://github.com/jerrykuku/luci-theme-argon/commit/cbad1c9f998401d7cc4664690c3f23e80d2c1ac2
