### ISSUE TITLE
又发现一个小问题

### ISSUE THREAD

**Issue by ssm1588** [jerrykuku/luci-theme-argon#441]
18.06 luci
argon主题版本v1.8.3
手机端主题>passwall>节点列表>通过链接添加节点的输入框太大了，已经溢出屏幕，如下图
![Screenshot_20230902_195726](https://github.com/jerrykuku/luci-theme-argon/assets/142860496/aa82a29a-cb90-43aa-99c9-ae3052f983c9)

**Comment by SpeedPartner** [comment]
摆烂~
