### ISSUE TITLE
immortalwrt登录页中文翻译会部分失效

### ISSUE THREAD

**Issue by liyuhaolol** [jerrykuku/luci-theme-argon#442]
我是9月9日进行的编译，我看immortalwrt里的luci-theme-argon代码是3个月前，对比本项目看来应该是最新的。登录页面的“登录”文本，会显示为“Login”，重复编译了几次都是如此，因为是明显的文本问题，所以暂时懒得截图，希望能得到修复

**Comment by ArronPlus** [comment]
feed/luci/themes/luci-theme-argon/luasrc/view/themes/argon/sysauth.html
将154行的Login改为Log in
