### ISSUE TITLE
编译固件时报错，目标模式不含有“%”。 停止

### ISSUE THREAD

**Issue by gyssi007** [jerrykuku/luci-theme-argon#445]
/home/f/immortalwrtARM/feeds/jerrykuku.tmp/info/.files-packageinfo.mk:1: *** 目标模式不含有“%”。 停止。

发生这样的问题，如何解决

**Comment by SpeedPartner** [comment]
不清楚这种情况的出现的具体原因,建议`make clean`后全新编译试下

**Comment by SpeedPartner** [comment]
你是不是将本主题添加到feeds.conf.default了?
feeds.conf.default只能添加包合集的源,无法添加单独的包的源,推荐按照本项目自述文件操作,编译或者安装本主题
