### ISSUE TITLE
如何调整 登录框的位置和大小 就是输入密码的 位置

### ISSUE THREAD

**Issue by gyssi007** [jerrykuku/luci-theme-argon#447]
想改变一下完整 因为换的背景图片需要统一下，所以需要移动一下输入框和调整大小

![捕获](https://github.com/jerrykuku/luci-theme-argon/assets/78358246/d6df76f6-68e5-4b91-aeb6-84bb872ef65c)

**Comment by SpeedPartner** [comment]
https://github.com/jerrykuku/luci-theme-argon/issues/134#issuecomment-1728621715

**Comment by gyssi007** [comment]
> [第134章（评论）](https://github.com/jerrykuku/luci-theme-argon/issues/134#issuecomment-1728621715)

把这个能不能变成直接透明层，不要毛玻璃效果
