### ISSUE TITLE
登录界面底部的属性文字，如何去掉

### ISSUE THREAD

**Issue by gyssi007** [jerrykuku/luci-theme-argon#448]
![IMG_20231005_180721](https://github.com/jerrykuku/luci-theme-argon/assets/78358246/4ccfc111-b06a-4d1c-acc6-fd90e14f7a82)
如何去掉，或者隐藏，太影响美观了

**Comment by gyssi007** [comment]
找到了  修改

.login-page .login-container footer .ftc {
  position: absolute;
  bottom: 999px;
  width: 100%;

**Comment by SpeedPartner** [comment]
那么就关闭此issue了,此类问题请使用Debug(F12)来查找网页元素
