### ISSUE TITLE
hc5962  安装报错：

### ISSUE THREAD

**Issue by xiangfeigao** [jerrykuku/luci-theme-argon#449]
**Describe the bug**
hc5962  安装报错：
Configuring luci-theme-argon.
sed: /usr/lib/lua/luci/dispatcher.lua: No such file or directory
sed: /usr/lib/lua/luci/dispatcher.lua: No such file or directory
sed: /usr/lib/lua/luci/dispatcher.lua: No such file or directory
sed: /usr/lib/lua/luci/dispatcher.lua: No such file or directory

**Openwrt (please complete the following information):**

型号 | HiWiFi HC5962
架构 | MediaTek MT7621 ver:1 eco:3
目标平台 | ramips/mt7621
固件版本 | OpenWrt SNAPSHOT r24111-66f6c20e45

**Comment by SpeedPartner** [comment]
你安装的Argon主题版本号呢?

**Comment by SpeedPartner** [comment]
7天内未回复,将视为无效issue并关闭

**Comment by xiangfeigao** [comment]
然后我通过编译倒是安装上了，但运行界面不完整，没有菜单项。版本是20231019凌晨clone的主题git

**Comment by SpeedPartner** [comment]
> 然后我通过编译倒是安装上了，但运行界面不完整，没有菜单项。版本是20231019凌晨clone的主题git
你之前提供的固件版本,我查到是编译自官方OpenWrt主线;
请确认已跟随Readme编译流程操作
```
cd openwrt/package
git clone https://github.com/jerrykuku/luci-theme-argon.git
make menuconfig #choose LUCI->Theme->Luci-theme-argon
make -j1 V=s
```
