### ISSUE TITLE
Snapshot版字体显示问题

### ISSUE THREAD

**Issue by garypang13** [jerrykuku/luci-theme-argon#45]
![2020-4-1 12-47-35](https://user-images.githubusercontent.com/48883331/78100379-3629cb80-7417-11ea-93b9-5f9515cfeccd.png)
所有设置了font-size-adjust: 属性的字体都这样.

**Comment by jerrykuku** [comment]
是不是 高分屏？

**Comment by garypang13** [comment]
> 是不是 高分屏？

是的哈.
