### ISSUE TITLE
斐讯 k2 (phicomm k2) mt7620 安装 (install) luci-theme-argon 报错(error)

### ISSUE THREAD

**Issue by GrootLiu** [jerrykuku/luci-theme-argon#453]
after installed argon on  phicomm k2, i miss a bug
i cant open the web-ui
![09a604f3f432f3a7eba6ab7323f54071f94362cb](https://github.com/jerrykuku/luci-theme-argon/assets/55238899/08bd339a-cf84-4da3-bad1-c178f1a7e345)
斐讯 k2 安装 argon 后进不去 web 页面

**Comment by GrootLiu** [comment]
opkg install luci-compat 
可以解决

**Comment by SpeedPartner** [comment]
你并没有提供有效的反馈,未说明OpenWrt的版本,也没有Argon主题的版本;
初步怀疑你是安装错Argon主题的分支版本了.
