### ISSUE TITLE
Lean openwrt 1.5.1 无线[移除]错位

### ISSUE THREAD

**Issue by DongfeiSay** [jerrykuku/luci-theme-argon#46]
![捕获](https://user-images.githubusercontent.com/49421020/78265341-e2ae9f00-7536-11ea-8684-0cec88bc93a2.JPG)

**Comment by jerrykuku** [comment]
ok 明天修复

**Comment by DongfeiSay** [comment]
> 好的明天修复

另外还有带宽监控[显示]里的第一二个主机显示是有问题的
![1](https://user-images.githubusercontent.com/49421020/78267127-3326fc00-7539-11ea-8238-fc2b56b280b9.JPG)
![2](https://user-images.githubusercontent.com/49421020/78267157-3ae6a080-7539-11ea-8cc1-938c826ac676.JPG)
第三个开始正常，不过右边那个x点击是没反应的
![3](https://user-images.githubusercontent.com/49421020/78267257-56ea4200-7539-11ea-84f0-ec7c80b593be.JPG)

自动刷新的小问题，鼠标放上去是显示文本选择的光标的，正常应该是显示为点击光标？

**Comment by lloyd18** [comment]
> > 好的明天修复
> 
> 另外还有带宽监控[显示]里的第一二个主机显示是有问题的
> ![1](https://user-images.githubusercontent.com/49421020/78267127-3326fc00-7539-11ea-8238-fc2b56b280b9.JPG)
> ![2](https://user-images.githubusercontent.com/49421020/78267157-3ae6a080-7539-11ea-8cc1-938c826ac676.JPG)
> 第三个开始正常，不过右边那个x点击是没反应的
> ![3](https://user-images.githubusercontent.com/49421020/78267257-56ea4200-7539-11ea-84f0-ec7c80b593be.JPG)
> 
> 自动刷新的小问题，鼠标放上去是显示文本选择的光标，正常应该是显示为点击光标？
> ![4](https://user-images.githubusercontent.com/49421020/78268246-82b9f780-753a-11ea-98a6-79a3f00bb4f1.JPG)

这个问题希望修复一下，一个月前提过了https://github.com/jerrykuku/luci-theme-argon/issues/38#issue-580538921

**Comment by jerrykuku** [comment]
已经全部修复

**Comment by lloyd18** [comment]
> 已经全部修复
哥，docker图标依然无法显示
![微信图片_20200704133750](https://user-images.githubusercontent.com/10294460/86505798-ab80b000-bdfb-11ea-9b67-3a0786346ba6.png)
