### ISSUE TITLE
暗色模式未适配网络诊断中的回显区域

### ISSUE THREAD

**Issue by LiuJiewenTT** [jerrykuku/luci-theme-argon#463]
**Describe the bug**
暗色模式未适配网络诊断中的回显区域，全白，刺眼。

**To Reproduce**
1. 转到“网络”
2. 转到“诊断”
3. 看到右侧回显区域白色背景

**Expected behavior**
改成暗色，不刺眼。

**Screenshots**
![image](https://github.com/jerrykuku/luci-theme-argon/assets/43092274/a584dc1b-4e3a-475a-8286-f3ac6fa036c6)

**Openwrt (please complete the following information):**
 - Versiosn: 23.05.2 r23630-842932a63d
 - Theme: ArgonTheme 
 - Version: 2.3.1 

**Additional context**

**Comment by yhl452493373** [comment]
#465 这个问题我处理了。你着急的话直接在我仓库把 `/htdocs/luci-static/argon/css`下的文件下下来，然后传到openwrt的`/www/luci-static/argon/css/`下面就行
