### ISSUE TITLE
luci-app-commands出现排版问题

### ISSUE THREAD

**Issue by Fddh2012** [jerrykuku/luci-theme-argon#464]
目标平台：x86/64
固件版本：ImmortalWrt 23.05.1 r27304-31bc47589e / LuCI openwrt-23.05 branch git-23.323.25576-ef326c3
内核版本：5.15.137
主题版本：ArgonTheme v2.3.1

兼容对象：luci-app-commands

复现：安装luci-app-commands - 系统 - 自定义命令 - 配置 - [新建任意命令] - 概览

![image](https://github.com/jerrykuku/luci-theme-argon/assets/58475641/5f852f4a-e948-40fd-a8b5-4ff8b6b81522)

**Comment by muink** [comment]
Same issue on 23.05
