### ISSUE TITLE
luci-app-commands 自定义命令UI错位

### ISSUE THREAD

**Issue by yu1t** [jerrykuku/luci-theme-argon#474]
OpenWrt 23.05.2

![image](https://github.com/jerrykuku/luci-theme-argon/assets/21243409/6d3be053-5e61-4229-972d-7f6b6968ca04)

**Comment by castillofrancodamian** [comment]
Mine 😂

![292700975-aa64e1d7-fc71-4508-855c-6a0f26c6a6ed](https://github.com/jerrykuku/luci-theme-argon/assets/47670442/302024bf-e45a-40db-8fad-00bad76156a3)
