### ISSUE TITLE
Unable to compile 'themes/argon/header' as Lua template: Unable to load Lua runtime

### ISSUE THREAD

**Issue by Mile-Lile** [jerrykuku/luci-theme-argon#478]
**Describe the bug**
I followed instruction from some site like this:
`opkg install luci-compat
wget --no-check-certificate https://github.com/jerrykuku/luci-theme-argon/releases/download/v2.2.5/luci-theme-argon_2.2.5-20200914_all.ipk
opkg install luci-theme-argon*.ipk`

but after installing theme I see this error:
![Screenshot_select-area_20240110195456](https://github.com/jerrykuku/luci-theme-argon/assets/12752816/7beadf9f-10bc-42be-aac0-dd5831804e88)

**Openwrt (please complete the following information):**
 - Versiosn: [	OpenWrt SNAPSHOT r24733-c1ad78318c / LuCI Master git-23.357.52396-5355b7b]
 - Theme [argon]
 - Version [2.27]

**Desktop (please complete the following information):**
 - OS: [deepin linux - 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC]
 - Browser [Chrome Version 119.0.6045.199 (Official Build) (64-bit)]

**Comment by SpeedPartner** [comment]
Why don't you take a look at the instruction([README](https://github.com/jerrykuku/luci-theme-argon#install-for-openwrt-official-snapshots-and-immortalwrt)) of this repository?

**Comment by Mile-Lile** [comment]
@SpeedPartner Hey, thank you very much. I didn't know what where to look :) I managed at the end with your help. Theme looks wonderfull... Th
![Screenshot_select-area_20240113070636](https://github.com/jerrykuku/luci-theme-argon/assets/12752816/b32854c2-aa9c-4f8c-be17-a23a1eee024c)
ank you
