### ISSUE TITLE
你好，使用argon后，ui语言展示问题

### ISSUE THREAD

**Issue by wwwxtcom** [jerrykuku/luci-theme-argon#48]
你好，我已经安装了，中文包，在官方ui的情况下，中文没有问题，但是切换到argon时，有一大半的页面，显示的是英文，请问你知道这是啥原因导致的嘛？谢谢

**Comment by jerrykuku** [comment]
麻烦告知下 argon的版本 如果能有截图最好

**Comment by wwwxtcom** [comment]
argon是最新的包：luci-theme-argon_1.5.1-01-20200331_all.ipk 
openwrt：19.07.1和19.07.2，前面用的19.07.2 以为时版本问题，就用你指定的19.07.1
图三：modal问题是样式问题，也不知道为啥会出现这样的情况，所有的modal样式都丢失了，自己写样式修复了modal问题，还有部分按钮的样式也没了，这些小细节我就没一一修复了，也不影响
![image](https://user-images.githubusercontent.com/48472546/78531588-4aefd000-7818-11ea-9eef-81b96b90f016.png)
![image](https://user-images.githubusercontent.com/48472546/78531618-5a6f1900-7818-11ea-93a2-3e451558bec2.png)
![image](https://user-images.githubusercontent.com/48472546/78531773-a91cb300-7818-11ea-816b-0d8b6aeefefe.png)

**Comment by jerrykuku** [comment]
了解 最近一直很忙 没有时间跟进官方主题。1.5.1是给lean 的版本适配的

**Comment by wwwxtcom** [comment]
感谢你的回复，我更换2.X版本，问题的到解决，再次感谢你！
