### ISSUE TITLE
使用最新lede源码编译的redmi ax6固件主题无法使用，显示严重错误

### ISSUE THREAD

**Issue by xhj234** [jerrykuku/luci-theme-argon#487]
系统版本：lede r24.2
6.1内核
![op](https://github.com/jerrykuku/luci-theme-argon/assets/96654582/2adcb4ab-0ad7-4c8d-b2ef-a1b424004141)
这个装上都无法操作了，选项全没了

**Comment by SpeedPartner** [comment]
LEDE固件你编译错主题版本了,请切换到18.06分支的主题源码进行编译

**Comment by fynhnt** [comment]
> LEDE固件你编译错主题版本了,请切换到18.06分支的主题源码进行编译

请问大佬怎么切换主题源码？修改哪个文件或使用什么命令？

**Comment by xhj234** [comment]
> 请问大佬怎么切换主题源码？修改哪个文件或使用什么命令？

git clone -b 18.06

**Comment by SpeedPartner** [comment]
> LEDE固件你编译错主题版本了,请切换到18.06分支的主题源码进行编译

请查看本项目issues中的置顶issue

**Comment by fynhnt** [comment]
> > LEDE固件你编译错主题版本了,请切换到18.06分支的主题源码进行编译
> 
> 请查看本项目issues中的置顶issue

谢谢老大提点，那以后二次编译是不是每次 feeds update 后都需要执行置顶命令？

**Comment by SpeedPartner** [comment]
> 谢谢老大提点，那以后二次编译是不是每次 feeds update 后都需要执行置顶命令？

置顶命令?你在说什么?...

**Comment by fynhnt** [comment]
> > 谢谢老大提点，那以后二次编译是不是每次 feeds update 后都需要执行置顶命令？
> 
> 置顶命令?你在说什么?...

就是你置顶中的切换18.06分支主题命令，已经验证过只需执行一次，二次编译是不需要的。

**Comment by SpeedPartner** [comment]
> 就是你置顶中的切换18.06分支主题命令，已经验证过只需执行一次，二次编译是不需要的。

除非本主题项目18.06分支有更新,那么再重新执行一遍`git clone`下载最新源码,或"git pull"命令同步最新源码即可.
其他无需再重复操作.
