### ISSUE TITLE
LEDE 18.06分支 在“实时流量监测”luci中 不会显示“自动刷新间隔”选定的时间，如图：

### ISSUE THREAD

**Issue by Fly432** [jerrykuku/luci-theme-argon#489]
![1](https://github.com/jerrykuku/luci-theme-argon/assets/63394186/b75a659d-1cea-4570-8bb2-8a12f5fe42a5)
![2](https://github.com/jerrykuku/luci-theme-argon/assets/63394186/31e25e16-dd11-4aaa-9360-4b0bd962b74f)

**Comment by SpeedPartner** [comment]
又得打补丁了...后续抽空再修
