### ISSUE TITLE
luci-theme-argon v2.01 小图标不显示(显示乱码)

### ISSUE THREAD

**Issue by aa1622296203** [jerrykuku/luci-theme-argon#49]
在openWrt源码中编译了luci-theme-argon v2.01 , openWrt源码版本版本为v19.07.2显示效果如下:

谷歌浏览器(每个标题的左侧显示有问题):

![luci-theme-argon1](https://user-images.githubusercontent.com/9100950/78647560-59f48200-78ed-11ea-9ed6-a4b52e9c9c8b.png)
![luci-theme-argon2](https://user-images.githubusercontent.com/9100950/78647566-5bbe4580-78ed-11ea-8757-a8d50c68137d.png)

火狐浏览器(每个标题的左侧有乱码):
![luci-theme-argon3](https://user-images.githubusercontent.com/9100950/78647986-e7d06d00-78ed-11ea-87fc-275fb1b69e09.png)
![luci-theme-argon4](https://user-images.githubusercontent.com/9100950/78647988-e9019a00-78ed-11ea-8ddb-02609cf48139.png)

**Comment by jerrykuku** [comment]
https://github.com/jerrykuku/luci-theme-argon/issues/39#issuecomment-600524731
参考这里

**Comment by aa1622296203** [comment]
@jerrykuku 非常感谢,问题解决, 大佬辛苦了, 奥利给!!!
