### ISSUE TITLE
LEDE版自己编译的根本无法使用，只有这里下载的才能用

### ISSUE THREAD

**Issue by dragon888888888888** [jerrykuku/luci-theme-argon#493]
如果不按这里的方法拉取代码，直接在LUCI中选择这个主题，也可以用，丢失图标等
在这里拉的源码一样缺少CSS样式，和在LUCI中选择的没什么区别
直接这里下载IPK包安装一切正常
不管是LUCI里选择还是源码拉取的，都不能做为默认主题
如果修改源码做为默认主题并不选其它主题，编译后无后台页面
如果是LUCI里选择或拉取源码后编译并保留其它主题的情况下，编译的的固件后台默认是其它主题，修改成这个主题后一样无很多ICON图标丢失。
ARM V8

**Comment by SpeedPartner** [comment]
请查看本项目置顶isuue,如何删除LEDE内置的Argon主题旧版本源码后,重新拉取最新18.06分支的主题源码,并将本主题编译为默认.
如还需要18.06分支,最新版本的主题设置插件编译进入固件,请查看主题设置项目源码[README](https://github.com/jerrykuku/luci-app-argon-config?tab=readme-ov-file#build-for-leans-lede-project)

**Comment by dragon888888888888** [comment]
> isuue
cd lede/package/lean
rm -rf luci-app-argon-config # if have
git clone -b 18.06 https://github.com/jerrykuku/luci-app-argon-config.git luci-app-argon-config
就是这样拉取的源码，会丢失CSS样式，主要是各种图片和图标都没有造成的

**Comment by dragon888888888888** [comment]
> 请查看本项目置顶isuue,如何删除LEDE内置的Argon主题旧版本源码后,重新拉取最新18.06分支的主题源码,并将本主题编译为默认. 如还需要18.06分支,最新版本的主题设置插件编译进入固件,请查看主题设置项目源码[README](https://github.com/jerrykuku/luci-app-argon-config?tab=readme-ov-file#build-for-leans-lede-project)

删除自带的后重拉源码已解决
