### ISSUE TITLE
登录界面的版本号显示是否可以关掉，很影响界面美观

### ISSUE THREAD

**Issue by pgwstd** [jerrykuku/luci-theme-argon#495]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Openwrt (please complete the following information):**
 - Versiosn: [e.g. 18.06-lean]
 - Theme [e.g. argon]
 - Version [e.g. 2.27]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SpeedPartner** [comment]
目前不可以,你是一个提出此需求的...
