### ISSUE TITLE
登陆界面背景

### ISSUE THREAD

**Issue by GHSY123** [jerrykuku/luci-theme-argon#5]
登录界面的背景图片在哪找的？如何添加？

**Comment by jerrykuku** [comment]
背景图片 来自于 无版权图片社区  https://unsplash.com/

**Comment by GHSY123** [comment]
> 背景图片 来自于 无版权图片社区 https://unsplash.com/

大佬，还有另外一个问题就是如何把图片变为web登录管理页面的背景？有教程吗？

**Comment by GHSY123** [comment]
> 背景图片 来自于 无版权图片社区 https://unsplash.com/

主题有个小问题，在酸酸乳界面应用配置时，文字显示不完全。

**Comment by admi-229133** [comment]
一个主题2.几MB 小一点的路由完全装不上 建议把图片删除或者固定一张图片即可！

**Comment by jerrykuku** [comment]
自己修改一下即可luasrc/view/themes/argon/header.htm 第273行  <div class="login-bg" style="background-image:url(<%=media%>/img/bg<%=math.random(1,4)%>.jpg)"></div>   (1,4) 改数字4 同时 去img文件夹 删除多余的背景图即可
