### ISSUE TITLE
能不能提交PR到Lean大的源里的argon主题

### ISSUE THREAD

**Issue by DreamWalkerXZ** [jerrykuku/luci-theme-argon#50]
能不能提交PR到[Lean大的源](https://github.com/coolsnowwolf/lede)的argon主题，更新一下

**Comment by Hey-Leo** [comment]
自己更新也不是不能用/
cd lede && git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon

**Comment by Hey-Leo** [comment]
用AutoBuild Action的话在DIY那里加上
git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/mine/luci-theme-argon
就行了

**Comment by DreamWalkerXZ** [comment]
感谢
