### ISSUE TITLE
页面错位

### ISSUE THREAD

**Issue by dragon888888888888** [jerrykuku/luci-theme-argon#501]
网络-接口  设置CPE模块接口错位

**Openwrt (please complete the following information):**
 - Versiosn: [e.g. R24.5.1-lean]
 - Theme [e.g. argon]
 - Version [e.g. 1.8.3]
![image](https://github.com/jerrykuku/luci-theme-argon/assets/167013420/c2ac6cd4-45e3-4f7c-ae31-4afe996bf5d7)

**Comment by SpeedPartner** [comment]
请问截图中的接口是什么类型的协议?另外,其他类型接口是否存在相同问题?

**Comment by dragon888888888888** [comment]
> 请问截图中的接口是什么类型的协议?另外,其他类型接口是否存在相同问题?

UMTS/GPRS/EV-DO   QMI  等都试过了
都是一样的问题
![111](https://github.com/jerrykuku/luci-theme-argon/assets/167013420/ff04fab9-4505-419e-9fbb-f20c5c086636)
![112](https://github.com/jerrykuku/luci-theme-argon/assets/167013420/4c199d2d-413d-40df-8653-8cce41330db2)

**Comment by SpeedPartner** [comment]
除了插卡相关网络协议外的协议,请问是否正常?

**Comment by dragon888888888888** [comment]
> 除了插卡相关网络协议外的协议,请问是否正常?

其它的正常

**Comment by SpeedPartner** [comment]
好吧,目前没办法测试修复;
后续有空重新编译带插卡相关网络协议的固件,再随缘修复
