### ISSUE TITLE
请问我的argon主题的进度条为什么是这样子的。

### ISSUE THREAD

**Issue by qzrsa** [jerrykuku/luci-theme-argon#505]
不好意思，纯萌新。
想问一下。为什么我编译出来的argon主题是这个样子。
![QQ截图20240705131249](https://github.com/jerrykuku/luci-theme-argon/assets/44892049/d6980b5b-5e2d-449a-b9e4-c135a6f4e05c)
而不是图片那种动态的。网上没有搜到相关解决方案....

**Comment by SpeedPartner** [comment]
动态气泡进度条,目前仅限于18.06分支的LuCI;
18.06分支目前已经趋于稳定.

**Comment by qzrsa** [comment]
> 动态气泡进度条,目前仅限于18.06分支的LuCI; 18.06分支目前已经趋于稳定.

感谢大佬回复
