### ISSUE TITLE
uci-mod-dashboard is not readable with argon 

### ISSUE THREAD

**Issue by shahram7** [jerrykuku/luci-theme-argon#506]
**Describe the bug**
please see the screen-shot.
uci-mod-dashboard is not readable in Argon dark.

![image](https://github.com/jerrykuku/luci-theme-argon/assets/34509793/ee5d315a-d57c-48ad-b818-0ee70d1cc341)
 
I need to open "Argon Config" and click on "Save" without any changes, then is dashboard like the second screen-shot readable.

![image](https://github.com/jerrykuku/luci-theme-argon/assets/34509793/ca2b3f3b-d561-47cc-a020-d0d3e859e72a)

**To Reproduce**
1. Log in to your Luci UI and the Dashboard is going to be shown

**Expected behavior**
a readable dashboard is expected : )

**Openwrt (please complete the following information):**
 - Versiosn: OpenWrt 23.05.3 r23809-234f1a2efa
 - luci-app-argon-config - 0.9 
 - luci-theme-argon - 2.3.1

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version:  126.0.6478.127

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 14
 - Browser: Brave
 - Version 1.67.123

**Comment by shahram7** [comment]
oh this is a known issue: https://github.com/jerrykuku/luci-theme-argon/issues/305#issuecomment-1146193744

**Comment by st7105** [comment]
Problem is actual.
