### ISSUE TITLE
argon theme 2.3.1版本问题

### ISSUE THREAD

**Issue by lanruihua026** [jerrykuku/luci-theme-argon#509]
如图所示，lean源码编译最新版本argon主题后侧边栏无法显示，重启后系统又切换为openwrt默认主题
![屏幕截图 2024-07-16 114914](https://github.com/user-attachments/assets/4ba63062-6a1e-4275-a32f-1b0ab385ec94)

**Comment by SpeedPartner** [comment]
大哥,lean的LEDE源码,请切换到18.06分支拉取源码再编制

**Comment by SpeedPartner** [comment]
18.06分支目前的版本是v1.8.3
