### ISSUE TITLE
lean openwrt wrtn 显示错误。

### ISSUE THREAD

**Issue by hyird** [jerrykuku/luci-theme-argon#51]
![image](https://user-images.githubusercontent.com/31695447/78850876-e49ec380-7a4a-11ea-94a0-10ed478ffa15.png)

希望能修一下 只有默认主题能正确显示这个

**Comment by jerrykuku** [comment]
麻烦告知下这个luci app 的名称

**Comment by hyird** [comment]
luci-app-wrtbwmon

**Comment by hyird** [comment]
![image](https://user-images.githubusercontent.com/31695447/78851125-9e962f80-7a4b-11ea-8aa7-2377f0ed6364.png)
![image](https://user-images.githubusercontent.com/31695447/78851139-a5bd3d80-7a4b-11ea-9776-6614d36ac18a.png)
还有passwall 浏览器全屏会出现这个横向的条 反而窗口不会。。。

**Comment by jerrykuku** [comment]
这个是他的template的设计问题

**Comment by hyird** [comment]
其他第三方主题就不会出现。。  不知道哪的问题

**Comment by jerrykuku** [comment]
因为外层盒 的css定义不一样 我没办法照顾到所有的 都不出问题
