### ISSUE TITLE
如何修改左侧菜单的隐藏和显示

### ISSUE THREAD

**Issue by aylgyfqc** [jerrykuku/luci-theme-argon#510]
如题，想修改主题左侧菜单，想隐藏一些itme。

**Comment by aylgyfqc** [comment]
大致看了下，没找到在哪个文件中可以修改的

**Comment by aylgyfqc** [comment]
![image](https://github.com/user-attachments/assets/be89a486-7ec6-43c0-a173-a1e8ef0d8887)

**Comment by SpeedPartner** [comment]
你的需求与本主题无关,在主题中也无法实现
