### ISSUE TITLE
[BUG] 保存并应用 按钮 下拉栏显示不全

### ISSUE THREAD

**Issue by muink** [jerrykuku/luci-theme-argon#513]
保存并应用 按钮 下拉栏显示不全
已在最新版 Firefox 和 Chromium 下测试得到一样的结果
![image](https://github.com/user-attachments/assets/31a8550b-7000-4490-8058-6f74c1020ebe)

**Comment by sbwml** [comment]
👍给你的发现问题点赞！

上图能直接看出 ul dropdown 这个弹出按钮被其它元素限制了，分享下我自己的解决方案：

给 cbi-page-actions（保存并应用 & 保存 && 重置） 类添加一个 **绝对定位** 属性，让他能在父元素内任何位置进行定位，不被其它元素遮挡。

```diff
 .cbi-page-actions {
   padding: 1rem;
-  text-align: right;
+  position: absolute;
+  right: 0;
   justify-content: flex-end;
 }
```

但是值得注意的是，窗口的高度变化可能会使它遮挡页脚内容，所以可以给 footer 增加一个外边距，大约 3.5 倍字体大小的长度来避免这种情况的出现。

```diff
 footer {
   font-size: .875rem;
   overflow: hidden;
   padding: 1rem;
   text-align: right;
   white-space: nowrap;
   color: #aaa;
+  margin-top: 3.5rem;
 }
```

如果你是强迫症患者还可以调整一下 cbi-dropdown 的左右外边距，使它居中。
![QQ_1723286337837](https://github.com/user-attachments/assets/525dce68-eab2-4ecd-9d1b-d50c3c64b5fc)


最终的效果：

PC 端

100%
![QQ_1723286448351](https://github.com/user-attachments/assets/24a398e0-c6cc-4824-a1f3-7ce5daae3c17)

125%
![QQ_1723286459560](https://github.com/user-attachments/assets/378c19ea-39c2-413d-b0df-dee4792b7e2b)

175%
![QQ_1723286502466](https://github.com/user-attachments/assets/2981f8b1-aa42-4c35-8bce-36b361d7d9d5)

移动端

![QQ_1723286530844](https://github.com/user-attachments/assets/f35cae3a-3a03-4286-b4b2-82702c53c5f0)

**Comment by muink** [comment]
感谢您的解答
我根据您的回答修改了 cascade.less 和 cascade.css
但是 ul dropdown 还是有问题
我对 css 并不了解，不知如何修改，期待能得到您的解答
<img width="493" alt="image" src="https://github.com/user-attachments/assets/78f1ca8c-06c7-41ec-9652-9503542b2a09">
