### ISSUE TITLE
lean-6.6内核luci-theme-argon左边空白，能不能修修左边栏没 了

### ISSUE THREAD

**Issue by Dr-chen99** [jerrykuku/luci-theme-argon#515]
![1](https://github.com/user-attachments/assets/c6a1f118-cc75-4163-96a4-c7628db5d337)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Openwrt (please complete the following information):**
 - Versiosn: [e.g. 18.06-lean]
 - Theme [e.g. argon]
 - Version [e.g. 2.27]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SpeedPartner** [comment]
未提供主题版本信息

**Comment by SpeedPartner** [comment]
按你的截图来看,目前18.06分支的主题,子选项卡已做外侧边距对齐;
故初步判定你可能是编译/安装成了主分支的主题版本,从而导致不兼容.

**Comment by SpeedPartner** [comment]
[相同issue参考 #487](https://github.com/jerrykuku/luci-theme-argon/issues/487)

**Comment by Dr-chen99** [comment]
> 未提供主题版本信息

lean 的master分支 6.6内核，也是默认分支

**Comment by SpeedPartner** [comment]
幽默,你有没有搞清楚?我说的是主题的版本,不是LEDE版本,也不是内核版本.
LEDE的LuCI版本一直是18.06,与内核版本无关,只适配本主题的18.06分支,你究竟看没看本主题的README?

**Comment by SpeedPartner** [comment]
另外,根据你之前在[其他项目发布的相同issue](https://github.com/sbwml/luci-theme-argon/issues/2)
故同样判断你是错误编译/安装了对方项目的官方OpenWRT版本的主题,也就是本主题的master分支,从而导致与LEDE的18.06版本的LuCI不兼容.
[主题分支介绍](https://github.com/sbwml/luci-theme-argon/issues/2)
[主题18.06分支](https://github.com/jerrykuku/luci-theme-argon/tree/18.06)
[置顶issue - lede 如何设置你的主题为默认主题呢？](https://github.com/jerrykuku/luci-theme-argon/issues/428)

**Comment by Dr-chen99** [comment]
> 幽默,你有没有搞清楚?我说的是主题的版本,不是LEDE版本,也不是内核版本. LEDE的LuCI版本一直是18.06,与内核版本无关,只适配本主题的18.06分支,你究竟看没看本主题的README?
知道了，我前面选了master分支

> 幽默,你有没有搞清楚?我说的是主题的版本,不是LEDE版本,也不是内核版本. LEDE的LuCI版本一直是18.06,与内核版本无关,只适配本主题的18.06分支,你究竟看没看本主题的README?

那就是我选错了分支，我选了master去搞得lean
