### ISSUE TITLE
1.删除lede的luci源中的argon旧版本主题(需先feeds update):

### ISSUE THREAD

**Issue by mcusee** [jerrykuku/luci-theme-argon#529]
lede修改默认主题的文件好像变了，麻烦作者给看看，改一下方法。

**Comment by SpeedPartner** [comment]
感谢反馈.

确实,最近LEDE已将LuCI升级为23.05(兼容lua的版本),虽然已兼容18.06(lua)的部分应用,但是18.06的主题已不再兼容.
如果还需要使用18.06分支的主题,请在编译固件前修改LEDE源码中[feeds.conf.default](https://github.com/coolsnowwolf/lede/blob/master/feeds.conf.default),
将第二行`#src-git luci https://github.com/coolsnowwolf/luci`的注释符号"#"删除,
再将第三行的`src-git luci https://github.com/coolsnowwolf/luci`的前面插入注释符号"#";

也就是需要将:
```
#src-git luci https://github.com/coolsnowwolf/luci
src-git luci https://github.com/coolsnowwolf/luci.git;openwrt-23.05
```
更改为:
```
src-git luci https://github.com/coolsnowwolf/luci
#src-git luci https://github.com/coolsnowwolf/luci.git;openwrt-23.05
```
将LEDE编译使用的LuCI源,更改回以前的18.06版本即可.

**Comment by SpeedPartner** [comment]
或者在LEDE源码路径下,使用以下命令直接更改LuCI源:
`sed -i '/^#src-git luci https:\/\/github.com\/coolsnowwolf\/luci$/s/^#//' feeds.conf.default && sed -i '/^src-git luci https:\/\/github.com\/coolsnowwolf\/luci\.git;openwrt-23\.05$/s/^/#/' feeds.conf.default`

**Comment by BenjaminX** [comment]
测试过了，直接用 argon 主干 main 分支没有问题了，lede 升级了 luci 版本。

**Comment by zuozhehao** [comment]
> 测试过了，直接用 argon 主干 main 分支没有问题了，lede 升级了 luci 版本。

没看到main 分支。

**Comment by SpeedPartner** [comment]
> 没看到main 分支。

应该为本主题的默认的"master"分支

**Comment by zuozhehao** [comment]
> > 没看到main 分支。
> 
> 应该为本主题的默认的"master"分支

<img width="626" src="https://github.com/user-attachments/assets/60650a6d-ba94-4bfe-b612-617b10d29e04">

@SpeedPartner 试过了，不行

**Comment by SpeedPartner** [comment]
> @SpeedPartner 试过了，不行

编译错主题版本版本导致.
LEDE编译使用目前最新默认的23.05 LuCI时,请拉取本主题默认的master分支源码进行编译,主题makefile中版本为v2.x.x+;
如果你想使用使用本主题18.06分支的版本,那么请按当前issue中的操作,将LEDE源码中的LuCI源码从23.05改成以前的18.06 LuCI,主题makefile中版本为v1.x.x+;
如果在LEDE的源码中更改了LuCI源,请记得make clean后,重新全新编译.

**Comment by zuozhehao** [comment]
> > @SpeedPartner 试过了，不行
> 
> 编译错主题版本版本导致. LEDE编译使用目前最新默认的23.05 LuCI时,请拉取本主题默认的master分支源码进行编译,主题makefile中版本为v2.x.x+; 如果你想使用使用本主题18.06分支的版本,那么请按当前issue中的操作,将LEDE源码中的LuCI源码从23.05改成以前的18.06 LuCI,主题makefile中版本为v1.x.x+; 如果在LEDE的源码中更改了LuCI源,请记得make clean后,重新全新编译.

```
    rm -rf feeds/luci/themes/luci-theme-argon
    git clone -b master https://github.com/jerrykuku/luci-theme-argon.git feeds/luci/themes/luci-theme-argon
```
没错，是master 分支。

**Comment by SpeedPartner** [comment]
> 没错，是master 分支。
可以尝试下本项目当前最新的release,也就是v2.3.1的ipk,安装后是否可以正常应用主题.

**Comment by zuozhehao** [comment]
> > 没错，是master 分支。
> 
> 可以尝试下本项目当前最新的release,也就是v2.3.1的ipk,安装后是否可以正常应用主题.

```
Installing luci-theme-argon (2.3.1) to root...
Configuring luci-theme-argon.
//usr/lib/opkg/info/luci-theme-argon.postinst: .: line 2: can't open '/etc/uci-defaults/30_luci-theme-argon': No such file or directory
```

**Comment by BenjaminX** [comment]
![SCR-20241102-kbbk-2](https://github.com/user-attachments/assets/e8742a06-7032-4ef2-bac1-33749551942f)

LEDE + 直接主干，编译已经可用了。不用切 branch 到以前的18.06分支

**Comment by aiastia** [comment]
没太理解现在 怎么编译  lede 下直接使用  这样吗
    #     cd openwrt/package 		
    #     git clone https://github.com/jerrykuku/luci-theme-argon.git luci-theme-argonn

> ![SCR-20241102-kbbk-2](https://private-user-images.githubusercontent.com/612858/382440323-e8742a06-7032-4ef2-bac1-33749551942f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDI3NjksIm5iZiI6MTczMDcwMjQ2OSwicGF0aCI6Ii82MTI4NTgvMzgyNDQwMzIzLWU4NzQyYTA2LTcwMzItNGVmMi1iYWMxLTMzNzQ5NTUxOTQyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwNjQxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDM2NDFiYTZiOGJiZmZhMzkwZmE1NGMxNDZjOTEzNWMzNTY1YTQ4NmIwMGJkYjU1M2EzYTRhOWIzZTE5MGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xWkISclnpjasTWXRc6oM0kY--D_snAg8OkmhOMhY8EA)
> 
> LEDE + 直接主干，编译已经可用了。不用切 branch 到以前的18.06分支

**Comment by BenjaminX** [comment]
> 没太理解现在 怎么编译 lede 下直接使用 这样吗 # cd openwrt/package # git clone https://github.com/jerrykuku/luci-theme-argon.git luci-theme-argonn
> 
> > ![SCR-20241102-kbbk-2](https://private-user-images.githubusercontent.com/612858/382440323-e8742a06-7032-4ef2-bac1-33749551942f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDI3NjksIm5iZiI6MTczMDcwMjQ2OSwicGF0aCI6Ii82MTI4NTgvMzgyNDQwMzIzLWU4NzQyYTA2LTcwMzItNGVmMi1iYWMxLTMzNzQ5NTUxOTQyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwNjQxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDM2NDFiYTZiOGJiZmZhMzkwZmE1NGMxNDZjOTEzNWMzNTY1YTQ4NmIwMGJkYjU1M2EzYTRhOWIzZTE5MGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xWkISclnpjasTWXRc6oM0kY--D_snAg8OkmhOMhY8EA)
> > LEDE + 直接主干，编译已经可用了。不用切 branch 到以前的18.06分支

是的，不需要切 18.06 适配 LEDE 的分支了，LEDE 升级了 luci 版本可以直接用主干 master 代码的 theme 了

**Comment by GreatMichaelLee** [comment]
我试了使用lede luci的23.05分支配合argon的master分支和argon工具的master分支，发现有些问题，第一个问题是默认起来就是暗黑色，而且字体有些怪，第二个argon工具修改主题背景无法生效，即修改为高亮或者bing并不起效，依然是暗黑，第三个是有些应用菜单显示不出来，比如openvpn/softether等，passwall也有部分tab变成英文了。麻烦作者看看是lede侧luci的问题呢还是argon的问题呀 @SpeedPartner

**Comment by yzwandyq** [comment]
RPCError
RPC call to luci/getMountPoints failed with error -32000: Object not found
![Snipaste_2024-12-21_01-02-35](https://github.com/user-attachments/assets/1e1f8d98-a8e1-457c-917f-0bd7765ab811)
请问这个报错怎么解决啊

**Comment by yzwandyq** [comment]
@SpeedPartner @BenjaminX 
请问这个报错怎么解决啊，LEDE的最新版本源码，主题是argon的最新版本。
RPCError
RPC call to luci/getMountPoints failed with error -32000: Object not found
![Snipaste_2024-12-21_01-02-35](https://github.com/user-attachments/assets/54404fce-cff6-4410-b3b2-e3d40bc51c71)

**Comment by SpeedPartner** [comment]
> 我试了使用lede luci的23.05分支配合argon的master分支和argon工具的master分支，发现有些问题，第一个问题是默认起来就是暗黑色，而且字体有些怪，第二个argon工具修改主题背景无法生效，即修改为高亮或者bing并不起效，依然是暗黑，第三个是有些应用菜单显示不出来，比如openvpn/softether等，passwall也有部分tab变成英文了。麻烦作者看看是lede侧luci的问题呢还是argon的问题呀 @SpeedPartner

抱歉,我和[jerrykuku](https://github.com/jerrykuku)最近都没有时间,我主要负责维护18.06分支的主题;
master分支的主题目前问题确实比较多,后续有空的话,看有没有机会着手修复.

**Comment by yzwandyq** [comment]
> > 我试了使用lede luci的23.05分支配合argon的master分支和argon工具的master分支，发现有些问题，第一个问题是默认起来就是暗黑色，而且字体有些怪，第二个argon工具修改主题背景无法生效，即修改为高亮或者bing并不起效，依然是暗黑，第三个是有些应用菜单显示不出来，比如openvpn/softether等，passwall也有部分tab变成英文了。麻烦作者看看是lede侧luci的问题呢还是argon的问题呀 @SpeedPartner
> 
> 抱歉,我和[jerrykuku](https://github.com/jerrykuku)最近都没有时间,我主要负责维护18.06分支的主题; master分支的主题目前问题确实比较多,后续有空的话,看有没有机会着手修复.

已经没问题了，我用LEDE最新Luci源码搭配argon最新版本主题不会有这个报错了，是我百度找教程时候不小心添加了些东西进去

**Comment by SpeedPartner** [comment]
> @SpeedPartner @BenjaminX 请问这个报错怎么解决啊，LEDE的最新版本源码，主题是argon的最新版本。 RPCError RPC call to luci/getMountPoints failed with error -32000: Object not found
这个问题应该是最近合并了https://github.com/jerrykuku/luci-theme-argon/pull/517 Pull request导致的,之前我就看到了,但是由于我没有维护master分支主题,所以没有发表评论....
@jerrykuku 麻烦你来看下,可能要回退此次合并

**Comment by SpeedPartner** [comment]
> 已经没问题了，我用LEDE最新Luci源码搭配argon最新版本主题不会有这个报错了，是我百度找教程时候不小心添加了些东西进去

OK,那就好

**Comment by aiastia** [comment]
改成新的主题 编译后nps 和npc 没了
