### ISSUE TITLE
连续两次安装都报错！在不同设备上均报错 难道是我的问题？

### ISSUE THREAD

**Issue by qunture** [jerrykuku/luci-theme-argon#531]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Openwrt (please complete the following information):**
 - Versiosn: [e.g. 18.06-lean]
 - Theme [e.g. argon]
 - Version [e.g. 2.27]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SpeedPartner** [comment]
长时间未提供有效反馈
