### ISSUE TITLE
Lean's LEDE分支R24.10版本已经不支持luci-theme-argon的18.06分支的主题了

### ISSUE THREAD

**Issue by SuitThug3977** [jerrykuku/luci-theme-argon#535]
最新发现，Lean's LEDE在R24.10版本使用argon的18.06分支版本主题编译后进系统会报错，进不了界面。
一番折腾要用master分支的源码编译才可以进界面。
Lean大表示新版的R24.10已经不支持旧版本lua的主题了。

Powered by LuCI openwrt-23.05 branch (git-24.339.48605-e1135e2) / ArgonTheme v2.3.1 / LEDE R24.12.12

**Comment by SpeedPartner** [comment]
已知晓,置顶issue有相关讨论,可以直接拉取本主题master分支源码编译;
或者将LEDE的LuCI源码改回18.06后,继续拉取本主题18.06分支源码进行编译.
