### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by xianfanjie** [jerrykuku/luci-theme-argon#539]
感谢大佬开发的主题

希望桌面和移动端有对应的目录存放背景图片,然后根据ua来简单判断从哪个目录下获取图片作为背景展示。

**Comment by SpeedPartner** [comment]
很遗憾，网页出于安全性的考虑，无法直接访问本地硬盘上的数据，包括移动设备。
这样是为了防止恶意网站获取用户的私人数据和文件。
