### ISSUE TITLE
Docker这个图标在iOS Safari浏览器不显示

### ISSUE THREAD

**Issue by lloyd18** [jerrykuku/luci-theme-argon#54]
其它手机浏览器没测试

![599687702655491171](https://user-images.githubusercontent.com/10294460/79066726-d1128780-7cec-11ea-863b-9846a0e7e8c8.png)

**Comment by jerrykuku** [comment]
最近忙于工作，等忙完一起更新吧

**Comment by lloyd18** [comment]
> 最近忙于工作，等忙完一起更新吧

大佬，两个月过去了，回来吧，我们需要你啊。
