### ISSUE TITLE
在http://192.168.1.1/cgi-bin/luci/admin/status/iptables# 由于信息过多 选择调到其他选项会没有响应

### ISSUE THREAD

**Issue by hyird** [jerrykuku/luci-theme-argon#55]
打开http://192.168.1.1/cgi-bin/luci/admin/status/iptables#  在没有加载完成的情况下会假死
按其他选项 比如 我要去打开dhcp就会无效。无任何反应
在官方主题下无此问题

**Comment by lysssssss** [comment]
按esc就可以停止加载了
