### ISSUE TITLE
Cannot install package luci-theme-argon

### ISSUE THREAD

**Issue by ppp47** [jerrykuku/luci-theme-argon#59]
无法安装软件包luci-theme-argon
大神帮我看看这是什么原因啊？
![捕1获](https://user-images.githubusercontent.com/59086679/80480402-2bfddd00-8983-11ea-9656-c4d72d6925ad.PNG)

**Comment by doushang** [comment]
你已经安装了定制版的argon主题luci-theme-argon-gd

**Comment by jerrykuku** [comment]
先卸载掉其他的版本，在安装吧
