### ISSUE TITLE
luci-theme-argon corrupts my NoTengoBattery version of OpenWRT

### ISSUE THREAD

**Issue by subtilt** [jerrykuku/luci-theme-argon#62]
Hi. I need some help. I am running a modded version of OpenWRT called "NoTengoBattery v1.00.oc c672b" also known as "NoTengoBattery EA6350v3 Custom ROM v1.00.oc".

As soon as I manually download .ipk luci-theme-argon and manually upload it to my router it corrupts the web gui/interface of my OpenWRT firmware. Which argon theme .ipk is compatible with NoTengo's custom OpenWRT firmware? If there are no versions compatible, are there any chance you can create an argon-theme that works for this particular firmware?

Here is the link to the firmware I'm using: https://github.com/NoTengoBattery/openwrt

**Comment by jerrykuku** [comment]
Which version did you download?
Can you provide the Openwrt firmware screenshot?

**Comment by subtilt** [comment]
This is the link I used to download and upgrade my router from OpenWRT to NoTengoBattery custom firmware: https://github.com/NoTengoBattery/openwrt/releases/download/a2cf87-v1.00/2020_04_19-a2cf87-v1.00.oc.tar.bz2

I was already on OpenWRT when I flashed this firmware so I used the sysupgrade image file that you will find in the dev-preview folder in above link.

**Comment by subtilt** [comment]
How do I provide you with a screenshot of my current firmware? Sorry

**Comment by jerrykuku** [comment]
i mean witch argon theme vision did you download?

**Comment by jerrykuku** [comment]
i need a screenshot of your current fimware .you can drag and drop your image in  the input content box.

**Comment by subtilt** [comment]
[notengobattery-v1.00.oc-c672b-ipq40xx-generic-linksys_ea6350v3-squashfs-sysupgrade.bin.zip](https://github.com/jerrykuku/luci-theme-argon/files/4558175/notengobattery-v1.00.oc-c672b-ipq40xx-generic-linksys_ea6350v3-squashfs-sysupgrade.bin.zip)

**Comment by subtilt** [comment]
I've tried to install these two without success. They both corrupt my firmware:

**Comment by jerrykuku** [comment]
sorry  i don't have your device。It mean i can‘t test the theme for that firmware.

**Comment by subtilt** [comment]
Oh I see. So there is no way to "port" argon theme to my firmware?

**Comment by jerrykuku** [comment]
i must know the luci version of your firmware.can you find it?

**Comment by jerrykuku** [comment]
I checked your firmware a few minutes ago， I think the V2.01 is the right version。

**Comment by subtilt** [comment]
Ok perfect. I will make a backup of my settings and then try it. If it fails again I'll just have to reinstall my firmware. Thanks so much. I will let you know if it worked.
