### ISSUE TITLE
与lean代码合并报错

### ISSUE THREAD

**Issue by iwowcn** [jerrykuku/luci-theme-argon#63]
4月30日lean更新 jquery v3.5.0 mark后，合并代码报错如下：
openwrt@openwrt: git pull && ./scripts/feeds update -a && ./scripts/feeds install -a 
Updating 11848e8b..f2f84a68
error: Your local changes to the following files would be overwritten by merge:
	package/lean/luci-theme-argon/htdocs/luci-static/argon/js/jquery.min.js
Please commit your changes or stash them before you merge.
Aborting

**Comment by jerrykuku** [comment]
不要合并 两个版本不一样 会冲突的
请先删除一个

**Comment by iwowcn** [comment]
> 不要合并 两个版本不一样 会冲突的
> 请先删除一个

我是先删除lean的argon，然后git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git ，最后在lede根目录执行git pull && ./scripts/feeds update -a && ./scripts/feeds install -a，之后就报错了，前天编译的时候还好好的。

**Comment by minfengyk** [comment]
> > 不要合并 两个版本不一样 会冲突的
> > 请先删除一个
> 
> 我是先删除lean的argon，然后git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git ，最后在lede根目录执行git pull && ./scripts/feeds update -a && ./scripts/feeds install -a，之后就报错了，前天编译的时候还好好的。

我今天编译一次性通过，是先git pull && ./scripts/feeds update -a && ./scripts/feeds install -a，
再删除lean的argon，然后git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git 。
