### ISSUE TITLE
无法输入用户名导致无法登陆

### ISSUE THREAD

**Issue by geol** [jerrykuku/luci-theme-argon#7]
已经修改过默认用户名，所以……无法登陆。登陆界面似乎没有填写用户的地方，若只填写密码则显示用户名/密码错误。
![39428453-2C91-4EB8-B791-434A07A93100](https://user-images.githubusercontent.com/2117430/66331628-8db61580-e965-11e9-8be8-8124c4870e5e.png)

**Comment by jerrykuku** [comment]
这个需要你自己把隐藏的用户名的input 自己修改出来 默认只是隐藏 并没有删除
