### ISSUE TITLE
在lean openwrt 中的存在的两个小问题

### ISSUE THREAD

**Issue by zhouym233** [jerrykuku/luci-theme-argon#70]
#### 登陆界面
![image](https://user-images.githubusercontent.com/26868483/82724782-2d64c000-9d0b-11ea-87fc-f62e1aa5a416.png)

此处要求输入用户名和密码，却不存在用户名输入框。

#### 无线界面
![image](https://user-images.githubusercontent.com/26868483/82724894-cc89b780-9d0b-11ea-8106-c06a5486bbe3.png)

‘’移除‘’按钮 样式有些问题。
在之前的issue似乎也有提及。

使用的是最新的18.06分支。

**Comment by jerrykuku** [comment]
用户名和密码这个是官方luci的翻译 并不在 theme能控制的范畴，另外一方面 openwrt 默认就是root账户，个人认为用户名存在的意义不是很大。所以隐藏掉了。
这个移除wifi的按钮。我会尽快的测试和修复。
