### ISSUE TITLE
Openwrt master icons missing

### ISSUE THREAD

**Issue by kyoto44** [jerrykuku/luci-theme-argon#75]
I think there's should be icons or something but it's missing and boxes are showed.
![image](https://user-images.githubusercontent.com/17720761/83849592-179ec400-a729-11ea-88bb-863297250723.png)

**Comment by jerrykuku** [comment]
luci->moudle->minify css  disabled

**Comment by kyoto44** [comment]
> luci->moudle->minify css disabled

it works, thank you!

**Comment by castillofrancodamian** [comment]
It would be nice to clarify somewhere.
