### ISSUE TITLE
登录界面无法进入

### ISSUE THREAD

**Issue by MikuVocal** [jerrykuku/luci-theme-argon#78]
由于登录界面只有密码而没有用户名，只输入密码就提示用户名和密码错误。换成其他需要输入用户名的主题就能正常登录，请问该如何解决？
版本：
OpenWrt R20.6.18 / LuCI Master (git-20.141.34051-f750b5f)

**Comment by jerrykuku** [comment]
lean的默认密码是password 你这个可能里记录了用户名密码 在流浏览器里删掉记录用户名密码试试看
