### ISSUE TITLE
分支18.06 字体颜色

### ISSUE THREAD

**Issue by OleStore** [jerrykuku/luci-theme-argon#79]
openclash
路径cgi-bin/luci/admin/services/openclash/config
![2020-06-29_092830](https://user-images.githubusercontent.com/1283711/85964102-f4df9280-b9ea-11ea-894b-b4b45c8a4b2a.jpg)

**Comment by jerrykuku** [comment]
你这个应该是自身问题 我测试过 没问题的

**Comment by OleStore** [comment]
重新拉包解决了
