### ISSUE TITLE
不能看到未保存的配置

### ISSUE THREAD

**Issue by Twinzo1** [jerrykuku/luci-theme-argon#8]
点击保存后，会在右上角出现“未保存的配置”，但是在应用主题后找不到这个位置

**Comment by garypang13** [comment]
编译前执行
`sed -i 's/ucichanges = ucichanges + #j/for k, l in pairs(j) do	  for m, n in pairs(l) do   ucichanges = ucichanges + 1;   end     end/g' package/lean/luci-theme-argon/luasrc/view/themes/argon/header.htm`
或编译后执行
`sed -i 's/ucichanges = ucichanges + #j/for k, l in pairs(j) do	  for m, n in pairs(l) do   ucichanges = ucichanges + 1;   end     end/g' /usr/lib/lua/luci/view/themes/argon/header.htm`

**Comment by Twinzo1** [comment]
明白
