### ISSUE TITLE
防火墙界面“卡死”

### ISSUE THREAD

**Issue by OldHorse188** [jerrykuku/luci-theme-argon#85]
打开防火墙（/cgi-bin/luci/admin/status/iptables）后，内容过多则无法进行其他操作，必须等待防火墙内容全部加载完成。
设备：NanoPi R2S
固件：Klever1988 Minimal

**Comment by jerrykuku** [comment]
防火墙页面 本来内容就特别多，你换了任何的主题都是这么慢。所以这个不是主题的问题。

**Comment by OldHorse188** [comment]
确实绝大部分主题这里都会有这个问题，luci-theme-argon已经是做得非常好的主题了。我是看到 Bootstrap 主题这里没有问题可以点击跳转其他页面，感觉应该还可以改进才来提issue的😀
