### ISSUE TITLE
install without git

### ISSUE THREAD

**Issue by xkuza** [jerrykuku/luci-theme-argon#9]
hi, i have a router with 3.76Mb left on flash, and GIT is not there (takes over 4Mb to install). Would you tell me how to install it via ssh?

OPENWRT 18.06, archer c50

**Comment by jerrykuku** [comment]
you can use `opkg install https://github.com/jerrykuku/luci-theme-argon/releases/download/v1.2/luci-theme-argon_1.2-01-20191109_all.ipk`  the new release only take 1.09Mb

**Comment by xkuza** [comment]
thanks!
