### ISSUE TITLE
很喜欢这个主题求助

### ISSUE THREAD

**Issue by qin9125** [jerrykuku/luci-theme-argon#92]
感谢楼主的辛苦付出，很喜欢这个主题能否适配一下koolshare 2.36固件呢？2.36luci是19.07
![image](https://user-images.githubusercontent.com/32502941/88519256-66c7ed80-d024-11ea-9732-e96bd8fa80c4.png)

**Comment by jerrykuku** [comment]
我都没有用过ks的。

**Comment by qin9125** [comment]
> 我都没有用过ks的。

哈哈哈，好吧，还是感谢，目测应该那个酷软的菜单会错位不正常，

**Comment by jerrykuku** [comment]
已经适配
