### ISSUE TITLE
报错，有时候又正常

### ISSUE THREAD

**Issue by OleStore** [jerrykuku/luci-theme-argon#93]
18.06
对不起，服务器遇到未知错误。

/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute function dispatcher target for entry '/'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute firstchild dispatcher target for entry '/admin'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute function dispatcher target for entry '/admin/status'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute template dispatcher target for entry '/admin/status/overview'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'admin_status/index'.
A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'footer'.
A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/argon/footer'.
A runtime error occured: [string "/usr/lib/lua/luci/view/themes/argon/footer...."]:19: attempt to index field 'luci-theme-argon' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function 
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute function dispatcher target for entry '/'. The called action terminated with an exception: /usr/lib/lua/luci/dispatcher.lua:469: Failed to execute firstchild dispatcher target for entry '/admin'. The called action terminated with an exception: /usr/lib/lua/luci/dispatcher.lua:469: Failed to execute function dispatcher target for entry '/admin/status'. The called action terminated with an exception: /usr/lib/lua/luci/dispatcher.lua:469: Failed to execute template dispatcher target for entry '/admin/status/overview'. The called action terminated with an exception: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'admin_status/index'. A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'footer'. A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/argon/footer'. A runtime error occured: [string "/usr/lib/lua/luci/view/themes/argon/footer...."]:19: attempt to index field 'luci-theme-argon' (a nil value) stack traceback: [C]: in function 'assert' /usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:121: in function
![2020-07-28_073759](https://user-images.githubusercontent.com/1283711/88602384-50ae4180-d0a5-11ea-88e1-e189ffa57443.jpg)

**Comment by jerrykuku** [comment]
主题footer 里面使用了脚本来获取 主题的版本，错误来自于这里，你这个是编译的版本，还是直接安装的ipk？

**Comment by OleStore** [comment]
> 主题footer 里面使用了脚本来获取 主题的版本，错误来自于这里，你这个是编译的版本，还是直接安装的ipk？

直接安装的ipk，今天懒了，没编译，看到有更新，直接安装了ipk

**Comment by jerrykuku** [comment]
等会我再换个新的ipk ，到时测试下试试

**Comment by jerrykuku** [comment]
已经更新了ipk 重新安装测试看看

**Comment by OleStore** [comment]
稍等，我现在安装

**Comment by OleStore** [comment]
暂时退回https://github.com/jerrykuku/luci-theme-argon/commit/3a9d358f996feff7147c9517429369f0aa380d52
登录界面居中，看起来更舒服一点

**Comment by jerrykuku** [comment]
ipk 更新了 代码昨天就更新 只是昨天没有更新ipk

**Comment by OleStore** [comment]
> ipk 更新了 代码昨天就更新 只是昨天没有更新ipk

晚点拉代码编译看看。
