### ISSUE TITLE
登录时会显示倒T字白线，请修复

### ISSUE THREAD

**Issue by ramondelee** [jerrykuku/luci-theme-argon#95]
登录时会显示以下图形的样子，LEAN版本，浏览器360
![无标题](https://user-images.githubusercontent.com/62197872/88680311-f05de500-d122-11ea-9dd9-2e6695e0be6d.png)

**Comment by jerrykuku** [comment]
360 没测试过。。。

**Comment by ramondelee** [comment]
好像不兼容IE11

**Comment by jerrykuku** [comment]
ie 系列也就放弃吧

**Comment by jerrykuku** [comment]
只能支持到老版本的edge

**Comment by ramondelee** [comment]
试了下sogou登录框没有背景，一片白

**Comment by jerrykuku** [comment]
请用chrome

**Comment by ramondelee** [comment]
360是78内核
