### ISSUE TITLE
点击菜单统计→图表，报错100%复现，500 内部服务器错误。

### ISSUE THREAD

**Issue by dolphinpaopao** [jerrykuku/luci-theme-argon#96]
作者你好，感谢做出这款精美的主题，今天全新编译的18.06，lean openwrt，偶然发现这个错误。点击 <统计→图表>，100%会报如图所示的错误，此时除开 <退出> 按钮点击有效外，其他的状态系统服务等菜单按钮统统失效。只能退出后重新登陆。
![报错](https://user-images.githubusercontent.com/20945941/88770365-4a58bc00-d1b0-11ea-8db6-1a0901333275.jpg)
![报错1](https://user-images.githubusercontent.com/20945941/88770589-a6234500-d1b0-11ea-9962-460e3175504a.jpg)
![报错2](https://user-images.githubusercontent.com/20945941/88770597-a8859f00-d1b0-11ea-9d80-6e1b50d946de.jpg)
![报错3](https://user-images.githubusercontent.com/20945941/88770607-aae7f900-d1b0-11ea-928b-a251983792fe.jpg)

**Comment by jerrykuku** [comment]
晚一点修复

**Comment by trombonist852** [comment]
我也是同样的问题 暂时的修复方法是scp进路由器 到/usr/lib/lua/luci/view/themes把argon这个文件夹改权限为0775就可以了

**Comment by trombonist852** [comment]
> 作者你好，感谢做出这款精美的主题，今天全新编译的18.06，lean openwrt，偶然发现这个错误。点击 <统计→图表>，100%会报如图所示的错误，此时除开 <退出> 按钮点击有效外，其他的状态系统服务等菜单按钮统统失效。只能退出后重新登陆。
> ![报错](https://user-images.githubusercontent.com/20945941/88770365-4a58bc00-d1b0-11ea-8db6-1a0901333275.jpg)
> ![报错1](https://user-images.githubusercontent.com/20945941/88770589-a6234500-d1b0-11ea-9962-460e3175504a.jpg)
> ![报错2](https://user-images.githubusercontent.com/20945941/88770597-a8859f00-d1b0-11ea-9d80-6e1b50d946de.jpg)
> ![报错3](https://user-images.githubusercontent.com/20945941/88770607-aae7f900-d1b0-11ea-928b-a251983792fe.jpg)

我也是同样的问题 暂时的修复方法是scp进路由器 到/usr/lib/lua/luci/view/themes把argon这个文件夹改权限为0775就可以了

**Comment by dolphinpaopao** [comment]
> > 作者你好，感谢做出这款精美的主题，今天全新编译的18.06，lean openwrt，偶然发现这个错误。点击 <统计→图表>，100%会报如图所示的错误，此时除开 <退出> 按钮点击有效外，其他的状态系统服务等菜单按钮统统失效。只能退出后重新登陆。
> > ![报错](https://user-images.githubusercontent.com/20945941/88770365-4a58bc00-d1b0-11ea-8db6-1a0901333275.jpg)
> > ![报错1](https://user-images.githubusercontent.com/20945941/88770589-a6234500-d1b0-11ea-9962-460e3175504a.jpg)
> > ![报错2](https://user-images.githubusercontent.com/20945941/88770597-a8859f00-d1b0-11ea-9d80-6e1b50d946de.jpg)
> > ![报错3](https://user-images.githubusercontent.com/20945941/88770607-aae7f900-d1b0-11ea-928b-a251983792fe.jpg)
> 
> 我也是同样的问题 暂时的修复方法是scp进路由器 到/usr/lib/lua/luci/view/themes把argon这个文件夹改权限为0775就可以了

刚远程看了一下，argon文件夹默认就是775的权限。我把里面的四个文件也修改为775权限，重启后还是同样报错。所以支号静待作者来修复了。

**Comment by dolphinpaopao** [comment]
今天编译最新版本，问题解决，感谢作者。issue关闭。
