### ISSUE TITLE
能否调整一下部分设置按钮间距

### ISSUE THREAD

**Issue by Sunnice** [jerrykuku/luci-theme-argon#99]
您好，作者，非常喜欢这个主题，但是近期的更新把无线设置的几个按钮间距弄得大了些，请问能否恢复原来的样子？
![image](https://user-images.githubusercontent.com/44739306/89141889-82794980-d578-11ea-97ef-28af1f89e7a4.png)

**Comment by lfm09** [comment]
@jerrykuku 我也提个建议：今天刚安装这个主题，总体很美观，很不错。感觉唯一不足之处是附带的英文字体不是很好看，而且个性字体容易审美疲劳，建议更换为系统默认字体就好。
